import json
from set_chronology import set_chronology_ocg, set_chronology_tcg

f = open('YGOProDeck_Card_Info.json')
data = json.load(f)
card_info = {}
for card_info_data in data['data']:
    card_info[card_info_data['name']] = card_info_data

pack_types_ocg = [
    'Magazine Promotional Set',
    'Tournament promotion',
    'structure Deck',
    'Limited Edition Pack',
    'Tournament Prize Cards',
    'Magazine promotion',
    'Structure Deck',
    'Vendor Edition',
    'Promotion Pack',
    'Book promotion',
    'Special Edition',
    '+1 Bonus Pack',
    'Game Promotional Set',
    'Tournament promotional card',
    'Duelist Pack',
    'Video Game promotion',
    'Duelist Set',
    'Booster pack',
    'Promotional set',
    'Box set',
    'Booster SP',
    'Video Game Promotional Card Set',
    'Promotional Set',
    'Manga promotion',
    'Core Booster',
    'Duel Terminal',
    'Film promotion',
    'Booster Pack',
    'Collectors Pack',
    'Animation Chronicle',
    'Binder',
    "Collector's set",
    'V Jump Edition',
    'Tournament promotional set',
    'Tactical-Try Deck',
    'Enhancement Pack',
    'Limited Edition',
    'Booster Pack Reprint Set',
    'Premium Pack',
    'Deck',
    'Guide Promotional Set',
    'Phantom Rage +1 Bonus Pack',
    'Tournament Pack',
    'Booster Pack Set',
    'Deck-Build Pack',
    'Promotional card',
    'Extra Pack',
    'Tin',
    'Video game promotion',
    'Starter Deck'
]

pack_types_tcg = [
    'Astral Pack',
    'Power-Up Pack',
    'Hidden Arsenal',
    'Sneak Peek',
    'Gold Series',
    'Duel Terminal',
    "Collector's Set",
    'Tournament Pack',
    'Booster Pack',
    'Demo Deck',
    'Speed Duel promotional card',
    'Manga promotion',
    'Speed Duel Tournament Pack',
    'Tin',
    'Video game promotion',
    "Collector's set",
    'Bundle',
    'OTS Tournament Pack',
    'Speed Duel Booster Pack',
    'Special Edition',
    'Premium Pack',
    'Deluxe Edition',
    'Lost Art Promotion',
    'Booster pack',
    'Speed Duel Sneak Peek',
    'Core Booster',
    'Duelist Pack',
    'Speed Duel Starter Deck',
    'Video Game promotion',
    'Advent calendar',
    'Promotional card',
    'Promotional set',
    'Structure Deck',
    'Magazine promotion',
    'Promotional cards',
    'Book promotion',
    'Super Edition',
    'Speed Duel demo deck',
    'Collectors Pack',
    'Turbo Pack',
    'Star Pack',
    'Deck-Build Pack',
    'Starter Deck',
    'Value Box',
    'Tournament promotion',
    "Speed Duel collector's set",
    'One of a kind',
    'Champion Pack',
    'Demo deck',
    'Legendary Collection',
    'Booster SP',
    'Collector Box',
    'Speed Duel magazine promotion'
]

for pack in sorted(set(pack_types_ocg + pack_types_tcg)):
    print(pack)