import json
from set_chronology import set_chronology_ocg, set_chronology_tcg

f = open('YGOProDeck_Card_Info.json')
data = json.load(f)
card_info = {}
for card_info_data in data['data']:
    card_info[card_info_data['name']] = card_info_data

pack_types = [
    '+1 Bonus Pack',
    'Advent calendar',
    'Animation Chronicle',
    'Astral Pack',
    'Binder',
    'Book promotion',
    'Booster Pack',
    'Booster Pack Reprint Set',
    'Booster Pack Set',
    'Booster SP',
    'Booster pack',
    'Box set',
    'Bundle',
    'Champion Pack',
    'Collector Box',
    'Collector's Set',
    'Collector's set',
    'Collectors Pack',
    'Core Booster',
    'Deck',
    'Deck-Build Pack',
    'Deluxe Edition',
    'Demo Deck',
    'Demo deck',
    'Duel Terminal',
    'Duelist Pack',
    'Duelist Set',
    'Enhancement Pack',
    'Extra Pack',
    'Film promotion',
    'Game Promotional Set',
    'Gold Series',
    'Guide Promotional Set',
    'Hidden Arsenal',
    'Legendary Collection',
    'Limited Edition',
    'Limited Edition Pack',
    'Lost Art Promotion',
    'Magazine Promotional Set',
    'Magazine promotion',
    'Manga promotion',
    'OTS Tournament Pack',
    'One of a kind',
    'Phantom Rage +1 Bonus Pack',
    'Power-Up Pack',
    'Premium Pack',
    'Promotion Pack',
    'Promotional Set',
    'Promotional card',
    'Promotional cards',
    'Promotional set',
    'Sneak Peek',
    'Special Edition',
    'Speed Duel Booster Pack',
    'Speed Duel Sneak Peek',
    'Speed Duel Starter Deck',
    'Speed Duel Tournament Pack',
    'Speed Duel collector's set',
    'Speed Duel demo deck',
    'Speed Duel magazine promotion',
    'Speed Duel promotional card',
    'Star Pack',
    'Starter Deck',
    'Structure Deck',
    'Super Edition',
    'Tactical-Try Deck',
    'Tin',
    'Tournament Pack',
    'Tournament Prize Cards',
    'Tournament promotion',
    'Tournament promotional card',
    'Tournament promotional set',
    'Turbo Pack',
    'V Jump Edition',
    'Value Box',
    'Vendor Edition',
    'Video Game Promotional Card Set',
    'Video Game promotion',
    'Video game promotion'
]