set_chronology = {
    "Legend of Blue Eyes White Dragon": ["Core Booster", "8 March 2002"],
    "Yu-Gi-Oh! Dark Duel Stories promotional cards": ["Video game promotion", "19 March 2002"],
    "Starter Deck: Yugi": ["Starter Deck", "29 March 2002"],
    "Starter Deck: Kaiba": ["Starter Deck", "29 March 2002"],
    "Metal Raiders": ["Core Booster", "26 June 2002"],
    "Tournament Pack: 1st Season": ["Tournament Pack", "1 September 2002"],
    "Spell Ruler": ["Core Booster", "16 September 2002"],
    "Tournament Pack: 2nd Season": ["Tournament Pack", "1 October 2002"],
    "Booster Pack Collectors Tins 2002": ["Tin", "4 October 2002"],
    "Yu-Gi-Oh! The Eternal Duelist Soul promotional cards": ["Video game promotion", "15 October 2002"],
    "Pharaoh's Servant": ["Core Booster", "20 October 2002"],
    "Yu-Gi-Oh! Forbidden Memories Premium Edition promotional cards": ["Video game promotion", "26 November 2002"],
    "Shonen Jump Vol. 1, Issue 1 promotional card": ["Magazine promotion", "26 November 2002"],
    "McDonald's Promotional Cards": ["Promotional set", "20 December 2002"],
    "Duelist League Series 1 participation cards": ["Tournament promotion", "1 January 2003"],
    "Yu-Gi-Oh! The Duelists of the Roses promotional cards": ["Video game promotion", "16 February 2003"],
    "Labyrinth of Nightmare": ["Core Booster", "1 March 2003"],
    "Tournament Pack: 3rd Season": ["Tournament Pack", "1 March 2003"],
    "Starter Deck: Joey": ["Starter Deck", "30 March 2003"],
    "Starter Deck: Pegasus": ["Starter Deck", "30 March 2003"],
    "Yu-Gi-Oh! Worldwide Edition: Stairway to the Destined Duel promotional cards": ["Video game promotion", "15 April 2003"],
    "Legacy of Darkness": ["Core Booster", "6 June 2003"],
    "Duelist League Series 2 participation cards": ["Tournament promotion", "15 July 2003"],
    "Pharaonic Guardian": ["Core Booster", "18 July 2003"],
    "Collectible Tins 2003": ["Tin", "1 September 2003"],
    "Tournament Pack 4": ["Tournament Pack", "1 October 2003"],
    "Magician's Force": ["Core Booster", "10 October 2003"],
    "Duel Master's Guide promotional cards": ["Book promotion", "28 October 2003"],
    "Yu-Gi-Oh! The Falsebound Kingdom promotional cards": ["Video game promotion", "4 November 2003"],
    "Yu-Gi-Oh! The Sacred Cards promotional cards": ["Video game promotion", "4 November 2003"],
    "Yu-Gi-Oh! Power of Chaos: Yugi the Destiny promotional cards": ["Video game promotion", "18 November 2003"],
    "Yu-Gi-Oh! Power of Chaos: Yugi the Destiny Limited Collector's Edition": ["Video game promotion", "28 November 2003"],
    "Dark Crisis": ["Core Booster", "1 December 2003"],
    "Duelist League Series 3 participation card": ["Tournament promotion", "Unknown 2003"],
    "Shonen Jump Vol. 2, Issue 1 promotional card": ["Magazine promotion", "1 January 2004"],
    "Yu-Gi-Oh! World Championship Tournament 2004 promotional cards": ["Video game promotion", "10 February 2004"],
    "Invasion of Chaos": ["Core Booster", "1 March 2004"],
    "Starter Deck: Yugi Evolution": ["Starter Deck", "1 March 2004"],
    "Starter Deck: Kaiba Evolution": ["Starter Deck", "1 March 2004"],
    "Yu-Gi-Oh! The Dawn of Destiny promotional cards": ["Video game promotion", "23 March 2004"],
    "Invasion of Chaos: Special Edition": ["Special Edition", "1 April 2004"],
    "Yu-Gi-Oh! Power of Chaos: Kaiba the Revenge promotional cards": ["Video game promotion", "6 April 2004"],
    "Kids' WB! Duel of Destiny promotional card": ["Promotional card", "5 May 2004"],
    "Ancient Sanctuary": ["Core Booster", "1 June 2004"],
    "Yu-Gi-Oh! Reshef of Destruction promotional cards": ["Video game promotion", "29 June 2004"],
    "Yu-Gi-Oh! Power of Chaos: Joey the Passion promotional cards": ["Video game promotion", "29 June 2004"],
    "Yu-Gi-Oh! Trading Card Game Tour 2004 promotional card": ["Tournament promotion", "19 June 2004"],
    "Yu-Gi-Oh! World Championship 2004 prize cards": ["Tournament promotion", "25 July 2004"],
    "Exclusive Pack": ["Promotional set", "1 August 2004"],
    "Movie Pack": ["Promotional set", "13 August 2004"],
    "Collectible Tins 2004": ["Tin", "1 September 2004"],
    "Duelist League Series 5 participation card": ["Tournament promotion", "1 September 2004"],
    "Soul of the Duelist": ["Core Booster", "1 October 2004"],
    "Hobby League 1 participation cards A": ["Tournament promotion", "1 October 2004"],
    "Dark Beginning 1": ["Booster Pack", "12 October 2004"],
    "Yu-Gi-Oh! Destiny Board Traveler promotional cards": ["Video game promotion", "26 October 2004"],
    "Tournament Pack 5": ["Tournament Pack", "1 November 2004"],
    "Yu-Gi-Oh! The Movie Ani-Manga promotional card": ["Manga promotion", "1 November 2004"],
    "Yu-Gi-Oh! Capsule Monster Coliseum promotional cards": ["Video game promotion", "26 November 2004"],
    "Hobby League 1 participation cards B": ["Tournament promotion", "December 2004"],
    "Rise of Destiny": ["Core Booster", "1 December 2004"],
    "Master Collection Volume 1": ["Collector's set", "1 December 2004"],
    "Duelist League Series 6 participation card": ["Tournament promotion", "1 December 2004"],
    "Shonen Jump Championship 2004 Prize Card": ["Tournament promotion", "1 December 2004"],
    "Duelist League Series 4 participation card": ["Tournament promotion", "Unknown 2004"],
    "Shonen Jump Vol. 3, Issue 1 promotional card": ["Magazine promotion", "1 January 2005"],
    "Structure Deck: Dragon's Roar": ["Structure Deck", "1 January 2005"],
    "Structure Deck: Zombie Madness": ["Structure Deck", "1 January 2005"],
    "Rise of Destiny: Special Edition": ["Special Edition", "1 February 2005"],
    "Hobby League 1 participation cards C": ["Tournament promotion", "February 2005"],
    "Yu-Gi-Oh! 7 Trials to Glory: World Championship Tournament 2005 promotional cards": ["Video game promotion", "15 February 2005"],
    "Flaming Eternity Sneak Peek Participation Card": ["Sneak peek", "26 February 2005"],
    "Flaming Eternity": ["Core Booster", "1 March 2005"],
    "Dark Revelation Volume 1": ["Booster Pack", "19 March 2005"],
    "Duelist League Series 7 participation card": ["Tournament promotion", "1 April 2005"],
    "Structure Deck: Blaze of Destruction": ["Structure Deck", "6 May 2005"],
    "Structure Deck: Fury from the Deep": ["Structure Deck", "6 May 2005"],
    "The Lost Millennium Sneak Peek Participation Card": ["Sneak Peek", "28 May 2005"],
    "Shonen Jump Vol. 3, Issue 6 promotional card": ["Magazine promotion", "June 2005"],
    "The Lost Millennium": ["Core Booster", "1 June 2005"],
    "Tournament Pack 6": ["Tournament Pack", "1 June 2005"],
    "The Lost Millennium: Special Edition": ["Special Edition", "10 June 2005"],
    "Duelist League Series 8 participation card": ["Tournament promotion", "30 June 2005"],
    "Dark Beginning 2": ["Booster Pack", "27 July 2005"],
    "Make-A-Wish Foundation promotional card": ["One of a kind", "5 August 2005"],
    "Cybernetic Revolution Sneak Peek Participation Card": ["Sneak Peek", "6 August 2005"],
    "Yu-Gi-Oh! World Championship 2005 prize cards": ["Tournament promotion", "7 August 2005"],
    "Cybernetic Revolution": ["Core Booster", "17 August 2005"],
    "Shonen Jump Championship 2005 Prize Card": ["Tournament promotion", "20 August 2005"],
    "Yu-Gi-Oh! Nightmare Troubadour promotional cards": ["Video game promotion", "30 August 2005"],
    "Shonen Jump Vol. 3, Issue 9 promotional card": ["Magazine promotion", "September 2005"],
    "Collectible Tins 2005": ["Tin", "1 September 2005"],
    "Forbidden Legacy": ["Special Edition", "1 October 2005"],
    "Dark Revelation Volume 2": ["Booster Pack", "20 October 2005"],
    "Master Collection Volume 2": ["Collector's set", "24 October 2005"],
    "Structure Deck: Warrior's Triumph": ["Structure Deck", "28 October 2005"],
    "Shonen Jump Vol. 3, Issue 11 promotional card": ["Magazine promotion", "November 2005"],
    "Tournament Pack 7": ["Tournament Pack", "1 November 2005"],
    "Elemental Energy Sneak Peek Participation Card": ["Sneak Peek", "5 November 2005"],
    "Elemental Energy": ["Core Booster", "16 November 2005"],
    "Elemental Energy: Special Edition": ["Special Edition", "30 November 2005"],
    "Pharaoh Tour 2005 promotional cards": ["Tournament promotion", "17 December 2005"],
    "Hobby League 2 participation card A": ["Tournament promotion", "January 2006"],
    "Shonen Jump Vol. 4, Issue 1 promotional card": ["Magazine promotion", "1 January 2006"],
    "Duelist League Series 9 participation card": ["Tournament promotion", "3 January 2006"],
    "Yu-Gi-Oh! GX Duel Academy promotional cards": ["Video game promotion", "10 January 2006"],
    "Structure Deck: Spellcaster's Judgment": ["Structure Deck", "18 January 2006"],
    "Hobby League 2 participation card B": ["Tournament promotion", "February 2006"],
    "Shonen Jump Vol. 4, Issue 2 promotional card": ["Magazine promotion", "February 2006"],
    "Duelist Pack: Jaden Yuki": ["Duelist Pack", "8 February 2006"],
    "Duelist Pack: Chazz Princeton": ["Duelist Pack", "8 February 2006"],
    "Shadow of Infinity Sneak Peek Participation Card": ["Sneak Peek", "18 February 2006"],
    "Shadow of Infinity": ["Core Booster", "18 February 2006"],
    "Yu-Gi-Oh! Double Pack promotional cards": ["Video game promotion", "22 February 2006"],
    "Hobby League 2 participation card C": ["Tournament promotion", "March 2006"],
    "Duelist Pack: Special Edition": ["Special Edition", "9 March 2006"],
    "Yu-Gi-Oh! Ultimate Masters: World Championship Tournament 2006 promotional cards": ["Video game promotion", "14 March 2006"],
    "Starter Deck 2006": ["Starter Deck", "23 March 2006"],
    "Hobby League 2 participation card D": ["Tournament promotion", "January 2006"],
    "Shadow of Infinity: Special Edition": ["Special Edition", "1 April 2006"],
    "Yu-Gi-Oh! GX Special Edition": ["Special Edition", "1 April 2006"],
    "Tournament Pack 8": ["Tournament Pack", "28 April 2006"],
    "Duelist League Series 10 participation card": ["Tournament promotion", "28 April 2006"],
    "Hobby League 2 participation card E": ["Tournament promotion", "May 2006"],
    "Shonen Jump Vol. 4, Issue 5 promotional card": ["Magazine promotion", "May 2006"],
    "Shonen Jump May 2006 subscription bonus": ["Magazine promotion", "May 2006"],
    "Shonen Jump Championship 2006 Prize Card": ["Tournament promotion", "6 May 2006"],
    "Enemy of Justice Sneak Peek Participation Card": ["Sneak Peek", "13 May 2006"],
    "Structure Deck: Invincible Fortress": ["Structure Deck", "15 May 2006"],
    "Enemy of Justice": ["Core Booster", "17 May 2006"],
    "Hobby League 2 participation card F": ["Tournament promotion", "June 2006"],
    "Hobby League 3 participation card A": ["Tournament promotion", "July 2006"],
    "Yu-Gi-Oh! World Championship 2006 prize cards": ["Tournament promotion", "2 July 2006"],
    "Structure Deck: Lord of the Storm": ["Structure Deck", "12 July 2006"],
    "Yu-Gi-Oh! GX Ultimate Beginner's Pack": ["Promotional cards", "19 July 2006"],
    "Duel the Master: Orichalcos Challenge 2006 promotional card": ["Promotional cards", "20 July 2006"],
    "Hobby League 3 participation card B": ["Tournament promotion", "August 2006"],
    "Shonen Jump Vol. 4, Issue 10 promotional card": ["Magazine promotion", "1 August 2006"],
    "Yu-Gi-Oh! Duelist Volume 16 promotional card": ["Manga promotion", "1 August 2006"],
    "Yu-Gi-Oh! Millennium World Volume 4 promotional card": ["Manga promotion", "1 August 2006"],
    "Power of the Duelist Sneak Peek Participation Card": ["Sneak Peek", "5 August 2006"],
    "Power of the Duelist": ["Core Booster", "16 August 2006"],
    "Hobby League 3 participation card C": ["Tournament promotion", "September 2006"],
    "Hobby League 3 participation card D": ["Tournament promotion", "September 2006"],
    "Collectible Tins 2006 Wave 1": ["Tin", "11 September 2006"],
    "Pharaoh Tour 2006 Stop participation card": ["Tournament promotion", "17 September 2006"],
    "Hobby League 3 participation card E": ["Tournament promotion", "October 2006"],
    "Structure Deck: Dinosaur's Rage": ["Structure Deck", "20 October 2006"],
    "Structure Deck: Dinosaur's Rage Special Set": ["Special Edition", "25 October 2006"],
    "Pharaoh Tour 2006 promotional cards": ["Tournament promotion", "28 October 2006"],
    "Hobby League 3 participation card F": ["Tournament promotion", "October 2006"],
    "Collectible Tins 2006 Wave 2": ["Tin", "1 November 2006"],
    "Shonen Jump Vol. 4, Issue 11 promotional card": ["Magazine promotion", "1 November 2006"],
    "Cyberdark Impact Sneak Peek Participation Card": ["Sneak Peek", "4 November 2006"],
    "Champion Pack: Game One": ["Champion Pack", "11 November 2006"],
    "Ultimate Edition 2": ["Special Edition", "11 November 2006"],
    "Cyberdark Impact": ["Core Booster", "15 November 2006"],
    "Yu-Gi-Oh! GX Tag Force promotional cards": ["Video game promotion", "16 November 2006"],
    "Dark Revelation Volume 3": ["Booster Pack", "25 November 2006"],
    "Hobby League 3 participation card G": ["Tournament promotion", "December 2006"],
    "Shonen Jump Vol. 4, Issue 12 promotional card": ["Magazine promotion", "1 December 2006"],
    "McDonald's Promotional Cards 2": ["Promotional set", "26 December 2006"],
    "Shonen Jump Vol. 5, Issue 1 promotional card": ["Magazine promotion", "1 January 2007"],
    "Yu-Gi-Oh! GX Spirit Caller promotional cards": ["Video game promotion", "2 January 2007"],
    "Structure Deck: Machine Re-Volt": ["Structure Deck", "17 January 2007"],
    "Shonen Jump Championship 2007 Prize Card A": ["Tournament promotion", "27 January 2007"],
    "Champion Pack: Game Two": ["Champion Pack", "6 February 2007"],
    "Duelist Pack: Jaden Yuki 2": ["Duelist Pack", "7 February 2007"],
    "Duelist Pack: Aster Phoenix": ["Duelist Pack", "7 February 2007"],
    "Strike of Neos Sneak Peek Participation Card": ["Sneak Peek", "24 February 2007"],
    "Strike of Neos": ["Core Booster", "28 February 2007"],
    "Duelist Pack: Zane Truesdale": ["Duelist Pack", "7 March 2007"],
    "Strike of Neos: Special Edition": ["Special Edition", "14 March 2007"],
    "Yu-Gi-Oh! World Championship 2007 promotional cards": ["Video game promotion", "15 March 2007"],
    "Hobby League 4 participation card A": ["Tournament promotion", "April 2007"],
    "Hobby League 4 participation card B": ["Tournament promotion", "April 2007"],
    "Toys "R" Us Throwdown promotional cards": ["Tournament promotion", "7 April 2007"],
    "Shonen Jump Vol. 5, Issue 4 promotional card": ["Magazine promotion", "21 April 2007"],
    "Hobby League 4 participation card C": ["Tournament promotion", "May 2007"],
    "Force of the Breaker Sneak Peek Participation Card": ["Sneak Peek", "5 May 2007"],
    "Champion Pack: Game Three": ["Champion Pack", "15 May 2007"],
    "Force of the Breaker": ["Core Booster", "16 May 2007"],
    "Hobby League 4 participation card F": ["Tournament promotion", "June 2007"],
    "Shonen Jump Vol. 5, Issue 6 promotional card": ["Magazine promotion", "1 June 2007"],
    "Force of the Breaker: Special Edition": ["Special Edition", "25 June 2007"],
    "Hobby League 5 participation card A": ["Tournament promotion", "July 2007"],
    "Shonen Jump 2007 subscription bonus": ["Magazine promotion", "15 July 2007"],
    "Starter Deck: Jaden Yuki": ["Starter Deck", "25 July 2007"],
    "Starter Deck: Syrus Truesdale": ["Starter Deck", "25 July 2007"],
    "Premium Pack": ["Premium Pack", "26 July 2007"],
    "Yu-Gi-Oh! World Championship 2007 prize cards": ["Tournament promotion", "28 July 2007"],
    "Hobby League 5 participation card B": ["Tournament promotion", "August 2007"],
    "Tactical Evolution Sneak Peek Participation Card": ["Sneak Peek", "4 August 2007"],
    "Hobby League 4 participation card D": ["Tournament promotion", "4 August 2007"],
    "Tactical Evolution": ["Core Booster", "12 August 2007"],
    "Shonen Jump Championship 2007 Prize Card B": ["Tournament promotion", "18 August 2007"],
    "Collectible Tins 2007 Wave 1": ["Tin", "29 August 2007"],
    "Hobby League 5 participation card C": ["Tournament promotion", "September 2007"],
    "Shonen Jump Vol. 5, Issue 9 promotional card": ["Magazine promotion", "1 September 2007"],
    "Champion Pack: Game Four": ["Champion Pack", "4 September 2007"],
    "Tactical Evolution: Special Edition": ["Special Edition", "12 September 2007"],
    "Yu-Gi-Oh! GX Tag Force 2 promotional cards": ["Video game promotion", "27 September 2007"],
    "Hobby League 5 participation card D": ["Tournament promotion", "October 2007"],
    "Pharaoh Tour 2007 promotional cards": ["Tournament promotion", "13 October 2007"],
    "Rise of the Dragon Lords Structure Deck": ["Structure Deck", "24 October 2007"],
    "Hobby League 5 participation card E": ["Tournament promotion", "November 2007"],
    "Shonen Jump Vol. 5, Issue 11 promotional card": ["Magazine promotion", "1 November 2007"],
    "Gladiator's Assault Sneak Peek Participation Card": ["Sneak Peek", "3 November 2007"],
    "GX Next Generation": ["Special Edition", "3 November 2007"],
    "Yu-Gi-Oh! GX Volume 1 promotional card": ["Manga promotion", "6 November 2007"],
    "Hobby League 4 participation card E": ["Tournament promotion", "10 November 2007"],
    "Yu-Gi-Oh! Elemental Hero Collection 1": ["Promotional set", "13 November 2007"],
    "Yu-Gi-Oh! Elemental Hero Collection 2": ["Promotional set", "13 November 2007"],
    "Gladiator's Assault": ["Core Booster", "14 November 2007"],
    "Dark Revelation Volume 4": ["Booster Pack", "14 November 2007"],
    "Light and Darkness Power Pack": ["Special Edition", "14 November 2007"],
    "Collectible Tins 2007 Wave 2": ["Tin", "15 November 2007"],
    "Yu-Gi-Oh! GX Card Almanac promotional cards": ["Video game promotion", "30 November 2007"],
    "Hobby League 5 participation card F": ["Tournament promotion", "December 2007"],
    "Yu-Gi-Oh! World Championship 2008 promotional cards": ["Video game promotion", "4 December 2007"],
    "Gladiator's Assault: Special Edition": ["Special Edition", "12 December 2007"],
    "Shonen Jump Vol. 6, Issue 1 promotional card": ["Magazine promotion", "1 January 2008"],
    "Champion Pack: Game Five": ["Champion Pack", "8 January 2008"],
    "Yu-Gi-Oh! GX Tag Force Evolution promotional cards": ["Video game promotion", "8 January 2008"],
    "Limited Edition 1": ["Magazine promotion", "16 January 2008"],
    "Hobby League 6 participation card A": ["Tournament promotion", "21 January 2008"],
    "Duelist Pack: Jaden Yuki 3": ["Duelist Pack", "26 January 2008"],
    "Duelist Pack: Jesse Anderson": ["Duelist Pack", "26 January 2008"],
    "Phantom Darkness Sneak Peek Participation Card": ["Sneak Peek", "26 January 2008"],
    "Hobby League 6 participation card B": ["Tournament promotion", "February 2008"],
    "Shonen Jump Vol. 6, Issue 3 promotional card": ["Magazine promotion", "1 February 2008"],
    "Phantom Darkness": ["Core Booster", "13 February 2008"],
    "Hobby League 6 participation card C": ["Tournament promotion", "March 2008"],
    "Shonen Jump Championship 2008 Prize Card": ["Tournament promotion", "8 March 2008"],
    "Duelist Pack Collection Tin 2008": ["Tin", "11 March 2008"],
    "Phantom Darkness: Special Edition": ["Special Edition", "18 March 2008"],
    "Duelist Pack Collection Tin: Jaden Yuki": ["Tin", "23 March 2008"],
    "Hobby League 6 participation card D": ["Tournament promotion", "April 2008"],
    "The Dark Emperor Structure Deck": ["Structure Deck", "2 April 2008"],
    "Gold Series": ["Gold Series", "2 April 2008"],
    "Hobby League 6 participation card E": ["Tournament promotion", "May 2008"],
    "Shonen Jump May 2008 subscription bonus": ["Magazine promotion", "May 2008"],
    "Shonen Jump Vol. 6, Issue 5 promotional card": ["Magazine promotion", "1 May 2008"],
    "Light of Destruction Sneak Peek Participation Card": ["Sneak Peek", "3 May 2008"],
    "Champion Pack: Game Six": ["Champion Pack", "12 May 2008"],
    "Light of Destruction": ["Core Booster", "13 May 2008"],
    "Hobby League 6 participation card F": ["Tournament promotion", "June 2008"],
    "Light of Destruction: Special Edition": ["Special Edition", "18 June 2008"],
    "Hobby League 7 participation card A": ["Tournament promotion", "July 2008"],
    "Retro Pack": ["Booster Pack", "8 July 2008"],
    "Premium Pack 2": ["Premium Pack", "31 July 2008"],
    "Hobby League 7 participation card B": ["Tournament promotion", "August 2008"],
    "Shonen Jump August 2008 subscription bonus": ["Magazine promotion", "1 August 2008"],
    "Duel Terminal - Preview Wave 1": ["Duel Terminal", "4 August 2008"],
    "Starter Deck: Yu-Gi-Oh! 5D's": ["Starter Deck", "5 August 2008"],
    "Shonen Jump Fifth Anniversary Collector's Issue promotional card": ["Magazine promotion", "5 August 2008"],
    "The Duelist Genesis Sneak Peek Participation Card": ["Sneak Peek", "9 August 2008"],
    "Yu-Gi-Oh! World Championship 2008 prize cards": ["Tournament promotion", "10 August 2008"],
    "Token Pack": ["Tournament promotion", "18 August 2008"],
    "Collectible Tins 2008 Wave 1": ["Tin", "18 August 2008"],
    "Hobby League 7 participation card C": ["Tournament promotion", "1 September 2008"],
    "Shonen Jump Vol. 6, Issue 9 promotional card": ["Magazine promotion", "September 2008"],
    "Champion Pack: Game Seven": ["Champion Pack", "1 September 2008"],
    "The Duelist Genesis": ["Core Booster", "2 September 2008"],
    "Exclusive Tins 2008": ["Tin", "23 September 2008"],
    "Hobby League 7 participation card D": ["Tournament promotion", "1 October 2008"],
    "The Duelist Genesis: Special Edition": ["Special Edition", "7 October 2008"],
    "Zombie World Structure Deck": ["Structure Deck", "21 October 2008"],
    "Hobby League 7 participation card E": ["Tournament promotion", "1 November 2008"],
    "Crossroads of Chaos Sneak Peek Participation Card": ["Sneak Peek", "1 November 2008"],
    "Collectible Tins 2008 Wave 2": ["Tin", "3 November 2008"],
    "Yu-Gi-Oh! GX Volume 2 promotional card": ["Manga promotion", "4 November 2008"],
    "Shonen Jump Vol. 6, Issue 12 promotional card": ["Magazine promotion", "5 November 2008"],
    "Crossroads of Chaos": ["Core Booster", "18 November 2008"],
    "Dark Legends": ["Booster Pack", "21 November 2008"],
    "Yu-Gi-Oh! GX Tag Force 3 promotional cards": ["Video game promotion", "28 November 2008"],
    "Hobby League 7 participation card F": ["Tournament promotion", "1 December 2008"],
    "Anniversary Pack": ["Booster Pack", "8 December 2008"],
    "Crossroads of Chaos: Special Edition": ["Special Edition", "9 December 2008"],
    "Shonen Jump Vol. 7, Issue 1 promotional card": ["Magazine promotion", "1 January 2009"],
    "Champion Pack: Game Eight": ["Champion Pack", "5 January 2009"],
    "Shonen Jump February 2009 subscription bonus": ["Magazine promotion", "February 2009"],
    "Duelist Pack: Yusei": ["Duelist Pack", "24 February 2009"],
    "Crimson Crisis Sneak Peek Participation Card": ["Sneak Peek", "28 February 2009"],
    "Crimson Crisis": ["Core Booster", "28 February 2009"],
    "Shonen Jump Vol. 7, Issue 3 promotional card": ["Magazine promotion", "February 2009"],
    "Duelist Pack Collection Tin 2009": ["Tin", "10 March 2009"],
    "Spellcaster's Command Structure Deck": ["Structure Deck", "31 March 2009"],
    "Spellcaster's Command Structure Deck: Special Edition": ["Special Edition", "31 March 2009"],
    "Crimson Crisis: Special Edition": ["Special Edition", "7 April 2009"],
    "Gold Series 2009": ["Gold Series", "21 April 2009"],
    "Shonen Jump Championship 2009 Prize Card": ["Tournament promotion", "26 April 2009"],
    "Shonen Jump Vol. 7, Issue 6 promotional card": ["Magazine promotion", "May 2009"],
    "Raging Battle Sneak Peek Participation Card": ["Sneak Peek", "2 May 2009"],
    "Raging Battle": ["Core Booster", "12 May 2009"],
    "Yu-Gi-Oh! 5D's Wheelie Breakers promotional cards": ["Video game promotion", "19 May 2009"],
    "Yu-Gi-Oh! 5D's World Championship 2009: Stardust Accelerator promotional cards": ["Video game promotion", "19 May 2009"],
    "Yu-Gi-Oh! GX Volume 3 promotional card": ["Manga promotion", "2 June 2009"],
    "Starter Deck: Yu-Gi-Oh! 5D's 2009": ["Starter Deck", "9 June 2009"],
    "Yu-Gi-Oh! R Volume 1 promotional card": ["Manga promotion", "10 June 2009"],
    "Duel Terminal - Preview Wave 2": ["Duel Terminal", "20 June 2009"],
    "Raging Battle: Special Edition": ["Special Edition", "23 June 2009"],
    "Duelist Pack: Yugi": ["Duelist Pack", "7 July 2009"],
    "Yu-Gi-Oh! 5D's National Championship 2009 promotional cards": ["Tournament promotion", "10 July 2009"],
    "Retro Pack 2": ["Booster Pack", "28 July 2009"],
    "Duelist League 2010 participation cards": ["Tournament promotion", "1 August 2009"],
    "Yu-Gi-Oh! World Championship 2009 prize cards": ["Tournament promotion", "9 August 2009"],
    "Turbo Pack: Booster One": ["Turbo Pack", "12 August 2009"],
    "Ancient Prophecy Sneak Peek Participation Card": ["Sneak Peek", "15 August 2009"],
    "Collectible Tins 2009 Wave 1": ["Tin", "18 August 2009"],
    "Shonen Jump Vol. 7, Issue 9 promotional card": ["Magazine promotion", "September 2009"],
    "Ancient Prophecy": ["Core Booster", "1 September 2009"],
    "Ancient Prophecy: Special Edition": ["Special Edition", "9 October 2009"],
    "Warriors' Strike Structure Deck": ["Structure Deck", "27 October 2009"],
    "Stardust Overdrive Sneak Peek Participation Card": ["Sneak Peek", "31 October 2009"],
    "Shonen Jump Vol. 7, Issue 11 promotional card": ["Magazine promotion", "November 2009"],
    "Ancient Prophecy Plus": ["Special Edition", "November 2009"],
    "Duel Disk - Yusei Version": ["Promotional set", "November 2009"],
    "Collectible Tins 2009 Wave 2": ["Tin", "3 November 2009"],
    "Hidden Arsenal": ["Hidden Arsenal", "5 November 2009"],
    "Stardust Overdrive": ["Core Booster", "12 November 2009"],
    "Yu-Gi-Oh! 5D's Tag Force 4 promotional cards": ["Video game promotion", "17 November 2009"],
    "Stardust Overdrive Plus": ["Special Edition", "December 2009"],
    "Stardust Overdrive: Special Edition": ["Special Edition", "15 December 2009"],
    "Shonen Jump Vol. 8, Issue 1 promotional card": ["Magazine promotion", "1 January 2010"],
    "Yu-Gi-Oh! GX Volume 4 promotional card": ["Manga promotion", "4 January 2010"],
    "Twilight Edition": ["Special Edition", "5 January 2010"],
    "Turbo Pack: Booster Two": ["Turbo Pack", "9 January 2010"],
    "Duelist Pack: Yusei 2": ["Duelist Pack", "26 January 2010"],
    "Duel Terminal 1": ["Duel Terminal", "29 January 2010"],
    "Yu-Gi-Oh! R Volume 3 promotional card": ["Manga promotion", "2 February 2010"],
    "Absolute Powerforce Sneak Peek Participation Card": ["Sneak Peek", "6 February 2010"],
    "Absolute Powerforce": ["Core Booster", "16 February 2010"],
    "Machina Mayhem Structure Deck": ["Structure Deck", "23 February 2010"],
    "Yu-Gi-Oh! 5D's World Championship 2010: Reverse of Arcadia promotional cards": ["Video game promotion", "23 February 2010"],
    "Shonen Jump March 2010 subscription bonus": ["Magazine promotion", "March 2010"],
    "Shonen Jump Vol. 8, Issue 3 promotional card": ["Magazine promotion", "1 March 2010"],
    "Duelist Pack Collection Tin 2010": ["Tin", "4 March 2010"],
    "Absolute Powerforce: Special Edition": ["Sneak Peek", "30 March 2010"],
    "Duelist Pack: Kaiba": ["Duelist Pack", "20 April 2010"],
    "Yu-Gi-Oh! R Volume 4 promotional card": ["Manga promotion", "29 April 2010"],
    "Shonen Jump May 2010 subscription bonus": ["Magazine promotion", "May 2010"],
    "The Shining Darkness Sneak Peek Participation Card": ["Sneak Peek", "1 May 2010"],
    "Shonen Jump Vol. 8, Issue 5 promotional card": ["Magazine promotion", "1 May 2010"],
    "The Shining Darkness": ["Core Booster", "11 May 2010"],
    "Yu-Gi-Oh! Championship Series 2010 Prize Cards": ["Tournament promotion", "15 May 2010"],
    "Duel Terminal 2": ["Duel Terminal", "25 May 2010"],
    "Starter Deck: Duelist Toolbox": ["Starter Deck", "1 June 2010"],
    "Yu-Gi-Oh! R Volume 5 promotional card": ["Manga promotion", "2 June 2010"],
    "Gold Series 3": ["Gold Series", "23 June 2010"],
    "Shonen Jump Vol. 8, Issue 7 promotional card": ["Magazine promotion", "1 July 2010"],
    "Turbo Pack: Booster Three": ["Turbo Pack", "12 July 2010"],
    "Hidden Arsenal 2": ["Hidden Arsenal", "20 July 2010"],
    "Duelist Revolution Sneak Peek Participation Card": ["Sneak Peek", "7 August 2010"],
    "World Championship 2010 Card Pack": ["Booster Pack", "14 August 2010"],
    "Yu-Gi-Oh! World Championship 2010 prize cards": ["Tournament promotion", "15 August 2010"],
    "Duelist Revolution": ["Core Booster", "17 August 2010"],
    "Collectible Tins 2010 Wave 1": ["Tin", "26 August 2010"],
    "Shonen Jump Vol. 8, Issue 9 promotional card": ["Magazine promotion", "1 September 2010"],
    "Duelist Revolution: Special Edition": ["Special Edition", "21 September 2010"],
    "Duel Terminal 3": ["Duel Terminal", "25 September 2010"],
    "Legendary Collection": ["Collector's set", "5 October 2010"],
    "Yu-Gi-Oh! GX Volume 5 promotional card": ["Manga promotion", "5 October 2010"],
    "Structure Deck: Marik": ["Structure Deck", "19 October 2010"],
    "Yu-Gi-Oh! 5D's Tag Force 5 promotional cards": ["Video game promotion", "26 October 2010"],
    "Shonen Jump Vol. 8, Issue 11 promotional card": ["Magazine promotion", "1 November 2010"],
    "Collectible Tins 2010 Wave 2": ["Tin", "2 November 2010"],
    "Starstrike Blast Sneak Peek Participation Card": ["Sneak Peek", "6 November 2010"],
    "Starstrike Blast": ["Core Booster", "16 November 2010"],
    "Turbo Pack: Booster Four": ["Turbo Pack", "19 November 2010"],
    "Yu-Gi-Oh! 5D's Duel Transer promotional cards": ["Video game promotion", "21 November 2010"],
    "X-Saber Power-Up": ["Special Edition", "23 November 2010"],
    "Shonen Jump December 2010 subscription bonus": ["Magazine promotion", "December 2010"],
    "Duelist League 2 participation cards": ["Tournament promotion", "1 December 2010"],
    "Hidden Arsenal 3": ["Hidden Arsenal", "2 December 2010"],
    "Shonen Jump Vol. 9, Issue 1 promotional card": ["Magazine promotion", "1 January 2011"],
    "Shonen Jump Scholastic Edition Vol. 9, Issue 1 promotional card": ["Magazine promotion", "1 January 2011"],
    "Duelist Pack: Yusei 3": ["Duelist Pack", "25 January 2011"],
    "Duel Terminal 4": ["Duel Terminal", "25 January 2011"],
    "Storm of Ragnarok Sneak Peek Participation Card": ["Sneak Peek", "5 February 2011"],
    "Storm of Ragnarok": ["Core Booster", "8 February 2011"],
    "Demo Pack": ["Demo deck", "12 February 2011"],
    "Yu-Gi-Oh! 3D Bonds Beyond Time Movie Pack": ["Booster Pack", "26 February 2011"],
    "Yu-Gi-Oh! 3D Bonds Beyond Time Theater distribution card": ["Promotional card", "26 February 2011"],
    "Shonen Jump Vol. 9, Issue 3 promotional card": ["Magazine promotion", "March 2011"],
    "Yu-Gi-Oh! GX Volume 6 promotional card": ["Manga promotion", "1 March 2011"],
    "Dragunity Legion Structure Deck": ["Structure Deck", "4 March 2011"],
    "Storm of Ragnarok: Special Edition": ["Special Edition", "22 March 2011"],
    "Yu-Gi-Oh! 5D's World Championship 2011: Over the Nexus promotional cards": ["Video game promotion", "24 March 2011"],
    "Shonen Jump Vol. 9, Issue 4 promotional card": ["Magazine promotion", "April 2011"],
    "Duelist Pack Collection Tin 2011": ["Tin", "5 April 2011"],
    "Turbo Pack: Booster Five": ["Turbo Pack", "9 April 2011"],
    "Hidden Arsenal 4: Trishula's Triumph": ["Hidden Arsenal", "14 April 2011"],
    "Extreme Victory Sneak Peek Participation Card": ["Sneak Peek", "30 April 2011"],
    "Extreme Victory": ["Core Booster", "5 May 2011"],
    "Yu-Gi-Oh! World Championship Qualifier National Championships 2011 prize cards": ["Tournament promotion", "15 May 2011"],
    "Duel Terminal 5a": ["Duel Terminal", "29 May 2011"],
    "Duelist Pack: Crow": ["Duelist Pack", "31 May 2011"],
    "Shonen Jump Vol. 9, Issue 6 promotional card": ["Magazine promotion", "April 2011"],
    "Shonen Jump June/July 2011 subscription bonus": ["Magazine promotion", "June 2011"],
    "Duelist League 3 participation cards": ["Tournament promotion", "1 June 2011"],
    "Lost Sanctuary Structure Deck": ["Structure Deck", "9 June 2011"],
    "Gold Series 4: Pyramids Edition": ["Gold Series", "1 July 2011"],
    "Yu-Gi-Oh! 5D's Volume 1 promotional card": ["Manga promotion", "6 July 2011"],
    "Starter Deck: Dawn of the Xyz": ["Starter Deck", "12 July 2011"],
    "Hidden Arsenal: Special Edition": ["Special Edition", "21 July 2011"],
    "World Championship 2011 Card Pack": ["Booster Pack", "August 2011"],
    "Turbo Pack: Booster Six": ["Turbo Pack", "4 August 2011"],
    "Generation Force Sneak Peek Participation Card": ["Sneak Peek", "6 August 2011"],
    "Yu-Gi-Oh! Championship Series 2011 Prize Card": ["Tournament promotion", "6 August 2011"],
    "Yu-Gi-Oh! World Championship 2011 prize cards": ["Tournament promotion", "14 August 2011"],
    "Generation Force": ["Core Booster", "16 August 2011"],
    "Yu-Gi-Oh! GX Volume 7 promotional card": ["Manga promotion", "18 August 2011"],
    "Collectible Tins 2011 Wave 1": ["Tin", "25 August 2011"],
    "Shonen Jump Vol. 9, Issue 8 promotional card": ["Magazine promotion", "September 2011"],
    "Generation Force: Special Edition": ["Special Edition", "15 September 2011"],
    "Duel Terminal 5b": ["Duel Terminal", "29 September 2011"],
    "Legendary Collection 2: The Duel Academy Years": ["Collector's set", "4 October 2011"],
    "Legendary Collection 2: The Duel Academy Years Mega Pack": ["Collector's set", "4 October 2011"],
    "Gates of the Underworld Structure Deck": ["Structure Deck", "18 October 2011"],
    "Next-Gen Dueling Kit": ["Value box", "November 2011"],
    "Collectible Tins 2011 Wave 2": ["Tin", "1 November 2011"],
    "Photon Shockwave Sneak Peek Participation Card": ["Sneak Peek", "5 November 2011"],
    "Photon Shockwave": ["Core Booster", "15 November 2011"],
    "Shonen Jump December 2011 subscription bonus": ["Magazine promotion", "December 2011"],
    "Shonen Jump Vol. 9, Issue 10 promotional card": ["Magazine promotion", "December 2011"],
    "Duelist League 13 participation cards": ["Tournament promotion", "1 December 2011"],
    "Samurai Assault": ["Special Edition", "6 December 2011"],
    "Hidden Arsenal 5: Steelswarm Invasion": ["Hidden Arsenal", "6 December 2011"],
    "Dragunity Blast": ["Value Box", "January 2012"],
    "Shonen Jump Vol. 10, Issue 1 promotional card": ["Magazine promotion", "January 2012"],
    "Turbo Pack: Booster Seven": ["Turbo Pack", "1 January 2012"],
    "Yu-Gi-Oh! GX Volume 8 promotional card": ["Manga promotion", "3 January 2012"],
    "Order of Chaos Sneak Peek Participation Card": ["Sneak Peek", "14 January 2012"],
    "Order of Chaos": ["Core Booster", "24 January 2012"],
    "Utopia Value Box": ["Value Box", "February 2012"],
    "Duel Terminal 6a": ["Duel Terminal", "3 February 2012"],
    "Dragons Collide Structure Deck": ["Structure Deck", "7 February 2012"],
    "Yu-Gi-Oh! 5D's Volume 2 promotional card": ["Manga promotion", "7 February 2012"],
    "Ra Yellow Mega Pack": ["Booster Pack", "16 February 2012"],
    "Shonen Jump Vol. 10, Issue 3 promotional card": ["Magazine promotion", "March 2011"],
    "Order of Chaos: Special Edition": ["Special Edition", "1 March 2012"],
    "Premium Collection Tin": ["Tin", "20 March 2012"],
    "Tournament promotion": ["24 March 2012", ""],
    "Yu-Gi-Oh! Championship Series 2012 pre-registration card": ["Tournament promotion", "30 March 2012"],
    "Shonen Jump Vol. 10, Issue 4 promotional card": ["Magazine promotion", "April 2011"],
    "Starter Deck: Xyz Symphony": ["Starter Deck", "12 April 2012"],
    "Galactic Overlord Sneak Peek Participation Card": ["Sneak Peek", "28 April 2012"],
    "Galactic Overlord": ["Core Booster", "8 May 2012"],
    "Duel Terminal 6b": ["Duel Terminal", "25 May 2012"],
    "Battle Pack: Epic Dawn": ["Booster Pack", "28 May 2012"],
    "Battle Pack Tournament Prize Cards": ["Tournament promotion", "29 May 2012"],
    "Weekly Shonen Jump Alpha April 2012 membership promotional card": ["Magazine promotion", "30 May 2012"],
    "Turbo Pack: Booster Eight": ["Turbo Pack", "June 2012"],
    "Duelist League 14 participation cards": ["Tournament promotion", "1 June 2012"],
    "Yu-Gi-Oh! ZEXAL Volume 1 promotional card": ["Manga promotion", "5 June 2012"],
    "Gold Series: Haunted Mine": ["Gold Series", "12 June 2012"],
    "Samurai Warlords Structure Deck": ["Structure Deck", "21 June 2012"],
    "Hidden Arsenal 6: Omega Xyz": ["Hidden Arsenal", "24 July 2012"],
    "Yu-Gi-Oh! GX Volume 9 promotional card": ["Manga promotion", "7 August 2012"],
    "Yu-Gi-Oh! World Championship 2012 prize cards": ["Tournament promotion", "11 August 2012"],
    "Collectible Tins 2012 Wave 1": ["Tin", "14 August 2012"],
    "Return of the Duelist Sneak Peek Participation Card": ["Sneak Peek", "18 August 2012"],
    "Weekly Shonen Jump Alpha July 2012 membership promotional card": ["Magazine promotion", "27 August 2012"],
    "Return of the Duelist": ["Core Booster", "28 August 2012"],
    "Yu-Gi-Oh! Championship Series 2012 Prize Card": ["Tournament promotion", "1 September 2012"],
    "Return of the Duelist: Special Edition": ["Special Edition", "20 September 2012"],
    "Legendary Collection 3: Yugi's World": ["Booster Pack", "27 September 2012"],
    "Legendary Collection 3: Yugi's World Mega Pack": ["Booster Pack", "27 September 2012"],
    "Duel Terminal 7a": ["Duel Terminal", "28 September 2012"],
    "Yu-Gi-Oh! 5D's Volume 3 promotional card": ["Manga promotion", "2 October 2012"],
    "Realm of the Sea Emperor Structure Deck": ["Structure Deck", "10 October 2012"],
    "Weekly Shonen Jump Alpha September 2012 membership promotional card": ["Magazine promotion", "12 October 2012"],
    "Collectible Tins 2012 Wave 2": ["Tin", "25 October 2012"],
    "Abyss Rising Sneak Peek Participation Card": ["Sneak Peek", "3 November 2012"],
    "Abyss Rising": ["Core Booster", "9 November 2012"],
    "Astral Pack One": ["Astral Pack", "16 November 2012"],
    "Yu-Gi-Oh! ZEXAL Volume 2 promotional card": ["Astral Pack", "4 December 2012"],
    "Abyss Rising: Special Edition": ["Special Edition", "5 December 2012"],
    "Duelist League 15 participation cards": ["Tournament promotion", "15 December 2012"],
    "Weekly Shonen Jump Alpha December 2012 membership promotional card": ["Magazine promotion", "25 December 2012"],
    "Collectible Tins 2012 Wave 2.5": ["Tin", "18 January 2013"],
    "Cosmo Blazer Sneak Peek Participation Card": ["Sneak Peek", "19 January 2013"],
    "Cosmo Blazer": ["Sneak Peek", "25 January 2013"],
    "Duel Terminal 7b": ["Duel Terminal", "1 February 2013"],
    "Onslaught of the Fire Kings Structure Deck": ["Structure Deck", "8 February 2013"],
    "Star Pack 2013": ["Star Pack", "1 March 2013"],
    "Zexal Collection Tin": ["Tin", "7 March 2013"],
    "Weekly Shonen Jump March 2013 membership promotional card": ["Magazine promotion", "15 March 2013"],
    "Cosmo Blazer: Special Edition": ["Special Edition", "21 March 2013"],
    "Yu-Gi-Oh! 5D's Volume 4 promotional card": ["Manga promotion", "2 April 2013"],
    "Master Hyperion Value Box": ["Value Box", "9 April 2013"],
    "Yu-Gi-Oh! Championship Series 2013 pre-registration card": ["Tournament promotion", "19 April 2013"],
    "Astral Pack Two": ["Astral Pack", "19 April 2013"],
    "Hidden Arsenal 7: Knight of Stars": ["Hidden Arsenal", "25 April 2013"],
    "Legendary Collection 2: Gameboard Edition": ["Legendary Collection", "May 2013"],
    "Lord of the Tachyon Galaxy Sneak Peek Participation Card": ["Sneak Peek", "11 May 2013"],
    "Lord of the Tachyon Galaxy": ["Core Booster", "17 May 2013"],
    "Yu-Gi-Oh! ZEXAL Volume 3 promotional card": ["Manga promotion", "4 June 2013"],
    "Super Starter: V for Victory": ["Starter Deck", "14 June 2013"],
    "Super Starter Power-Up Pack": ["Power-Up Pack", "14 June 2013"],
    "Battle Pack 2: War of the Giants": ["Booster Pack", "28 June 2013"],
    "Duelist League 16 participation cards": ["Tournament promotion", "1 July 2013"],
    "Weekly Shonen Jump July 2013 membership promotional card": ["Magazine promotion", "9 July 2013"],
    "Number Hunters": ["Collectors Pack", "11 July 2013"],
    "Judgment of the Light Sneak Peek Participation Card": ["Sneak Peek", "3 August 2013"],
    "Judgment of the Light": ["Core Booster", "9 August 2013"],
    "Yu-Gi-Oh! World Championship 2013 prize cards": ["Tournament promotion", "11 August 2013"],
    "2013 Collectible Tins Wave 1": ["Tin", "30 August 2013"],
    "Yu-Gi-Oh! Championship Series 2013 Prize Card": ["Tournament promotion", "1 September 2013"],
    "Saga of Blue-Eyes White Dragon Structure Deck": ["Structure Deck", "12 September 2013"],
    "Astral Pack Three": ["Astral Pack", "12 September 2013"],
    "Shadow Samurai Value Box": ["Value Box", "13 September 2013"],
    "Poseidra Value Box": ["Value Box", "13 September 2013"],
    "Legendary Collection: Gameboard Edition": ["Promotional set", "27 September 2013"],
    "Judgment of the Light: Deluxe Edition": ["Deluxe Edition", "27 September 2013"],
    "Legendary Collection 4: Joey's World": ["Booster Pack", "11 October 2013"],
    "Legendary Collection 4: Joey's World Mega Pack": ["Booster Pack", "11 October 2013"],
    "Weekly Shonen Jump September 2013 membership promotional card": ["Magazine promotion", "24 October 2013"],
    "Shadow Specters Sneak Peek Participation Card": ["Sneak Peek", "2 November 2013"],
    "Yu-Gi-Oh! 5D's Volume 5 promotional card": ["Manga promotion", "5 November 2013"],
    "Shadow Specters": ["Core Booster", "8 November 2013"],
    "2013 Collectible Tins Wave 2": ["Tin", "22 November 2013"],
    "Starter Deck: Yugi Reloaded": ["Starter Deck", "5 December 2013"],
    "Starter Deck: Kaiba Reloaded": ["Starter Deck", "5 December 2013"],
    "Shadow Specters: Special Edition": ["Special Edition", "12 December 2013"],
    "Duelist League 17 participation cards": ["Tournament promotion", "13 December 2013"],
    "Weekly Shonen Jump December 2013 membership promotional card": ["Magazine promotion", "15 December 2013"],
    "Battle City Tournament Kit": ["Promotional set", "1 January 2014"],
    "Yu-Gi-Oh! ZEXAL Volume 4 promotional card": ["Manga promotion", "7 January 2014"],
    "War of the Giants: Round 2": ["Booster Pack", "17 January 2014"],
    "Legacy of the Valiant Sneak Peek Participation Card": ["Sneak Peek", "18 January 2014"],
    "Legacy of the Valiant": ["Core Booster", "24 January 2014"],
    "Yu-Gi-Oh! Day January 2014 promotional card": ["Yu-Gi-Oh! Day", "25 January 2014"],
    "Jump Pack 2014 Issue 1 promotional card": ["Magazine promotion", "31 January 2014"],
    "Cyber Dragon Revolution Structure Deck": ["Structure Deck", "6 February 2014"],
    "Astral Pack Four": ["Astral Pack", "6 February 2014"],
    "Star Pack 2014": ["Star Pack", "21 February 2014"],
    "Legacy of the Valiant: Deluxe Edition": ["Deluxe Edition", "6 March 2014"],
    "Yu-Gi-Oh! Championship Series 2014 pre-registration card": ["Tournament promotion", "7 March 2014"],
    "Weekly Shonen Jump March 2014 membership promotional card": ["Magazine promotion", "13 March 2014"],
    "Premium Gold": ["Gold Series", "27 March 2014"],
    "Fire Fists: Special Edition": ["Special Edition", "4 April 2014"],
    "Jump Pack 2014 Issue 2 promotional card": ["Magazine promotion", "15 April 2014"],
    "Dragons of Legend": ["Collectors Pack", "25 April 2014"],
    "Primal Origin Sneak Peek Participation Card": ["Sneak Peek", "10 May 2014"],
    "Primal Origin": ["Core Booster", "12 May 2014"],
    "Primal Origin Plus": ["Special Edition", "9 June 2014"],
    "Primal Origin: Deluxe Edition": ["Deluxe Edition", "12 June 2014"],
    "Yu-Gi-Oh! ZEXAL World Duel Carnival promotional cards": ["Video game promotion", "26 June 2014"],
    "Realm of Light Structure Deck": ["Structure Deck", "26 June 2014"],
    "Duelist League 18 participation cards": ["Tournament promotion", "27 June 2014"],
    "Yu-Gi-Oh! ZEXAL Volume 5 promotional card": ["Manga promotion", "1 July 2014"],
    "Super Starter: Space-Time Showdown": ["Starter Deck", "11 July 2014"],
    "Space-Time Showdown Power-Up Pack": ["Power-Up Pack", "11 July 2014"],
    "Astral Pack Five": ["Astral Pack", "25 July 2014"],
    "Yu-Gi-Oh! Day July 2014 promotional card": ["Yu-Gi-Oh! Day", "26 July 2014"],
    "Battle Pack 3: Monster League": ["Booster Pack", "1 August 2014"],
    "Duelist Alliance Sneak Peek Participation Card": ["Sneak Peek", "9 August 2014"],
    "Yu-Gi-Oh! World Championship 2014 prize cards": ["Tournament promotion", "11 August 2014"],
    "Duelist Alliance": ["Core Booster", "15 August 2014"],
    "Weekly Shonen Jump August 2014 membership promotional card": ["Magazine promotion", "18 August 2014"],
    "Jump Pack 2014 Issue 3 promotional card": ["Magazine promotion", "22 August 2014"],
    "2014 Mega-Tins": ["Tin", "29 August 2014"],
    "2014 Mega-Tin Mega Pack": ["Booster Pack", "29 August 2014"],
    "Yu-Gi-Oh! 5D's Volume 6 promotional card": ["Manga promotion", "2 September 2014"],
    "Yu-Gi-Oh! Championship Series 2014 Prize Card": ["Tournament promotion", "7 September 2014"],
    "Duelist Alliance: Deluxe Edition": ["Deluxe Edition", "11 September 2014"],
    "Weekly Shonen Jump November 2014 membership promotional card": ["Magazine promotion", "8 October 2014"],
    "Geargia Rampage Structure Deck": ["Structure Deck", "16 October 2014"],
    "Legendary Collection 5D's": ["Booster Pack", "23 October 2014"],
    "Legendary Collection 5D's Mega Pack": ["Booster Pack", "23 October 2014"],
    "The New Challengers Sneak Peek Participation Card": ["Sneak Peek", "1 November 2014"],
    "The New Challengers": ["Core Booster", "7 November 2014"],
    "Noble Knights of the Round Table Box Set": ["Box set", "20 November 2014"],
    "Noble Knights of the Round Table Power-Up Pack": ["Power-Up Pack", "20 November 2014"],
    "The New Challengers: Super Edition": ["Super Edition", "4 December 2014"],
    "Astral Pack Six": ["Astral Pack", "5 December 2014"],
    "Secrets of Eternity Sneak Peek Participation Card": ["Sneak Peek", "10 January 2015"],
    "Secrets of Eternity": ["Core Booster", "16 January 2015"],
    "Yu-Gi-Oh! Day January 2015 promotional card": ["Yu-Gi-Oh! Day", "24 January 2015"],
    "HERO Strike Structure Deck": ["Structure Deck", "30 January 2015"],
    "Yu-Gi-Oh! ZEXAL Volume 6 promotional card": ["Manga promotion", "3 February 2015"],
    "The Secret Forces": ["Booster SP", "13 February 2015"],
    "Weekly Shonen Jump February 2015 membership promotional card": ["Magazine promotion", "19 February 2015"],
    "Secrets of Eternity: Super Edition": ["Special Edition", "27 February 2015"],
    "Yu-Gi-Oh! 5D's Volume 7 promotional card": ["Manga promotion", "3 March 2015"],
    "Premium Gold: Return of the Bling": ["Gold Series", "20 March 2015"],
    "Demo Deck 2015": ["Demo Deck", "30 March 2015"],
    "Yu-Gi-Oh! Championship Series 2015 pre-registration card": ["Tournament promotion", "10 April 2015"],
    "World Superstars": ["Booster Pack", "17 April 2015"],
    "Weekly Shonen Jump April 2015 membership promotional card": ["Magazine promotion", "7 May 2015"],
    "Crossed Souls Sneak Peek Participation Card": ["Sneak Peek", "9 May 2015"],
    "Crossed Souls": ["Core Booster", "15 May 2015"],
    "Saber Force Starter Deck": ["Starter Deck", "29 May 2015"],
    "Dark Legion Starter Deck": ["Starter Deck", "29 May 2015"],
    "Astral Pack Seven": ["Astral Pack", "5 June 2015"],
    "Star Pack ARC-V": ["Star Pack", "12 June 2015"],
    "Duelist Pack: Battle City": ["Duelist Pack", "19 June 2015"],
    "Weekly Shonen Jump July 2015 membership promotional card": ["Magazine promotion", "1 July 2015"],
    "Crossed Souls: Advance Edition": ["Special Edition", "2 July 2015"],
    "Dragons of Legend 2": ["Collectors Pack", "17 July 2015"],
    "Yu-Gi-Oh! Day July 2015 promotional card": ["Yu-Gi-Oh! Day", "25 July 2015"],
    "Clash of Rebellions Sneak Peek Participation Card": ["Sneak Peek", "1 August 2015"],
    "Clash of Rebellions": ["Core Booster", "7 August 2015"],
    "Synchron Extreme Structure Deck": ["Structure Deck", "28 August 2015"],
    "Yu-Gi-Oh! World Championship 2015 attendance cards": ["Tournament promotion", "30 August 2015"],
    "Yu-Gi-Oh! World Championship 2015 prize cards": ["Tournament promotion", "30 August 2015"],
    "Yu-Gi-Oh! ZEXAL Volume 7 promotional card": ["Manga promotion", "1 September 2015"],
    "Yu-Gi-Oh! Championship Series 2015 Prize Card": ["Tournament promotion", "1 September 2015"],
    "2015 Mega-Tins": ["Tin", "17 September 2015"],
    "2015 Mega-Tin Mega Pack": ["Booster Pack", "17 September 2015"],
    "High-Speed Riders": ["Booster SP", "2 October 2015"],
    "Yu-Gi-Oh! 5D's Volume 8 promotional card": ["Manga promotion", "6 October 2015"],
    "Weekly Shonen Jump October 2015 membership promotional card": ["Magazine promotion", "7 October 2015"],
    "Astral Pack Eight": ["Magazine promotion", "23 October 2015"],
    "Dimension of Chaos Sneak Peek Participation Card": ["Sneak Peek", "31 October 2015"],
    "Dimension of Chaos": ["Core Booster", "6 November 2015"],
    "Yugi's Legendary Decks": ["Collector's set", "13 November 2015"],
    "2015 Value Box": ["Value Box", "December 2015"],
    "Master of Pendulum Structure Deck": ["Structure Deck", "4 December 2015"],
    "Dimension of Chaos: Special Edition": ["Special Edition", "10 December 2015"],
    "Clash of Rebellions: Special Edition": ["Special Edition", "11 December 2015"],
    "Breakers of Shadow Sneak Peek Participation Card": ["Sneak Peek", "9 January 2016"],
    "Demo Deck 2016": ["Demo Deck", "14 January 2016"],
    "Breakers of Shadow": ["Core Booster", "15 January 2016"],
    "Weekly Shonen Jump January 2016 membership promotional card": ["Magazine promotion", "18 January 2016"],
    "Emperor of Darkness Structure Deck": ["Structure Deck", "29 January 2016"],
    "Yu-Gi-Oh! Day January 2016 promotional card": ["Yu-Gi-Oh! Day", "30 January 2016"],
    "WSJ Jump Pack Spring 2016 promotional card": ["Magazine promotion", "1 February 2016"],
    "Wing Raiders": ["Booster SP", "12 February 2016"],
    "Breakers of Shadow: Special Edition": ["Special Edition", "12 February 2016"],
    "Yu-Gi-Oh! Championship Series 2016 pre-registration card": ["Tournament promotion", "26 February 2016"],
    "Yu-Gi-Oh! ZEXAL Volume 8 promotional card": ["Manga promotion", "1 March 2016"],
    "Premium Gold: Infinite Gold": ["Gold Series", "17 March 2016"],
    "OTS Tournament Pack 1": ["OTS Tournament Pack", "18 March 2016"],
    "Yu-Gi-Oh! 5D's Volume 9 promotional card": ["Manga promotion", "5 April 2016"],
    "Millennium Pack": ["Booster Pack", "15 April 2016"],
    "Weekly Shonen Jump April 2016 membership promotional card": ["Magazine promotion", "20 April 2016"],
    "Shining Victories Sneak Peek Participation Card": ["Sneak Peek", "30 April 2016"],
    "Shining Victories": ["Core Booster", "6 May 2016"],
    "Starter Deck: Yuya": ["Starter Deck", "27 May 2016"],
    "Shining Victories: Special Edition": ["Special Edition", "17 June 2016"],
    "WSJ Jump Pack Fall 2016 promotional card": ["Magazine promotion", "1 July 2016"],
    "Weekly Shonen Jump July 2016 membership promotional card": ["Magazine promotion", "4 July 2016"],
    "Rise of the True Dragons Structure Deck": ["Structure Deck", "8 July 2016"],
    "OTS Tournament Pack 2": ["OTS Tournament Pack", "22 July 2016"],
    "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack": ["Booster Pack", "22 July 2016"],
    "Yu-Gi-Oh! Day July 2016 promotional card": ["Yu-Gi-Oh! Day", "23 July 2016"],
    "The Dark Illusion Sneak Peek Participation Card": ["Sneak Peek", "30 July 2016"],
    "The Dark Illusion": ["Core Booster", "5 August 2016"],
    "Dragons of Legend: Unleashed": ["Collectors Pack", "19 August 2016"],
    "Yu-Gi-Oh! World Championship 2016 prize cards": ["Tournament promotion", "21 August 2016"],
    "Yu-Gi-Oh! Championship Series 2016 Prize Card": ["Tournament promotion", "28 August 2016"],
    "2016 Mega-Tins": ["Tin", "1 September 2016"],
    "2016 Mega-Tin Mega Pack": ["Booster Pack", "1 September 2016"],
    "Yu-Gi-Oh! ZEXAL Volume 9 promotional card": ["Manga promotion", "1 September 2016"],
    "The Dark Illusion: Special Edition": ["Special Edition", "15 September 2016"],
    "Duelist Pack: Rivals of the Pharaoh": ["Duelist Pack", "15 September 2016"],
    "Weekly Shonen Jump October 2016 membership promotional card": ["Magazine promotion", "6 October 2016"],
    "Legendary Decks II": ["Collector's set", "6 October 2016"],
    "Structure Deck: Yugi Muto": ["Structure Deck", "20 October 2016"],
    "Structure Deck: Seto Kaiba": ["Structure Deck", "20 October 2016"],
    "Invasion: Vengeance Sneak Peek Participation Card": ["Sneak Peek", "29 October 2016"],
    "Invasion: Vengeance": ["Core Booster", "4 November 2016"],
    "Destiny Soldiers": ["Booster SP", "18 November 2016"],
    "OTS Tournament Pack 3": ["OTS Tournament Pack", "18 November 2016"],
    "Invasion: Vengeance: Special Edition": ["Special Edition", "9 December 2016"],
    "WSJ Jump Pack Spring 2017 promotional card": ["Magazine promotion", "January 2017"],
    "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack: Gold Edition": ["Special Edition", "13 January 2017"],
    "Weekly Shonen Jump January 2017 membership promotional card": ["Magazine promotion", "16 January 2016"],
    "Pendulum Domination Structure Deck": ["Structure Deck", "20 January 2017"],
    "Yu-Gi-Oh! Day January 2017 promotional card": ["Yu-Gi-Oh! Day", "28 January 2017"],
    "Raging Tempest Sneak Peek Participation Card": ["Sneak Peek", "4 February 2017"],
    "Raging Tempest": ["Core Booster", "10 February 2017"],
    "Fusion Enforcers": ["Booster SP", "23 February 2017"],
    "Star Pack Battle Royal": ["Star Pack", "10 March 2017"],
    "Raging Tempest: Special Edition": ["Special Edition", "17 March 2017"],
    "Duelist Saga": ["Collector's set", "31 March 2017"],
    "Yu-Gi-Oh! ARC-V Volume 1 promotional card": ["Manga promotion", "4 April 2017"],
    "OTS Tournament Pack 4": ["OTS Tournament Pack", "7 April 2017"],
    "Machine Reactor Structure Deck": ["Structure Deck", "14 April 2017"],
    "Dinosmasher's Fury Structure Deck": ["Structure Deck", "14 April 2017"],
    "Maximum Crisis Sneak Peek Participation Card": ["Sneak Peek", "29 April 2017"],
    "Weekly Shonen Jump April 2017 membership promotional card": ["Magazine promotion", "16 January 2016"],
    "Maximum Crisis": ["Core Booster", "5 May 2017"],
    "Duelist Pack: Dimensional Guardians": ["Duelist Pack", "26 May 2017"],
    "Yu-Gi-Oh! The Dark Side of Dimensions Blu-ray & DVD promotional card": ["Promotional card", "7 June 2017"],
    "Maximum Crisis: Special Edition": ["Special Edition", "9 June 2017"],
    "Pendulum Evolution": ["Booster Pack", "23 June 2017"],
    "Weekly Shonen Jump July 2017 membership promotional card": ["Magazine promotion", "30 June 2017"],
    "Battles of Legend: Light's Revenge": ["Collectors Pack", "7 July 2017"],
    "Starter Deck: Link Strike": ["Starter Deck", "21 July 2017"],
    "Yu-Gi-Oh! Day July 2017 promotional card": ["Promotional card", "22 July 2017"],
    "Code of the Duelist Sneak Peek Participation Card": ["Sneak Peek", "29 July 2017"],
    "WSJ Jump Pack Fall 2017 promotional card": ["Magazine promotion", "1 August 2017"],
    "Code of the Duelist": ["Core Booster", "4 August 2017"],
    "OTS Tournament Pack 5": ["OTS Tournament Pack", "5 August 2017"],
    "Yu-Gi-Oh! World Championship 2017 prize cards": ["Tournament promotion", "13 August 2017"],
    "2017 Mega-Tins": ["Tin", "25 August 2017"],
    "2017 Mega-Tin Mega Pack": ["Booster Pack", "25 August 2017"],
    "Yu-Gi-Oh! Championship Series 2017 prize card": ["Tournament promotion", "27 August 2017"],
    "Yu-Gi-Oh! ARC-V Volume 2 promotional card": ["Manga promotion", "5 September 2017"],
    "Legendary Duelists": ["Duelist Pack", "8 September 2017"],
    "Yugi's Collector Box": ["Collector Box", "15 September 2017"],
    "Code of the Duelist: Special Edition": ["Special Edition", "21 September 2017"],
    "Legendary Dragon Decks": ["Collector's set", "6 October 2017"],
    "Circuit Break Sneak Peek Participation Card": ["Sneak Peek", "14 October 2017"],
    "Circuit Break": ["Core Booster", "20 October 2017"],
    "Structure Deck: Cyberse Link": ["Structure Deck", "2 November 2017"],
    "Spirit Warriors": ["Deck Build Pack", "16 November 2017"],
    "Kaiba's Collector Box": ["Collector Box", "17 November 2017"],
    "Weekly Shonen Jump November 2017 membership promotional card": ["Magazine promotion", "December 2017"],
    "OTS Tournament Pack 6": ["OTS Tournament Pack", "7 December 2017"],
    "Circuit Break Special Edition": ["Special Edition", "8 December 2017"],
    "WSJ Jump Pack Spring 2018 promotional card": ["Magazine promotion", "1 January 2018"],
    "Structure Deck: Wave of Light": ["Structure Deck", "19 January 2018"],
    "Extreme Force Sneak Peek Participation Card": ["Sneak Peek", "27 January 2018"],
    "Weekly Shonen Jump January 2018 membership promotional card": ["Magazine promotion", "February 2018"],
    "Extreme Force": ["Core Booster", "2 February 2018"],
    "Legendary Duelists: Ancient Millennium": ["Duelist Pack", "23 February 2018"],
    "The Lost Art Promotion": ["Lost Art Promotion", "1 March 2018"],
    "Yu-Gi-Oh! ARC-V Volume 3 promotional card": ["Manga promotion", "6 March 2018"],
    "Legendary Collection Kaiba": ["Collector's set", "8 March 2018"],
    "Legendary Collection Kaiba Mega Pack": ["Booster Pack", "8 March 2018"],
    "Extreme Force Special Edition": ["Special Edition", "23 March 2018"],
    "Yugi & Kaiba Collector Box": ["Collector Box", "29 March 2018"],
    "Star Pack VRAINS": ["Star Pack", "30 March 2018"],
    "OTS Tournament Pack 7": ["OTS Tournament Pack", "13 April 2018"],
    "Structure Deck: Lair of Darkness": ["Structure Deck", "20 April 2018"],
    "Flames of Destruction Sneak Peek Participation Card": ["Sneak Peek", "28 April 2018"],
    "Weekly Shonen Jump May 2018 membership promotional card": ["Magazine promotion", "1 May 2018"],
    "Flames of Destruction": ["Core Booster", "4 May 2018"],
    "Dark Saviors": ["Deck Build Pack", "24 May 2018"],
    "Flames of Destruction Special Edition": ["Special Edition", "8 June 2018"],
    "Battles of Legend: Relentless Revenge": ["Special Edition", "29 June 2018"],
    "Starter Deck: Codebreaker": ["Starter Deck", "13 July 2018"],
    "Cybernetic Horizon Sneak Peek Participation Card": ["Sneak Peek", "21 July 2018"],
    "Cybernetic Horizon": ["Core Booster", "27 July 2018"],
    "Yu-Gi-Oh! World Championship 2018 prize cards": ["Tournament promotion", "5 August 2018"],
    "Structure Deck: Powercode Link": ["Structure Deck", "10 August 2018"],
    "Weekly Shonen Jump July 2018 membership promotional card": ["Magazine promotion", "12 August 2018"],
    "Shadows in Valhalla": ["Booster Pack", "16 August 2018"],
    "OTS Tournament Pack 8": ["OTS Tournament Pack", "17 August 2018"],
    "2018 Mega-Tins": ["Tin", "30 August 2018"],
    "2018 Mega-Tin Mega Pack": ["Booster Pack", "30 August 2018"],
    "WSJ Jump Pack Fall 2018 promotional card": ["Magazine promotion", "1 September 2018"],
    "Cybernetic Horizon Special Edition": ["Special Edition", "13 September 2018"],
    "Yu-Gi-Oh! Championship Series 2018 prize card": ["Tournament promotion", "23 September 2018"],
    "Legendary Duelists: White Dragon Abyss": ["Duelist Pack", "28 September 2018"],
    "Legendary Hero Decks": ["Collector's Set", "5 October 2018"],
    "Soul Fusion Sneak Peek Participation Card": ["Sneak Peek", "13 October 2018"],
    "Soul Fusion": ["Core Booster", "19 October 2018"],
    "Structure Deck: Zombie Horde": ["Structure Deck", "2 November 2018"],
    "Yu-Gi-Oh! Advent Calendar (2018)": ["Advent calendar", "2 November 2018"],
    "Yu-Gi-Oh! ARC-V Volume 4 promotional card": ["Manga promotion", "2 November 2018"],
    "Hidden Summoners": ["Deck Build Pack", "18 November 2018"],
    "Weekly Shonen Jump November 2018 membership promotional card": ["Magazine promotion", "21 November 2018"],
    "Soul Fusion Special Edition": ["Special Edition", "7 December 2018"],
    "OTS Tournament Pack 9": ["OTS Tournament Pack", "7 December 2018"],
    "WSJ Jump Pack Spring 2019 promotional card": ["Magazine promotion", "1 January 2019"],
    "The Lost Art Promotion 2019": ["Lost Art Promotion", "1 January 2019"],
    "Legendary Duelists: Sisters of the Rose": ["Duelist Pack", "11 January 2019"],
    "Speed Duel Starter Decks: Destiny Masters": ["Speed Duel Starter Deck", "24 January 2019"],
    "Speed Duel Starter Decks: Duelists of Tomorrow": ["Speed Duel Starter Deck", "24 January 2019"],
    "Savage Strike Sneak Peek Participation Card": ["Sneak Peek", "26 January 2019"],
    "Savage Strike": ["Core Booster", "1 February 2019"],
    "Structure Deck: Soulburner": ["Structure Deck", "15 February 2019"],
    "Yu-Gi-Oh! ARC-V Volume 5 promotional card": ["Manga promotion", "5 March 2019"],
    "Savage Strike Special Edition": ["Special Edition", "8 March 2019"],
    "The Infinity Chasers": ["Deck Build Pack", "22 March 2019"],
    "Speed Duel: Arena of Lost Souls": ["Speed Duel Booster Pack", "22 March 2019"],
    "Duel Power": ["Collector's set", "3 April 2019"],
    "Yu-Gi-Oh! Day April 2019 promotional card": ["Speed Duel promotional card", "6 April 2019"],
    "OTS Tournament Pack 10": ["OTS Tournament Pack", "18 April 2019"],
    "Speed Duel Tournament Pack 1": ["Speed Duel Tournament Pack", "18 April 2019"],
    "Structure Deck: Order of the Spellcasters": ["Structure Deck", "19 April 2019"],
    "Dark Neostorm Sneak Peek Participation Card": ["Sneak Peek", "27 April 2019"],
    "Dark Neostorm": ["Core Booster", "3 May 2019"],
    "Speed Duel: Attack from the Deep": ["Speed Duel Booster Pack", "31 May 2019"],
    "Speed Duel Demo Deck": ["Speed Duel demo deck", "8 June 2019"],
    "Dark Neostorm Special Edition": ["Special Edition", "14 June 2019"],
    "Weekly Shonen Jump June 2019 membership promotional cards": ["Magazine promotion", "18 June 2019"],
    "Battles of Legend: Hero's Revenge": ["Collectors Pack", "12 July 2019"],
    "Rising Rampage Sneak Peek Participation Card": ["Sneak Peek", "20 July 2019"],
    "Rising Rampage": ["Core Booster", "26 July 2019"],
    "Speed Duel Starter Decks: Ultimate Predators": ["Speed Duel Starter Deck", "2 August 2019"],
    "Speed Duel: Scars of Battle": ["Speed Duel Booster Pack", "2 August 2019"],
    "Event Pack Speed Duel": ["Speed Duel promotional card", "2 August 2019"],
    "Yu-Gi-Oh! World Championship 2019 prize cards": ["Tournament promotion", "11 August 2019"],
    "OTS Tournament Pack 11": ["OTS Tournament Pack", "15 August 2019"],
    "Structure Deck: Rokket Revolt": ["Structure Deck", "16 August 2019"],
    "Speed Duel: Scars of Battle Launch Event participation card": ["Speed Duel promotional card", "17 August 2019"],
    "Yu-Gi-Oh! Legacy of the Duelist: Link Evolution promotional cards": ["Video game promotion", "20 August 2019"],
    "Fists of the Gadgets": ["Booster Pack", "23 August 2019"],
    "Yu-Gi-Oh! Championship Series 2019 prize card": ["Tournament promotion", "25 August 2019"],
    "2019 Gold Sarcophagus Tin": ["Tin", "30 August 2019"],
    "2019 Gold Sarcophagus Tin Mega Pack": ["Booster Pack", "30 August 2019"],
    "Yu-Gi-Oh! ARC-V Volume 6 promotional card": ["Manga promotion", "3 September 2019"],
    "Rising Rampage Special Edition": ["Special Edition", "13 September 2019"],
    "Yu-Gi-Oh! Advent Calendar (2019)": ["Advent calendar", "26 September 2019"],
    "Legendary Duelists: Immortal Destiny": ["Duelist Pack", "26 September 2019"],
    "Speed Duel Tournament Pack 2": ["Speed Duel Tournament Pack", "10 October 2019"],
    "Duel Devastator": ["Collector's set", "11 October 2019"],
    "Chaos Impact Sneak Peek Participation Card": ["Sneak Peek", "19 October 2019"],
    "Chaos Impact": ["Core Booster", "25 October 2019"],
    "Mystic Fighters": ["Deck Build Pack", "22 November 2019"],
    "Speed Duel: Trials of the Kingdom Sneak Peek participation cards": ["Speed Duel Sneak Peek", "30 November 2019"],
    "Speed Duel: Trials of the Kingdom": ["Speed Duel Booster Pack", "5 December 2019"],
    "Chaos Impact Special Edition": ["Special Edition", "5 December 2019"],
    "OTS Tournament Pack 12": ["OTS Tournament Pack", "5 December 2019"],
    "The Lost Art Promotion 2020": ["Lost Art Promotion", "1 January 2020"],
    "Legendary Duelists: Magical Hero": ["Duelist Pack", "17 January 2020"],
    "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack Secret Edition": ["Special Edition", "24 January 2020"],
    "Ignition Assault Sneak Peek Participation Card": ["Sneak Peek", "25 January 2020"],
    "Ignition Assault": ["Core Booster", "30 January 2020"],
    "SJ Jump Pack Spring 2020 promotional card": ["Speed Duel magazine promotion", "1 February 2020"],
    "Structure Deck: Shaddoll Showdown": ["Structure Deck", "14 February 2020"],
    "Ignition Assault Special Edition": ["Special Edition", "5 March 2020"],
    "Duel Overload": ["Collector's set", "19 March 2020"],
    "Secret Slayers": ["Deck Build Pack", "16 April 2020"],
    "Structure Deck: Mechanized Madness": ["Structure Deck", "16 April 2020"],
    "OTS Tournament Pack 13": ["OTS Tournament Pack", "16 April 2020"],
    "Eternity Code": ["Core Booster", "1 May 2020"],
    "Speed Duel Starter Decks: Match of the Millennium": ["Speed Duel Starter Deck", "15 May 2020"],
    "Speed Duel Starter Decks: Twisted Nightmares": ["Speed Duel Starter Deck", "15 May 2020"],
    "Yu-Gi-Oh! ARC-V Volume 7 promotional card": ["Manga promotion", "2 June 2020"],
    "Toon Chaos": ["Booster Pack", "18 June 2020"],
    "Legendary Duelists: Season 1": ["Duelist Pack", "2 July 2020"],
    "Structure Deck: Sacred Beasts": ["Structure Deck", "9 July 2020"],
    "Battles of Legend: Armageddon": ["Collectors Pack", "23 July 2020"],
    "Rise of the Duelist Premiere! promotional card": ["Sneak Peek", "1 August 2020"],
    "Rise of the Duelist": ["Core Booster", "6 August 2020"],
    "2020 Tin of Lost Memories": ["Tin", "27 August 2020"],
    "KC Grand Tournament prize card": ["Tournament promotion", "27 August 2020"],
    "Dragons of Legend: The Complete Series": ["Collectors Pack", "11 September 2020"],
    "Legendary Duelists: Rage of Ra": ["Duelist Pack", "25 September 2020"],
    "OTS Tournament Pack 14": ["OTS Tournament Pack", "8 October 2020"],
    "Structure Deck: Spirit Charmers": ["Structure Deck", "23 October 2020"],
    "Phantom Rage Premiere! promotional card": ["Sneak Peek", "31 October 2020"],
    "Phantom Rage": ["Core Booster", "6 November 2020"],
    "Maximum Gold": ["Gold Series", "12 November 2020"],
    "Speed Duel: Battle City Box": ["Speed Duel collector's set", "20 November 2020"],
    "Genesis Impact": ["Deck Build Pack", "4 December 2020"],
    "The Lost Art Promotion 2021": ["Lost Art Promotion", "1 January 2021"],
    "Legendary Duelists: Season 2": ["Duelist Pack", "22 January 2021"],
    "Blazing Vortex": ["Core Booster", "4 February 2021"],
    "OTS Tournament Pack 15": ["OTS Tournament Pack", "17 February 2021"],
    "Structure Deck: Freezing Chains": ["Structure Deck", "18 February 2021"],
    "Ghosts From the Past": ["Collector's set", "15 April 2021"],
    "Ancient Guardians": ["Deck Build Pack", "6 May 2021"],
    "Yu-Gi-Oh! Remote Duel Extravaganza participation card": ["Tournament promotion", "22 May 2021"],
    "Lightning Overdrive": ["Core Booster", "3 June 2021"],
    "OTS Tournament Pack 16": ["OTS Tournament Pack", "10 June 2021"],
    "Egyptian God Deck: Slifer the Sky Dragon": ["Starter Deck", "17 June 2021"],
    "Egyptian God Deck: Obelisk the Tormentor": ["Starter Deck", "17 June 2021"],
    "King's Court": ["Booster Pack", "8 July 2021"],
    "Promotional card": ["August 2021", "Blue-Eyes White Dragon"],
    "Dawn of Majesty": ["Core Booster", "13 August 2021"],
    "KC Grand Tournament 2021 prize card": ["Tournament promotion", "28 August 2021"],
    "2021 Tin of Ancient Battles": ["Tin", "1 October 2021"],
    "OTS Tournament Pack 17": ["OTS Tournament Pack", "13 October 2021"],
    "Structure Deck: Cyber Strike": ["Structure Deck", "15 October 2021"],
    "Legendary Duelists: Synchro Storm": ["Duelist Pack", "29 October 2021"],
    "Burst of Destiny": ["Core Booster", "5 November 2021"],
    "Maximum Gold: El Dorado": ["Gold Series", "19 November 2021"],
    "Brothers of Legend": ["Collectors Pack", "3 December 2021"],
    "The Lost Art Promotion 2022": ["Lost Art Promotion", "1 January 2022"],
    "The Grand Creators": ["Deck Build Pack", "28 January 2022"],
    "Battle of Chaos": ["Core Booster", "11 February 2022"],
    "OTS Tournament Pack 18": ["OTS Tournament Pack", "17 February 2022"],
    "Hidden Arsenal: Chapter 1": ["Hidden Arsenal", "10 March 2022"],
    "Speed Duel GX: Duel Academy Box": ["Speed Duel collector's set", "18 March 2022"],
    "Speed Duel Tournament Pack 3": ["Speed Duel Tournament Pack", "24 March 2022"],
    "Trials of the Pharaoh - Speed Duel GX: Duel Academy Box promotional card": ["Speed Duel promotional card", "9 April 2022"],
    "Japan Championship 2022 Shop Qualifiers prize cards": ["Tournament promotion", "9 April 2022"],
    "Structure Deck: Albaz Strike": ["Structure Deck", "14 April 2022"],
    "Dimension Force": ["Core Booster", "5 May 2022"],
    "Ghosts From the Past: The 2nd Haunting": ["Collector's set", "19 May 2022"],
    "OTS Tournament Pack 19": ["OTS Tournament Pack", "15 June 2022"],
    "Legendary Duelists: Duels From the Deep": ["Duelist Pack", "17 June 2022"],
    "Legendary Duelists: Season 3": ["Duelist Pack", "21 July 2022"],
    "Power of the Elements": ["Core Booster", "5 August 2022"],
    "Tactical Masters": ["Deck Build Pack", "25 August 2022"],
    "KC Grand Tournament 2022 prize card": ["Tournament promotion", "27 August 2022"],
    "Yu-Gi-Oh! Championship Series 2022 prize card": ["Tournament promotion", "28 August 2022"],
    "2022 Tin of the Pharaoh's Gods": ["Tin", "16 September 2022"],
    "Speed Duel Tournament Pack 4": ["Speed Duel Tournament Pack", "28 September 2022"],
    "Structure Deck: Legend of the Crystal Beasts": ["Structure Deck", "29 September 2022"],
    "OTS Tournament Pack 20": ["OTS Tournament Pack", "5 October 2022"],
    "Speed Duel GX: Midterm Paradox": ["Speed Duel collector's set", "6 October 2022"],
    "Darkwing Blast": ["Core Booster", "21 October 2022"],
    "Magnificent Mavens": ["Booster Pack", "3 November 2022"],
    "Battles of Legend: Crystal Revenge": ["Collectors Pack", "17 November 2022"],
    "Structure Deck: Dark World": ["Structure Deck", "2 December 2022"],
    "The Lost Art Promotion 2023": ["Lost Art Promotion", "1 January 2023"],
    "Trials of the Pharaoh - Speed Duel GX: Midterm Paradox promotional card": ["Speed Duel promotional card", "16 January 2023"],
    "Amazing Defenders": ["Deck Build Pack", "20 January 2023"],
    "OTS Tournament Pack 21": ["OTS Tournament Pack", "8 February 2023"],
    "Photon Hypernova": ["Core Booster", "9 February 2023"],
    "Structure Deck: Beware of Traptrix": ["Structure Deck", "24 February 2023"],
    "Speed Duel Tournament Pack 5": ["Speed Duel Tournament Pack", "8 March 2023"],
    "Maze of Memories": ["Booster Pack", "9 March 2023"],
    "Speed Duel GX: Duelists of Shadows": ["Speed Duel collector's set", "30 March 2023"],
    "Legendary Collection: 25th Anniversary Edition": ["Collector's set", "20 April 2023"],
    "Cyberstorm Access": ["Core Booster", "5 May 2023"],
    "Wild Survivors": ["Deck Build Pack", "1 June 2023"],
    "Battles of Legend: Monstrous Revenge": ["Collectors Pack", "22 June 2023"],
    "OTS Tournament Pack 22": ["OTS Tournament Pack", "19 June 2023"],
    "Duelist Nexus": ["Core Booster", "27 July 2023"],
    "Yu-Gi-Oh! World Championship 2023 prize cards": ["Tournament promotion", "6 August 2023"],
    "Legendary Duelists: Soulburning Volcano": ["Duelist Pack", "10 August 2023"],
    "Speed Duel: Streets of Battle City": ["Speed Duel collector's set", "24 August 2023"],
    "The Pot Collection": ["Collector's set", "September 2023"],
    "Yu-Gi-Oh! Championship Series 2023 prize card": ["Tournament promotion", "3 September 2023"],
    "Promotional card": ["6 September 2023", "Dark Magician"],
    "Speed Duel Tournament Pack 6": ["Speed Duel Tournament Pack", "6 September 2023"],
    "25th Anniversary Tin: Dueling Heroes": ["Tin", "7 September 2023"],
    "25th Anniversary Tin: Dueling Heroes Mega Pack": ["Booster Pack", "7 September 2023"],
    "Structure Deck: The Crimson King": ["Structure Deck", "22 September 2023"],
    "Age of Overlord": ["Core Booster", "19 October 2023"],
    "OTS Tournament Pack 23": ["OTS Tournament Pack", "25 October 2023"],
    "25th Anniversary Rarity Collection": ["Booster Pack", "2 November 2023"],
    "Valiant Smashers": ["Deck Build Pack", "16 November 2023"],
    "Structure Deck: Fire Kings": ["Structure Deck", "7 December 2023"],
    "Maze of Millennia": ["Booster Pack", "18 January 2024"],
    "2-Player Starter Set": ["Starter Deck", "26 January 2024"],
    "25th Anniversary Ultimate Kaiba Set": ["Collector's set", "February 2024"],
    "Phantom Nightmare": ["Core Booster", "8 February 2024"],
    "OTS Tournament Pack 24": ["OTS Tournament Pack", "14 February 2024"],
    "Battles of Legend: Chapter 1": ["Collectors Pack", "22 February 2024"],
    "Promotional card": ["March 2024", "Obelisk the Tormentor (UR)"],
    "25th Anniversary Ultimate Kaiba Set": ["Collector's set", "1 March 2024"],
    "Japan Championship 2024 Shop Qualifiers prize card 1": ["Tournament promotion", "1 March 2024"],
    "Promotional card": ["22 March 2024", "Black Luster Soldier (UR)"],
    "Speed Duel GX: Midterm Destruction": ["Speed Duel collector's set", "29 March 2024"],
    "Speed Duel Tournament Pack 7": ["Speed Duel Tournament Pack", "3 April 2024"],
    "Legacy of Destruction": ["Booster Pack", "26 April 2024"],
    "Japan Championship 2024 Shop Qualifiers prize card 2": ["Tournament promotion", "1 May 2024"],
    "25th Anniversary Rarity Collection II": ["Booster pack", "23 May 2024"],
    "OTS Tournament Pack 25": ["OTS Tournament Pack", "12 June 2024"],
    "Battles of Legend: Terminal Revenge": ["Booster Pack", "20 June 2024"],
    "The Infinite Forbidden": ["Booster pack", "19 July 2024"],
    "Tin": ["19 September 2024", ""],
    "Rage of the Abyss": ["Booster pack", "10 October 2024"],
    "Name": ["Type", "Release date"],
    "Saikyō Jump May 2020 promotional card": ["Magazine promotion", "2 April 2020"],
    "Starter Deck Yuga - Cut Through! Sevens Road!!": ["Starter Deck", "4 April 2020"],
    "Starter Deck Luke - Explosive Supremacy! Dragias!!": ["Starter Deck", "4 April 2020"],
    "Starter Deck Set - Yuga vs. Luke": ["Starter Deck", "4 April 2020"],
    "Deck Mod Pack: Hyperspeed Rush Road!!": ["Deck Mod Pack", "11 April 2020"],
    "Start Rush Campaign": ["Promotional card", "11 April 2020"],
    "Weekly Shōnen Jump 2020, Issue 21–22 promotional card": ["Magazine promotion", "27 April 2020"],
    "Saikyō Jump July 2020 promotional card": ["Magazine promotion", "4 June 2020"],
    "Victory Pack Legendary Red-Eyes": ["Magazine promotion", "30 July 2020"],
    "Deck Mod Pack: Shocking Lightning Attack!!": ["Deck Mod Pack", "1 August 2020"],
    "Saikyō Jump September 2020 promotional card": ["Magazine promotion", "4 August 2020"],
    "Rush Road Guide promotional cards": ["Book promotion", "18 September 2020"],
    "Character Pack - Gavin/Roa/Romin": ["Booster Pack", "19 September 2020"],
    "Saikyō Jump November 2020 promotional card": ["Magazine promotion", "1 October 2020"],
    "Yu-Gi-Oh! SEVENS Complete Challenge 1": ["Promotional card", "23 October 2020"],
    "Yu-Gi-Oh! SEVENS Duel-1 Blu-ray & DVD promotional card": ["Promotional card", "28 October 2020"],
    "Deck Mod Pack: Illusion Strike Mirage Impact!!": ["Deck Mod Pack", "14 November 2020"],
    "Saikyō Jump January 2021 promotional card": ["Magazine promotion", "4 December 2020"],
    "Maximum Ultra Enhancement Pack": ["Booster Pack", "12 December 2020"],
    "Yu-Gi-Oh! SEVENS Duel-2 Blu-ray & DVD promotional card": ["Promotional card", "27 January 2021"],
    "Saikyō Jump March 2021 promotional card": ["Magazine promotion", "4 February 2021"],
    "Deck Mod Pack: Destined Power Destruction!!": ["Deck Mod Pack", "13 February 2021"],
    "Amabie-San Present Campaign": ["Promotional card", "20 February 2021"],
    "777 Treasure Campaign": ["Promotional set", "11 March 2021"],
    "Rush Duel Starter Deck Enhancement Pack": ["Enhancement Pack", "20 March 2021"],
    "Battle Pack Vol.1": ["Battle Pack", "22 March 2021"],
    "Secret Ace Pack": ["Booster Pack", "28 March 2021"],
    "Weekly Shōnen Jump 2021, Issue 17 promotional card": ["Magazine promotion", "29 March 2021"],
    "Saikyō Jump May 2021 promotional card": ["Magazine promotion", "1 April 2021"],
    "Deck Mod Pack: Dynamic Eternal Live!!": ["Deck Mod Pack", "24 April 2021"],
    "Yu-Gi-Oh! SEVENS Complete Challenge 2": ["Promotional card", "24 April 2021"],
    "Yu-Gi-Oh! SEVENS Luke! Explosive Supremacy Legend!! Volume 1 promotional card": ["Manga promotion", "30 April 2021"],
    "Yu-Gi-Oh! SEVENS Duel-3 Blu-ray & DVD promotional card": ["Promotional card", "24 May 2021"],
    "Yu-Gi-Oh! SEVENS x Akagi Nyugyo Collaboration Campaign": ["Promotional set", "30 May 2021"],
    "Maximum Ultra Evolution Pack": ["Booster Pack", "5 June 2021"],
    "Blue-Eyes White Dragon Rush Rare Special Red Version GET Campaign": ["Promotional card", "July 2021"],
    "Battle Pack Vol.2": ["Battle Pack", "1 July 2021"],
    "Secret Ace Pack Vol.2": ["Booster Pack", "1 July 2021"],
    "Yu-Gi-Oh! SEVENS x 7-Eleven Collaboration Campaign": ["Promotional set", "22 July 2021"],
    "Deck Mod Pack: Fierce Thunder Storm!!": ["Deck Mod Pack", "24 July 2021"],
    "Saikyō Battle Pack": ["Promotional set", "4 August 2021"],
    "Yu-Gi-Oh! RUSH DUEL: Saikyo Battle Royale!! promotional cards": ["Video game promotion", "12 August 2021"],
    "Yu-Gi-Oh! RUSH DUEL: Saikyo Battle Royale!! Winner's Spirit promotional card": ["Book promotion", "12 August 2021"],
    "Strongest Battle Deck Yuga - Hyper Machine Road": ["Strongest Battle Deck", "21 August 2021"],
    "Strongest Battle Deck Luke - Dragon's Dragons": ["Strongest Battle Deck", "21 August 2021"],
    "Strongest Battle Deck Gavin - Demon Commander Three Legions": ["Strongest Battle Deck", "21 August 2021"],
    "Strongest Battle Deck Romin - Psychic Beat": ["Strongest Battle Deck", "21 August 2021"],
    "Strongest Battle Deck Roa - Demon's Rock": ["Strongest Battle Deck", "21 August 2021"],
    "Strongest Battle Deck Nail - Maximum Haven": ["Strongest Battle Deck", "21 August 2021"],
    "Strongest Battle Deck Asana - Pride of the Heavy Cavalry Style": ["Strongest Battle Deck", "21 August 2021"],
    "Strongest Battle Deck +1 Bonus Card": ["Strongest Battle Deck", "21 August 2021"],
    "Jump Victory Carnival Treasure Box": ["Promotional card", "21 August 2021"],
    "Strongest Battle Deck Tournament prize card": ["Tournament promotion", "21 August 2021"],
    "Yu-Gi-Oh! SEVENS Duel-4 Blu-ray & DVD promotional card": ["Promotional card", "25 August 2021"],
    "Saikyō Jump October 2021 promotional card": ["Magazine promotion", "3 September 2021"],
    "Ultra 777 Treasure Campaign": ["Promotional set", "15 September 2021"],
    "Extra Transcend Enhancement Pack": ["Booster Pack", "19 September 2021"],
    "Battle Pack Vol.3": ["Battle Pack", "1 October 2021"],
    "Saikyō Jump November 2021 promotional card": ["Magazine promotion", "4 October 2021"],
    "Yu-Gi-Oh! SEVENS x Don Quijote Collaboration Campaign": ["Promotional card", "16 October 2021"],
    "Yu-Gi-Oh! SEVENS Complete Challenge 3": ["Promotional card", "20 October 2021"],
    "Deck Mod Pack: Chaotic Omega Rising!!": ["Deck Mod Pack", "30 October 2021"],
    "Saikyō Jump December 2021 promotional card": ["Magazine promotion", "4 November 2021"],
    "Yu-Gi-Oh! SEVENS Luke! Explosive Supremacy Legend!! Volume 2 promotional card": ["MaNGA promotion", "4 November 2021"],
    "Yu-Gi-Oh! SEVENS x Akagi Nyugyo Collaboration Campaign 2": ["Promotional set", "1 December 2021"],
    "Saikyō Jump January 2022 promotional card": ["Magazine promotion", "3 December 2021"],
    "Gold Rush Pack": ["Booster Pack", "11 December 2021"],
    "Yu-Gi-Oh! Rush Duel Duel Disk": ["Promotional set", "18 December 2021"],
    "Yu-Gi-Oh! SEVENS Duel-5 Blu-ray & DVD promotional card": ["Promotional card", "22 December 2021"],
    "Transcendent 7777 Treasure Campaign": ["Promotional card", "23 December 2021"],
    "Victory Pack Maximal Multistrike Dragon": ["Booster Pack", "28 December 2021"],
    "Battle Pack Vol.4": ["Battle Pack", "1 January 2022"],
    "Secret Ace Pack Vol.3": ["Booster Pack", "1 January 2022"],
    "Saikyō Jump February 2022 promotional card": ["Magazine promotion", "4 January 2022"],
    "Deck Mod Pack: Genesis Master Road!!": ["Deck Mod Pack", "29 January 2022"],
    "Gold Rush Challenge Pack": ["Booster Pack", "29 January 2022"],
    "Saikyō Jump March 2022 promotional card": ["Magazine promotion", "4 February 2022"],
    "Yu-Gi-Oh! SEVENS Complete Challenge 4": ["Promotional card", "26 February 2022"],
    "Saikyō Jump April 2022 promotional card": ["Magazine promotion", "4 March 2022"]
}

import json

f = open('YGOProDeck_Card_Info.json')
data = json.load(f)
card_info = {}
for card_info_data in data['data']:
    card_info[card_info_data['name']] = {}
    try:
        for card_set in card_info_data['card_sets']:
            card_info[card_info_data['name']][card_set['set_name']] = card_set
            try:
                card_info[card_info_data['name']][card_set['set_name']]['set_chronology'] = set_chronology[card_set['set_name']]
            except:
                pass
    except:
        print(card_info_data['name'])
json_object = json.dumps(card_info, indent=4)
with open("Set_Chronology.json", "w") as outfile:
    outfile.write(json_object)
f.close()