import json
from dateutil import parser
from datetime import *
import traceback
import logging

f = open('YGOProDeck_Card_Info.json')
f2 = open('Set_Chronology.json')
data = json.load(f)
data2 = json.load(f2)
card_info = {}
for card_info_data in data['data']:
    card_info[card_info_data['name']] = card_info_data
yugikaiba = date(2002, 3, 29)
critter = date(2002, 6, 26)
treasure = date(2002, 9, 16)
eds = date(2002, 10, 15)
imperial = date(2002, 10, 20)
android = date(2003, 3, 1)
warrior = date(2004, 12, 1)
reaper = date(2006, 2, 18)
gladiator = date(2008, 8, 1)

months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]

eds_cards = [
    "7 Colored Fish",
    "7 Completed",
    "Acid Crawler",
    "Acid Trap Hole",
    "Air Eater",
    "Archfiend Marmot of Nefariousness", # "Air Marmot of Nefariousness",
    "Akakieisu",
    "Akihiron",
    "Alligator's Sword",
    "Alligator's Sword Dragon",
    "Alpha The Magnet Warrior",
    "Amazon of the Seas",
    "Ameba",
    "Amphibious Bugroth",
    "Ancient Brain",
    "Ancient Elf",
    "Ancient Jar",
    "Ancient Lizard Warrior",
    "Ancient One of the Deep Forest",
    "Ancient Telescope",
    "Ancient Tool",
    "Ansatsu",
    "Anthrosaurus",
    "Anti Raigeki",
    "Anti-Spell Fragrance", # "Anti-Magic Fragrance",
    "Appropriate",
    "Aqua Chorus",
    "Aqua Dragon",
    "Aqua Madoor",
    "Arlownay",
    "Arma Knight",
    "Armaill",
    "Armed Ninja",
    "Armored Glass",
    "Armored Lizard",
    "Armored Rat",
    "Armored Starfish",
    "Armored Zombie",
    "Axe of Despair",
    "Axe Raider",
    "B. Dragon Jungle King",
    "Black Skull Dragon", # "B. Skull Dragon",
    "Baby Dragon",
    "Backup Soldier",
    "Banisher of the Light",
    "Barox",
    "Barrel Dragon",
    "Barrel Lily",
    "Barrel Rock",
    "Basic Insect",
    "Battle Ox",
    "Battle Steer",
    "Battle Warrior",
    "Bean Soldier",
    "Beast Fangs",
    "Beastking of the Swamps",
    "Beastly Mirror Ritual",
    "Beautiful Headhuntress",
    "Beaver Warrior",
    "Behegon",
    "Ring of Destruction", # "Bell of Destruction",
    "Beta The Magnet Warrior",
    "Bickuribox",
    "Big Eye",
    "Big Insect",
    "Big Shield Gardna",
    "Binding Chain",
    "Bio Plant",
    "Black Illusion Ritual",
    "Black Luster Ritual",
    "Black Luster Soldier",
    "Black Pendant",
    "Blackland Fire Dragon",
    "Bladefly",
    "Blast Juggler",
    "Blast Sphere",
    "Block Attack",
    "Blue Medicine",
    "Blue-Eyed Silver Zombie",
    "Blue-Eyes Toon Dragon",
    "Blue-Eyes Ultimate Dragon",
    "Blue-Eyes White Dragon",
    "Blue-Eyes White Dragon",
    "Blue-Winged Crown",
    "Boar Soldier",
    "Bolt Escargot",
    "Book of Secret Arts",
    "Bottom Dweller",
    "Bracchio-raidus",
    "Breath of Light",
    "Shine Palace", # "Bright Castle",
    "Burglar",
    "Burning Spear",
    "Buster Blader",
    "Call of Darkness", # "Call of the Dark",
    "Call of the Grave",
    "Call of the Haunted", # "Call Of The Haunted",
    "Candle of Fate",
    "Cannon Soldier",
    "Castle of Dark Illusions",
    "Castle Walls",
    "Catapult Turtle",
    "Ceasefire",
    "Celtic Guardian",
    "Celtic Guardian",
    "Ceremonial Bell",
    "Chain Destruction",
    "Chain Energy",
    "Chakra",
    "Change of Heart",
    "Charubin the Fire Knight",
    "Chorus of Sanctuary",
    "Claw Reacher",
    "Clown Zombie",
    "Cockroach Knight",
    "Cocoon of Evolution",
    "Commencement Dance",
    "Confiscation",
    "Cosmo Queen",
    "Crab Turtle",
    "Crass Clown",
    "Crawling Dragon",
    "Crawling Dragon #2",
    "Crazy Fish",
    "Crimson Sunbird",
    "Crow Goblin",
    "Crush Card Virus", # "Crush Card",
    "Curse of Dragon",
    "Curse of Fiend",
    "Curtain of the Dark Ones",
    "Cyber Commander",
    "Cyber Falcon",
    "Cyber Jar",
    "Cyber Saurus",
    "Cyber Shield",
    "Cyber Soldier",
    "Cyber-Stein",
    "Cyber-Tech Alligator",
    "D. Human",
    "Dancing Elf",
    "Dark Artist",
    "Dark Assailant",
    "Dark Chimera",
    "Dark Elf",
    "Dark Energy",
    "Dark Gray",
    "Dark Hole",
    "Dark King of the Abyss",
    "Black Magic Ritual", # "Dark Magic Ritual",
    "Dark Magician",
    "Dark Magician",
    "Dark Magician Girl",
    "Dark Rabbit",
    "Dark Sage",
    "Dark Shade",
    "Dark Witch",
    "Dark Zebra",
    "Dark-Eyes Illusionist",
    "Darkfire Dragon",
    "Darkfire Soldier #1",
    "Darkfire Soldier #2",
    "Darkness Approaches",
    "Dark-Piercing Light",
    "Darkworld Thorns",
    "Deepsea Shark",
    "Delinquent Duo",
    "De-Spell",
    "Destroyer Golem",
    "Dian Keto the Cure Master",
    "Dice Armadillo",
    "D.D. Warrior", # "Dimensional Warrior",
    "Disk Magician",
    "Dissolverock",
    "DNA Surgery",
    "Dokuroizo the Grim Reaper",
    "Dokurorider",
    "Doma The Angel of Silence",
    "Doron",
    "Dorover",
    "Dragon Capture Jar",
    "Dragon Piper",
    "Dragon Seeker",
    "Dragon Treasure",
    "Dragon Zombie",
    "Dragoness the Wicked Knight",
    "Dream Clown",
    "Driving Snow",
    "Drooling Lizard",
    "Doriado", # "Dryad",
    "Dunames Dark Witch",
    "Dungeon Worm",
    "Dust Tornado",
    "Earthshaker",
    "Eatgaboon",
    "Eldeen",
    "Electric Lizard",
    "Electric Snake",
    "Electro-Whip",
    "Elegant Egotist",
    "Elf's Light",
    "Empress Judge",
    "Enchanted Javelin",
    "Enchanting Mermaid",
    "Eradicating Aerosol",
    "Eternal Drought", # "Eternal Draught",
    "Eternal Rest",
    "Exchange",
    "Exile of the Wicked",
    "Exodia the Forbidden One",
    "Eyearmor",
    "Fairy Dragon",
    "Fairy's Hand Mirror",
    "Fairywitch",
    "Faith Bird",
    "Fake Trap",
    "Feral Imp",
    "Fiend Kraken",
    "Fiend Reflection #1",
    "Fiend Reflection #2",
    "Fiend Sword",
    "Fiend's Hand",
    "Fiend's Mirror",
    "Final Destiny",
    "Final Flame",
    "Fire Kraken",
    "Fire Reaper",
    "Firegrass",
    "Firewing Pegasus",
    "Fireyarou",
    "Fissure",
    "Flame Cerebrus",
    "Flame Champion",
    "Flame Ghost",
    "Flame Manipulator",
    "Flame Swordsman",
    "Flame Swordsman",
    "Flame Viper",
    "Flash Assailant",
    "Flower Wolf",
    "Flying Kamakiri #1",
    "Flying Kamakiri #2",
    "Follow Wind",
    "Forced Requisition",
    "Forest",
    "Fortress Whale",
    "Fortress Whale's Oath",
    "Frenzied Panda",
    "Fusion Sage",
    "Fusionist",
    "Gaia Power",
    "Gaia the Dragon Champion",
    "Gaia The Fierce Knight",
    "Gaia The Fierce Knight",
    "Gale Dogra",
    "Gamma the Magnet Warrior", # "Gamma The Magnet Warrior",
    "Ganigumo",
    "Garma Sword",
    "Garma Sword Oath",
    "Garnecia Elefantis",
    "Garoozis",
    "Garvas",
    "Gate Guardian",
    "Gatekeeper",
    "Gazelle the King of Mythical Beasts",
    "Gemini Elf",
    "Genin",
    "Germ Infection",
    "Ghoul with an Appetite",
    "Giant Flea",
    "Giant Germ",
    "Giant Mech-Soldier",
    "Giant Rat",
    "Giant Red Seasnake",
    "Giant Scorpion of the Tundra",
    "Giant Soldier of Stone",
    "Giant Trunade",
    "Giant Turtle Who Feeds on Flames",
    "Gift of The Mystical Elf",
    "Giganto",
    "Giga-Tech Wolf", # "Giga-tech Wolf",
    "Giltia the D. Knight",
    "Goblin Fan",
    "Goblin's Secret Remedy",
    "Goddess of Whim",
    "Goddess with the Third Eye",
    "Gokibore",
    "Graceful Charity",
    "Graceful Dice",
    "Grappler",
    "Gravedigger Ghoul",
    "Gravekeeper's Servant",
    "Graverobber",
    "Graveyard and the Hand of Invitation",
    "Great Bill",
    "Great Mammoth of Goldfine",
    "Great Moth",
    "Great White",
    "Green Phantom King",
    "Greenkappa",
    "Griffore",
    "Griggle",
    "Ground Attacker Bugroth",
    "Gruesome Goo",
    "Gryphon Wing",
    "Guardian of the Labyrinth",
    "Sentinel of the Seas", # "Guardian of the Sea",
    "Guardian of the Throne Room",
    "Gust",
    "Gust Fan",
    "Gyakutenno Megami",
    "Hamburger Recipe",
    "Hane-Hane",
    "Haniwa",
    "Happy Lover",
    "Hard Armor",
    "Harpie Lady",
    "Harpie Lady Sisters",
    "Sky Scout", # "Harpie's Brother",
    "Harpie's Feather Duster",
    "Harpie's Pet Dragon",
    "Heavy Storm",
    "Hercules Beetle",
    "Hero of the East",
    "Hibikime",
    "High Tide Gyojin",
    "Hinotama",
    "Hinotama Soul",
    "Hiro's Shadow Scout",
    "Hitodenchak",
    "Hitotsu-Me Giant",
    "Holograh",
    "Horn Imp",
    "Horn of Heaven",
    "Horn of Light",
    "Horn of the Unicorn",
    "Hoshiningen",
    "Hourglass of Courage",
    "Hourglass of Life",
    "House of Adhesive Tape",
    "Hungry Burger",
    "Hunter Spider",
    "Hyo",
    "Hyosube",
    "Hyozanryu",
    "Ice Water",
    "Ill Witch",
    "Illusionist Faceless Mage",
    "Imperial Order",
    "Insect Armor with Laser Cannon",
    "Insect Queen",
    "Insect Soldiers of the Sky",
    "Inspection",
    "Invader from Another Dimension",
    "Invader of the Throne",
    "Invigoration",
    "Javelin Beetle",
    "Javelin Beetle Pact",
    "Jellyfish",
    "Jigen Bakudan",
    "Jinzo",
    "Jinzo #7",
    "Jirai Gumo",
    "Judge Man",
    "Just Desserts",
    "Kagemusha of the Blue Flame",
    "Kageningen",
    "Kairyu-Shin",
    "Kaiser Dragon",
    "Kamakiriman",
    "Kaminari Attack",
    "Thunder Kid", # "Kaminarikozou",
    "Kamionwizard",
    "Kanan the Swordmistress",
    "Kanikabuto",
    "Karate Man",
    "Karbonala Warrior",
    "Kattapillar",
    "Kazejin",
    "Key Mace #2",
    "Killer Needle",
    "King Fog",
    "King of Yamimakai",
    "Kiseitai",
    "Kojikocy",
    "Kotodama",
    "Koumori Dragon",
    "Krokodilus",
    "Kumootoko",
    "Kunai with Chain",
    "Kurama",
    "Kuriboh",
    "Kuwagata α", # "Kuwagata a",
    "Kwagar Hercules",
    "La Jinn the Mystical Genie of the Lamp",
    "Labyrinth Tank",
    "Labyrinth Wall",
    "Lady of Faith",
    "LaLa Li-oon",
    "Larvae Moth",
    "Larvas",
    "Laser Cannon Armor",
    "Last Day of Witch",
    "Last Will",
    "Laughing Flower",
    "Launcher Spider",
    "Launcher Spider",
    "Lava Battleguard",
    "Left Arm of the Forbidden One",
    "Left Leg of the Forbidden One",
    "Legendary Sword",
    "Leghul",
    "Leogun",
    "Lesser Dragon",
    "Light of Intervention",
    "Lightforce Sword",
    "Liquid Beast",
    "Little Chimera",
    "Little D",
    "Lord of D.",
    "Lord of the Lamp",
    "Lord of Zemia",
    "Luminous Spark",
    "Lunar Queen Elzaim",
    "Mabarrel",
    "Machine Conversion Factory",
    "Machine King",
    "Magic Jammer",
    "Magical Thorn", # "Magic Thorn",
    "Magical Ghost",
    "Magical Hats",
    "Magical Labyrinth",
    "Magical Arm Shield", # "Magic-Arm Shield",
    "Magician of Black Chaos",
    "Magician of Faith",
    "Maha Vailo",
    "Maiden of the Moonlight",
    "Major Riot",
    "Malevolent Nuzzler",
    "Mammoth Graveyard",
    "Man Eater",
    "Man-Eater Bug",
    "Man-Eating Black Shark", # "Man-eating Black Shark",
    "Man-Eating Plant",
    "Man-Eating Treasure Chest",
    "Manga Ryu-Ran",
    "Marine Beast",
    "Masaki the Legendary Swordsman",
    "Mask of Darkness",
    "Masked Sorcerer",
    "Master & Expert",
    "Mavelus",
    "Mechanical Snail",
    "Karakuri Spider", # "Mechanical Spider",
    "Mechanicalchaser",
    "Meda Bat",
    "Mega Thunderball",
    "Megamorph",
    "Megazowler",
    "Meotoko",
    "Mesmeric Control",
    "Messenger of Peace",
    "Metal Detector",
    "Metal Dragon",
    "Metal Fish",
    "Metal Guardian",
    "Metalmorph",
    "Metalzoa",
    "Meteor Black Dragon", # "Meteor B. Dragon",
    "Meteor Dragon",
    "Mikazukinoyaiba",
    "Millennium Golem",
    "Millennium Shield",
    "Milus Radiant",
    "Minar",
    "Minomushi Warrior",
    "Mirror Force",
    "Mirror Wall",
    "Misairuzame",
    "Molten Destruction",
    "Monster Egg",
    "Monster Eye",
    "Monster Reborn",
    "Monster Tamer",
    "Monstrous Bird",
    "Moon Envoy",
    "Mooyan Curry",
    "Morinphen",
    "Morphing Jar",
    "Morphing Jar #2",
    "Mother Grizzly",
    "Mountain",
    "Mountain Warrior",
    "Mr. Volcano",
    "Muka Muka",
    "Mushroom Man",
    "Mushroom Man #2",
    "Musician King",
    "M-Warrior #1",
    "M-Warrior #2",
    "Mysterious Puppeteer",
    "Mystic Horseman",
    "Mystic Lamp",
    "Mystic Plasma Zone",
    "Mystic Probe",
    "Mystic Tomato",
    "Mystical Capture Chain",
    "Mystical Elf",
    "Mystical Moon",
    "Mystical Sand",
    "Mystical Sheep #1",
    "Mystical Sheep #2",
    "Mystical Space Typhoon",
    "Needle Ball",
    "Needle Worm",
    "Negate Attack",
    "Nekogal #1",
    "Nekogal #2",
    "Nemuriko",
    "Neo the Magic Swordsman",
    "Nimble Momonga",
    "Niwatori",
    "Nobleman of Crossout",
    "Nobleman of Extermination",
    "Novox's Prayer",
    "Numinous Healer",
    "Octoberser",
    "Ocubeam",
    "Ogre of the Black Shadow",
    "One-Eyed Shield Dragon",
    "Ooguchi",
    "Ookazi",
    "Orion the Battle King",
    "Oscillo Hero",
    "Wattkid", # "Oscillo Hero #2",
    "Painful Choice",
    "Pale Beast",
    "Panther Warrior",
    "Paralyzing Potion",
    "Parasite Paracide",
    "Parrot Dragon",
    "Patrol Robo",
    "Peacock",
    "Pendulum Machine",
    "Pendulum Machine",
    "Penguin Knight",
    "Penguin Soldier",
    "Perfectly Ultimate Great Moth",
    "Performance of Sword",
    "Petit Angel",
    "Petit Dragon",
    "Petit Moth",
    "Polymerization",
    "Polymerization",
    "Pot of Greed",
    "Power of Kaishin",
    "Pragtical",
    "Premature Burial",
    "Prevent Rat",
    "Princess of Tsurugi",
    "Prisman",
    "Prohibition",
    "Protector of the Throne",
    "Psychic Kappa",
    "Pumpking the King of Ghosts",
    "Punished Eagle",
    "Queen Bird",
    "Queen of Autumn Leaves",
    "Queen's Double",
    "Rabid Horseman",
    "Raigeki",
    "Raimei",
    "Rainbow Flower",
    "Raise Body Heat",
    "Rare Fish",
    "Ray & Temperature",
    "Reaper of the Cards",
    "Red Archery Girl",
    "Red Medicine",
    "Red-Eyes Black Dragon", # "Red-Eyes B. Dragon",
    "Red-Eyes Black Metal Dragon",
    "Reinforcements",
    "Relinquished",
    "Remove Trap",
    "Respect Play",
    "Restructer Revolution",
    "Resurrection of Chakra",
    "Reverse Trap",
    "Revival of Dokurorider",
    "Rhaimundos of the Red Sword",
    "Right Arm of the Forbidden One",
    "Right Leg of the Forbidden One",
    "Ring of Magnetism",
    "Riryoku",
    "Rising Air Current",
    "Roaring Ocean Snake",
    "Robbin' Goblin",
    "Rock Ogre Grotto #1",
    "Rogue Doll",
    "Root Water",
    "Rose Spectre of Dunn",
    "Royal Decree",
    "Royal Guard",
    "Rude Kaiser",
    "Rush Recklessly",
    "Ryu-Kishin",
    "Ryu-Kishin Powered",
    "Ryu-Ran",
    "Sword Slasher", # "Saber Slasher",
    "Saggi the Dark Clown",
    "Salamandra",
    "Sand Stone",
    "Sanga of the Thunder",
    "Sangan",
    "Sea Kamen",
    "Sea King Dragon",
    "Seal of the Ancients",
    "Sebek's Blessing",
    "Sectarian of Secrets",
    "Seiyaryu",
    "Sengenjin",
    "Senju of the Thousand Hands",
    "Serpent Night Dragon",
    "Seven Tools of the Bandit",
    "Shadow Ghoul",
    "Shadow Specter",
    "Share the Pain",
    "Shield & Sword",
    "Shining Angel", # "Shining Fairy",
    "Shovel Crusher",
    "Silver Bow and Arrow",
    "Silver Fang",
    "Sinister Serpent",
    "Skelengel",
    "Skelgon",
    "Skull Dice",
    "Skull Guardian",
    "Skull Knight",
    "Skull Red Bird",
    "Skull Servant",
    "Skull Stalker",
    "Skullbird",
    "Sleeping Lion",
    "Slot Machine",
    "Snake Fang",
    "Snakeyashi",
    "Snatch Steal",
    "Sogen",
    "Solemn Judgment",
    "Solitude",
    "Solomon's Lawbook",
    "Sonic Bird",
    "Sonic Maid",
    "Soul Hunter",
    "Soul of the Pure",
    "Soul Release",
    "Sparks",
    "Spear Cretin",
    "Spellbinding Circle",
    "Spike Seadra",
    "Spirit of the Books",
    "Spirit of the Harp",
    "Acid Rain", # "Stain Storm",
    "Star Boy",
    "Steel Ogre Grotto #1",
    "Steel Ogre Grotto #2",
    "Steel Scorpion",
    "Steel Shell",
    "Stim-Pack",
    "Stone Armadiller",
    "Stone Ogre Grotto",
    "Stop Defense",
    "Stuffed Animal",
    "Succubus Knight",
    "Suijin",
    "Summoned Skull",
    "Super War-Lion",
    "Supporter in the Shadows",
    "Swamp Battleguard",
    "Sword Arm of Dragon",
    "Sword of Dark Destruction",
    "Sword of Deep-Seated",
    "Sword of Dragon's Soul",
    "Swords of Revealing Light",
    "Swordsman from a Distant Land", # "Swordsman from a Foreign Land",
    "Swordstalker",
    "Tailor of the Fickle",
    "Tainted Wisdom",
    "Takriminos",
    "Takuhee",
    "Tao the Chanter",
    "Temple of Skulls",
    "Tenderness",
    "Terra the Terrible",
    "The 13th Grave",
    "The Bewitching Phantom Thief",
    "The Bistro Butcher",
    "The Cheerful Coffin",
    "The Drdek",
    "The Eye of Truth",
    "The Flute of Summoning Dragon",
    "The Forceful Sentry",
    "The Furious Sea King",
    "The Immortal of Thunder",
    "The Inexperienced Spy",
    "The Little Swordsman of Aile",
    "The Regulation of Tribe",
    "The Reliable Guardian",
    "The Shallow Grave",
    "The Snake Hair",
    "The Stern Mystic",
    "The Thing That Hides in the Mud",
    "The Unhappy Maiden",
    "The Wandering Doomed",
    "The Wicked Worm Beast",
    "Thousand Dragon",
    "Thousand Dragon",
    "Three-Headed Geedo",
    "Three-Legged Zombies",
    "Thunder Dragon",
    "Tiger Axe",
    "Tiger Axe",
    "Time Machine",
    "Time Seal",
    "Time Wizard",
    "Toad Master",
    "Togex",
    "Toll",
    "Tomozaurus",
    "Tongyo",
    "Toon Alligator",
    "Toon Mermaid",
    "Toon Summoned Skull",
    "Toon World",
    "Torike",
    "Total Defense Shogun",
    "Trakodon", # "Trakadon",
    "Trap Hole",
    "Trap Master",
    "Tremendous Fire",
    "Trent",
    "Trial of Nightmare",
    "Tribute to the Doomed", # "Tribute to The Doomed",
    "Tri-Horned Dragon",
    "Tripwire Beast",
    "Turtle Oath",
    "Turtle Tiger",
    "Twin Long Rods #2",
    "Twin-Headed Fire Dragon",
    "Twin-Headed Thunder Dragon",
    "Two-Headed King Rex",
    "Two-Mouth Darkruler",
    "Two-Pronged Attack",
    "Tyhone",
    "Tyhone #2",
    "UFO Turtle",
    "Ultimate Offering",
    "Umi",
    "Umiiruka",
    "Unknown Warrior of Fiend",
    "Upstart Goblin",
    "Uraby",
    "Ushi Oni",
    "Valkyrion the Magna Warrior",
    "Vermillion Sparrow",
    "Versago the Destroyer",
    "Vile Germs",
    "Violent Rain",
    "Violet Crystal",
    "Vishwar Randi",
    "Vorse Raider",
    "Waboku",
    "Wall of Illusion",
    "Wall Shadow",
    "War-Lion Ritual",
    "Warrior Elimination",
    "Warrior of Tradition",
    "Wasteland",
    "Water Element",
    "Water Girl",
    "Water Magician",
    "Water Omotics",
    "Waterdragon Fairy",
    "Weather Control",
    "Weather Report",
    "Whiptail Crow",
    "White Hole",
    "White Magical Hat",
    "Archfiend Mirror", # "Wicked Mirror",
    "Widespread Ruin",
    "Windstorm of Etaqua",
    "Wing Egg Elf",
    "Winged Cleaver",
    "Winged Dragon, Guardian of the Fortress #1", # "Winged Dragon,Guardian of the Fortress #1",
    "Wings of Wicked Flame",
    "Witch of the Black Forest",
    "Witch's Apprentice",
    "Witty Phantom",
    "Wodan the Resident of the Forest",
    "Wood Remains",
    "World Suppression",
    "Wow Warrior",
    "Wretched Ghost of the Attic",
    "Yado Karu",
    "Yaiba Robo",
    "Yamatano Dragon Scroll",
    "Yami",
    "Yaranzo",
    "Zanki",
    "Zera Ritual",
    "Zera the Mant", # "Zera The Mant",
    "Zoa",
    "Zombie Warrior",
    "Zone Eater",
    # "The Monarchy",
    # "Set Sail for the Kingdom",
    # "Glory of the King's Hand",
    "Obelisk the Tormentor",
    "Slifer the Sky Dragon",
    "The Winged Dragon of Ra",
    "Insect Monster Token"
]

um06_cards = [
    "30,000-Year White Turtle",
    "Akihiron",
    "Ally Mind",
    "Ancient Tool",
    "Ansatsu",
    "Battle Steer",
    "Beautiful Beast Trainer",
    "Bolt Escargot",
    "Crawling Dragon",
    "Crow Goblin",
    "Cyber Soldier",
    "Dark Chimera",
    "Dark Witch",
    "Dice Armadillo",
    "Doma The Angel of Silence",
    "Dungeon Worm",
    "Emperor of the Land and Sea",
    "Flame Champion",
    "Garoozis",
    "Gatekeeper",
    "Giant Turtle Who Feeds on Flames",
    "Giganto",
    "Hercules Beetle",
    "Hunter Spider",
    "Ill Witch",
    "Kairyu-Shin",
    "Kuwagata α",
    "LaMoon",
    "Leo Wizard",
    "Leogun",
    "Mabarrel",
    "Machine Attacker",
    "Mech Bass",
    "Megasonic Eye",
    "Metal Fish",
    "Metal Guardian",
    "Misairuzame",
    "Monster Tamer",
    "Morinphen",
    "Octoberser",
    "Orion the Battle King",
    "Parrot Dragon",
    "Peacock",
    "Queen Bird",
    "Queen of Autumn Leaves",
    "Rainbow Marine Mermaid",
    "Rock Spirit",
    "Rude Kaiser",
    "Sand Stone",
    "Seiyaryu",
    "Shapesnatch",
    "Spike Seadra",
    "Spikebot",
    "Spirit of the Mountain",
    "Spirit of the Winds",
    "Stone Ogre Grotto",
    "Succubus Knight",
    "Sword Slasher",
    "Tatsunootoshigo",
    "Togex",
    "Trent",
    "Wing Eagle",
    "Winged Egg of New Life",
    "Yamadron",
    "Zanki",
    "8-Claws Scorpion",
    "Dragon Piper",
    "Grave Protector",
    "Gravekeeper's Chief",
    "Great Phantom Thief",
    "Legacy Hunter",
    "Malice Doll of Demise",
    "Skull Knight #2",
    "Ante",
    "Archfiend's Oath",
    "Beast Fangs",
    "Book of Secret Arts",
    "Burning Spear",
    "D.D. Designator",
    "Dark Designator",
    "Dark Energy",
    "Darkness Approaches",
    "Double Spell",
    "Dragon Treasure",
    "Electro-Whip",
    "Elf's Light",
    "Follow Wind",
    "Gust Fan",
    "Invigoration",
    "Kaiser Colosseum",
    "Laser Cannon Armor",
    "Legendary Sword",
    "Machine Conversion Factory",
    "My Body as a Shield",
    "Mystical Moon",
    "Power of Kaishin",
    "Prohibition",
    "Question",
    "Raise Body Heat",
    "Secret Pass to the Treasures",
    "Silver Bow and Arrow",
    "Spirit Elimination",
    "Spring of Rebirth",
    "Steel Shell",
    "Sword of Dark Destruction",
    "The Puppet Magic of Dark Ruler",
    "Vile Germs",
    "Violet Crystal",
    "Barrel Behind the Door",
    "Grave Lure",
    "Mind Crush",
    "Null and Void",
    "Penalty Game!",
    "Pharaoh's Treasure",
    "Pole Position",
    "Trap of Board Eraser",
    "Kwagar Hercules"
]

imperial_cards = [
    "4-Starred Ladybug of Doom",
    "7 Colored Fish",
    "7 Completed",
    "Acid Trap Hole",
    "Ameba",
    "Ancient Brain",
    "Ancient Elf",
    "Ancient Lizard Warrior",
    "Ancient One of the Deep Forest",
    "Ancient Telescope",
    "Ansatsu",
    "Appropriate",
    "Aqua Madoor",
    "Armaill",
    "Armed Ninja",
    "Armored Glass",
    "Armored Lizard",
    "Armored Starfish",
    "Armored Zombie",
    "Attack and Receive",
    "Axe of Despair",
    "Axe Raider",
    "Baby Dragon",
    "Backup Soldier",
    "Banisher of the Light",
    "Baron of the Fiend Sword",
    "Barrel Dragon",
    "Basic Insect",
    "Battle Ox",
    "Battle Steer",
    "Bean Soldier",
    "Beast Fangs",
    "Beast of Talwar",
    "Beastking of the Swamps",
    "Beautiful Headhuntress",
    "Beaver Warrior",
    "Bickuribox",
    "Big Eye",
    "Bite Shoes",
    "Black Illusion Ritual",
    "Black Pendant",
    "Black Skull Dragon",
    "Blackland Fire Dragon",
    "Bladefly",
    "Blast Juggler",
    "Block Attack",
    "Blue Medicine",
    "Blue-Eyes Toon Dragon",
    "Blue-Eyes White Dragon",
    "Blue-Winged Crown",
    "Boar Soldier",
    "Bombardment Beetle",
    "Book of Secret Arts",
    "Bottom Dweller",
    "Bubonic Vermin",
    "Burning Land",
    "Burning Spear",
    "Buster Blader",
    "Call of the Grave",
    "Call of the Haunted",
    "Cannon Soldier",
    "Card Destruction",
    "Castle of Dark Illusions",
    "Castle Walls",
    "Catapult Turtle",
    "Ceasefire",
    "Celtic Guardian",
    "Ceremonial Bell",
    "Chain Destruction",
    "Chain Energy",
    "Change of Heart",
    "Charubin the Fire Knight",
    "Chorus of Sanctuary",
    "Claw Reacher",
    "Cockroach Knight",
    "Cocoon of Evolution",
    "Cold Wave",
    "Commencement Dance",
    "Confiscation",
    "Corroding Shark",
    "Crab Turtle",
    "Crass Clown",
    "Crawling Dragon",
    "Crawling Dragon #2",
    "Curse of Dragon",
    "Curse of Fiend",
    "Cyber Falcon",
    "Cyber Jar",
    "Cyber Saurus",
    "Cyber Soldier of Darkworld",
    "D. Human",
    "Dancing Elf",
    "Dark Assailant",
    "Dark Bat",
    "Dark Elf",
    "Dark Energy",
    "Dark Gray",
    "Dark Hole",
    "Dark King of the Abyss",
    "Dark Magician",
    "Dark Titan of Terror",
    "Dark Witch",
    "Dark Zebra",
    "Darkfire Dragon",
    "Darkfire Soldier #1",
    "Darkfire Soldier #2",
    "Darkness Approaches",
    "Darkworld Thorns",
    "De-Spell",
    "Deepsea Shark",
    "Deepsea Warrior",
    "Delinquent Duo",
    "Destroyer Golem",
    "Dharma Cannon",
    "Dian Keto the Cure Master",
    "Dimensionhole",
    "Disk Magician",
    "Dissolverock",
    "DNA Surgery",
    "Dokurorider",
    "Dokuroyaiba",
    "Doma The Angel of Silence",
    "Dragon Capture Jar",
    "Dragon Piper",
    "Dragon Seeker",
    "Dragon Treasure",
    "Dragon Zombie",
    "Dragoness the Wicked Knight",
    "Dream Clown",
    "Drill Bug",
    "Driving Snow",
    "Drooling Lizard",
    "Dust Tornado",
    "Earthshaker",
    "Eatgaboon",
    "Electric Lizard",
    "Electric Snake",
    "Electro-Whip",
    "Elegant Egotist",
    "Elf's Light",
    "Empress Judge",
    "Enchanted Javelin",
    "Enchanting Mermaid",
    "Eternal Rest",
    "Exchange",
    "Exile of the Wicked",
    "Exodia the Forbidden One",
    "Fairy Meteor Crush",
    "Fairy's Hand Mirror",
    "Faith Bird",
    "Fake Trap",
    "Feral Imp",
    "Fiend Reflection #2",
    "Final Destiny",
    "Final Flame",
    "Fire Kraken",
    "Firegrass",
    "Fireyarou",
    "Fissure",
    "Flame Cerebrus",
    "Flame Champion",
    "Flame Ghost",
    "Flame Manipulator",
    "Flame Swordsman",
    "Flash Assailant",
    "Flower Wolf",
    "Flying Kamakiri #1",
    "Flying Kamakiri #2",
    "Follow Wind",
    "Forced Requisition",
    "Forest",
    "Frenzied Panda",
    "Fusionist",
    "Gaia Power",
    "Gaia the Dragon Champion",
    "Gaia The Fierce Knight",
    "Gamble",
    "Garnecia Elefantis",
    "Garoozis",
    "Gate Guardian",
    "Gazelle the King of Mythical Beasts",
    "Gearfried the Iron Knight",
    "Germ Infection",
    "Giant Flea",
    "Giant Germ",
    "Giant Rat",
    "Giant Red Seasnake",
    "Giant Soldier of Stone",
    "Giant Trunade",
    "Giant Turtle Who Feeds on Flames",
    "Gift of The Mystical Elf",
    "Giga-Tech Wolf",
    "Giltia the D. Knight",
    "Girochin Kuwagata",
    "Goblin Attack Force",
    "Goblin's Secret Remedy",
    "Goddess with the Third Eye",
    "Graceful Dice",
    "Gradius",
    "Gravedigger Ghoul",
    "Gravekeeper's Servant",
    "Graverobber",
    "Gravity Bind",
    "Great Moth",
    "Great White",
    "Green Phantom King",
    "Griggle",
    "Ground Attacker Bugroth",
    "Ground Collapse",
    "Guardian of the Labyrinth",
    "Guardian of the Throne Room",
    "Gust",
    "Gust Fan",
    "Gyakutenno Megami",
    "Hamburger Recipe",
    "Hane-Hane",
    "Hard Armor",
    "Harpie Lady",
    "Harpie Lady Sisters",
    "Hayabusa Knight",
    "Heavy Storm",
    "Hercules Beetle",
    "Hibikime",
    "High Tide Gyojin",
    "Hinotama",
    "Hinotama Soul",
    "Hiro's Shadow Scout",
    "Hitotsu-Me Giant",
    "Horn of Heaven",
    "Horn of Light",
    "Horn of the Unicorn",
    "Hoshiningen",
    "House of Adhesive Tape",
    "Hungry Burger",
    "Hunter Spider",
    "Hyosube",
    "Hyozanryu",
    "Illusionist Faceless Mage",
    "Imperial Order",
    "Infinite Dismissal",
    "Insect Barrier",
    "Insect Imitation",
    "Insect Soldiers of the Sky",
    "Inspection",
    "Invader of the Throne",
    "Invigoration",
    "Invitation to a Dark Sleep",
    "Island Turtle",
    "Jellyfish",
    "Jigen Bakudan",
    "Jinzo",
    "Jinzo #7",
    "Jirai Gumo",
    "Judge Man",
    "Just Desserts",
    "Kagemusha of the Blue Flame",
    "Kaminari Attack",
    "Karate Man",
    "Karbonala Warrior",
    "Kazejin",
    "Killer Needle",
    "King Fog",
    "King of Yamimakai",
    "Kiseitai",
    "Kojikocy",
    "Kotodama",
    "Koumori Dragon",
    "Kumootoko",
    "Kurama",
    "Kuriboh",
    "Kwagar Hercules",
    "La Jinn the Mystical Genie of the Lamp",
    "Labyrinth Tank",
    "Labyrinth Wall",
    "Lady of Faith",
    "Larvae Moth",
    "Larvas",
    "Laser Cannon Armor",
    "Last Will",
    "Launcher Spider",
    "Lava Battleguard",
    "Left Arm of the Forbidden One",
    "Left Leg of the Forbidden One",
    "Legendary Sword",
    "Leghul",
    "Leogun",
    "Lesser Dragon",
    "Light of Intervention",
    "Lightforce Sword",
    "Limiter Removal",
    "Liquid Beast",
    "Little Chimera",
    "Lord of D.",
    "Luminous Spark",
    "M-Warrior #1",
    "M-Warrior #2",
    "Machine Conversion Factory",
    "Mad Sword Beast",
    "Magic Drain",
    "Magic Jammer",
    "Magical Ghost",
    "Magical Hats",
    "Magical Labyrinth",
    "Magician of Faith",
    "Maha Vailo",
    "Maiden of the Moonlight",
    "Major Riot",
    "Malevolent Nuzzler",
    "Mammoth Graveyard",
    "Man Eater",
    "Man-Eater Bug",
    "Man-Eating Treasure Chest",
    "Manga Ryu-Ran",
    "Masaki the Legendary Swordsman",
    "Mask of Darkness",
    "Masked Sorcerer",
    "Master & Expert",
    "Mechanical Snail",
    "Mechanicalchaser",
    "Meda Bat",
    "Mega Thunderball",
    "Megamorph",
    "Messenger of Peace",
    "Metal Detector",
    "Metal Dragon",
    "Metal Fish",
    "Michizure",
    "Mikazukinoyaiba",
    "Milus Radiant",
    "Minar",
    "Minor Goblin Official",
    "Mirror Force",
    "Mirror Wall",
    "Misairuzame",
    "Molten Destruction",
    "Monster Egg",
    "Monster Reborn",
    "Monster Recovery",
    "Morinphen",
    "Morphing Jar",
    "Morphing Jar #2",
    "Mother Grizzly",
    "Mountain",
    "Mr. Volcano",
    "Muka Muka",
    "Mushroom Man #2",
    "Musician King",
    "Mysterious Puppeteer",
    "Mystic Clown",
    "Mystic Horseman",
    "Mystic Lamp",
    "Mystic Plasma Zone",
    "Mystic Probe",
    "Mystic Tomato",
    "Mystical Elf",
    "Mystical Moon",
    "Mystical Sheep #1",
    "Mystical Sheep #2",
    "Mystical Space Typhoon",
    "Nemuriko",
    "Neo the Magic Swordsman",
    "Nimble Momonga",
    "Niwatori",
    "Nobleman of Crossout",
    "Nobleman of Extermination",
    "Novox's Prayer",
    "Numinous Healer",
    "Octoberser",
    "Ocubeam",
    "Ogre of the Black Shadow",
    "One-Eyed Shield Dragon",
    "Oni Tank T-34",
    "Ooguchi",
    "Ookazi",
    "Oscillo Hero",
    "Overdrive",
    "Painful Choice",
    "Pale Beast",
    "Paralyzing Potion",
    "Parasite Paracide",
    "Parrot Dragon",
    "Patrol Robo",
    "Peacock",
    "Penguin Knight",
    "Performance of Sword",
    "Petit Angel",
    "Petit Dragon",
    "Petit Moth",
    "Polymerization",
    "Pot of Greed",
    "Power of Kaishin",
    "Premature Burial",
    "Prevent Rat",
    "Princess of Tsurugi",
    "Prohibition",
    "Protector of the Throne",
    "Psychic Kappa",
    "Pumpking the King of Ghosts",
    "Punished Eagle",
    "Queen Bird",
    "Queen of Autumn Leaves",
    "Queen's Double",
    "Rabid Horseman",
    "Raigeki",
    "Raimei",
    "Rain of Mercy",
    "Rainbow Flower",
    "Raise Body Heat",
    "Ray & Temperature",
    "Reaper of the Cards",
    "Red Archery Girl",
    "Red Medicine",
    "Red-Eyes Black Dragon",
    "Reinforcements",
    "Relinquished",
    "Remove Trap",
    "Respect Play",
    "Reverse Trap",
    "Revival of Dokurorider",
    "Right Arm of the Forbidden One",
    "Right Leg of the Forbidden One",
    "Ring of Magnetism",
    "Rising Air Current",
    "Roaring Ocean Snake",
    "Robbin' Goblin",
    "Rock Ogre Grotto #1",
    "Rogue Doll",
    "Root Water",
    "Rude Kaiser",
    "Rush Recklessly",
    "Ryu-Kishin",
    "Ryu-Kishin Powered",
    "Ryu-Ran",
    "Saggi the Dark Clown",
    "Salamandra",
    "Sand Stone",
    "Sanga of the Thunder",
    "Sangan",
    "Science Soldier",
    "Seiyaryu",
    "Senju of the Thousand Hands",
    "Serpent Night Dragon",
    "Seven Tools of the Bandit",
    "Shadow Ghoul",
    "Shadow of Eyes",
    "Share the Pain",
    "Shield & Sword",
    "Shift",
    "Shining Angel",
    "Shining Friendship",
    "Silver Bow and Arrow",
    "Silver Fang",
    "Skull Dice",
    "Skull Guardian",
    "Skull Invitation",
    "Skull Knight",
    "Skull Mariner",
    "Skull Red Bird",
    "Skull Servant",
    "Sky Dragon",
    "Sky Scout",
    "Slot Machine",
    "Snake Fang",
    "Snatch Steal",
    "Sogen",
    "Solemn Judgment",
    "Solemn Wishes",
    "Solomon's Lawbook",
    "Sonic Bird",
    "Sonic Maid",
    "Sorcerer of the Doomed",
    "Soul Exchange",
    "Soul of the Pure",
    "Soul Release",
    "Souls of the Forgotten",
    "Sparks",
    "Spear Cretin",
    "Spellbinding Circle",
    "Spike Seadra",
    "Spikebot",
    "Spirit of the Books",
    "Spirit of the Harp",
    "Star Boy",
    "Steel Ogre Grotto #1",
    "Steel Ogre Grotto #2",
    "Steel Scorpion",
    "Steel Shell",
    "Stim-Pack",
    "Stone Ogre Grotto",
    "Stop Defense",
    "Stuffed Animal",
    "Succubus Knight",
    "Suijin",
    "Summoned Skull",
    "Swamp Battleguard",
    "Sword Hunter",
    "Sword of Dark Destruction",
    "Sword of Deep-Seated",
    "Swords of Revealing Light",
    "Swordstalker",
    "Tailor of the Fickle",
    "Tainted Wisdom",
    "Takuhee",
    "Terra the Terrible",
    "The 13th Grave",
    "The All-Seeing White Tiger",
    "The Bistro Butcher",
    "The Cheerful Coffin",
    "The Eye of Truth",
    "The Fiend Megacyber",
    "The Flute of Summoning Dragon",
    "The Forceful Sentry",
    "The Furious Sea King",
    "The Immortal of Thunder",
    "The Inexperienced Spy",
    "The Judgement Hand",
    "The Legendary Fisherman",
    "The Little Swordsman of Aile",
    "The Regulation of Tribe",
    "The Reliable Guardian",
    "The Shallow Grave",
    "The Statue of Easter Island",
    "The Stern Mystic",
    "The Unhappy Maiden",
    "The Wicked Worm Beast",
    "Thousand Dragon",
    "Thousand-Eyes Idol",
    "Thousand-Eyes Restrict",
    "Three-Headed Geedo",
    "Thunder Dragon",
    "Tiger Axe",
    "Time Seal",
    "Time Wizard",
    "Toll",
    "Tongyo",
    "Toon Mermaid",
    "Toon Summoned Skull",
    "Toon World",
    "Trap Hole",
    "Trap Master",
    "Tremendous Fire",
    "Trent",
    "Tri-Horned Dragon",
    "Trial of Nightmare",
    "Tribute to the Doomed",
    "Tripwire Beast",
    "Turtle Oath",
    "Turtle Tiger",
    "Turu-Purun",
    "Twin Long Rods #2",
    "Twin-Headed Fire Dragon",
    "Twin-Headed Thunder Dragon",
    "Two-Headed King Rex",
    "Two-Mouth Darkruler",
    "Two-Pronged Attack",
    "Tyhone",
    "Tyhone #2",
    "Type Zero Magic Crusher",
    "UFO Turtle",
    "Ultimate Offering",
    "Umi",
    "Umiiruka",
    "Unknown Warrior of Fiend",
    "Upstart Goblin",
    "Uraby",
    "Vampire Baby",
    "Versago the Destroyer",
    "Vile Germs",
    "Violet Crystal",
    "Waboku",
    "Wall of Illusion",
    "Wall Shadow",
    "Warrior of Tradition",
    "Wasteland",
    "Water Magician",
    "Water Omotics",
    "Wattkid",
    "Weather Report",
    "Whiptail Crow",
    "White Hole",
    "White Magical Hat",
    "Winged Dragon, Guardian of the Fortress #1",
    "Winged Dragon, Guardian of the Fortress #2",
    "Wingweaver",
    "Witch of the Black Forest",
    "Witch's Apprentice",
    "Witty Phantom",
    "Wodan the Resident of the Forest",
    "World Suppression",
    "Wow Warrior",
    "Yado Karu",
    "Yami"
]

# for card in eds_cards:
    # if card not in imperial_cards:
        # attribute = 'None'
        # level = 0
        # atk = 0
        # defn = 0
        # try:
            # for set in data2[card]['set_chronology_ocg']:
                # try:
                    # attribute = card_info[card]['attribute']
                    # level = card_info[card]['level']
                    # atk = card_info[card]['atk']
                    # defn = card_info[card]['def']
                    # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set[0] + ' (OCG)\t' + set[1].split('/')[3], months[int(set[1].split('/')[2])], set[1].split('/')[1])
                # except:
                    # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set[0] + ' (OCG)\t' + set[1].split('/')[3], months[int(set[1].split('/')[2])], set[1].split('/')[1])
        # except:
            # try:
                # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']))
            # except Exception as e:
                # pass

mod = [
    "7",
    "Blue-Eyes White Dragon",
    "Mystical Elf",
    "Hitotsu-Me Giant",
    "Baby Dragon",
    "Ryu-Kishin",
    "Feral Imp",
    "Winged Dragon, Guardian of the Fortress #1",
    "Mushroom Man",
    "Blackland Fire Dragon",
    "Tyhone",
    "Flame Swordsman",
    "Time Wizard",
    "Right Leg of the Forbidden One",
    "Left Leg of the Forbidden One",
    "Right Arm of the Forbidden One",
    "Left Arm of the Forbidden One",
    "Exodia the Forbidden One",
    "Summoned Skull",
    "The Wicked Worm Beast",
    "Skull Servant",
    "Horn Imp",
    "Battle Ox",
    "Beaver Warrior",
    "Rock Ogre Grotto #1",
    "Mountain Warrior",
    "Zombie Warrior",
    "Koumori Dragon",
    "Two-Headed King Rex",
    "Judge Man",
    "Saggi the Dark Clown",
    "Dark Magician",
    "The Snake Hair",
    "Gaia the Dragon Champion",
    "Gaia The Fierce Knight",
    "Curse of Dragon",
    "Celtic Guardian",
    "Illusionist Faceless Mage",
    "Karbonala Warrior",
    "Rogue Doll",
    "Wattkid",
    "Griffore",
    "Torike",
    "Sangan",
    "Big Insect",
    "Basic Insect",
    "Armored Lizard",
    "Killer Needle",
    "Gokibore",
    "Giant Flea",
    "Larvae Moth",
    "Great Moth",
    "Kuriboh",
    "Mammoth Graveyard",
    "Great White",
    "Wolf",
    "Harpie Lady",
    "Harpie Lady Sisters",
    "Tiger Axe",
    "Silver Fang",
    "Kojikocy",
    "Perfectly Ultimate Great Moth",
    "Thousand Dragon",
    "Fiend Kraken",
    "Jellyfish",
    "Cocoon of Evolution",
    "Giant Soldier of Stone",
    "Man-Eating Plant",
    "Krokodilus",
    "Grappler",
    "Axe Raider",
    "Megazowler",
    "Uraby",
    "Crawling Dragon #2",
    "Red-Eyes Black Dragon",
    "Castle of Dark Illusions",
    "Reaper of the Cards",
    "King of Yamimakai",
    "Barox",
    "Metal Guardian",
    "Catapult Turtle",
    "Gyakutenno Megami",
    "Mystic Horseman",
    "Rabid Horseman",
    "Crass Clown",
    "Armored Zombie",
    "Dragon Zombie",
    "Clown Zombie",
    "Pumpking the King of Ghosts",
    "Battle Warrior",
    "Wings of Wicked Flame",
    "Mask of Darkness",
    "Job-Change Mirror",
    "Curtain of the Dark Ones",
    "Kageningen",
    "Graveyard and the Hand of Invitation",
    "Goddess with the Third Eye",
    "Hero of the East",
    "That Which Feeds on Life",
    "Dark Gray",
    "White Magical Hat",
    "Kamionwizard",
    "Nightmare Scorpion",
    "Spirit of the Books",
    "Supporter in the Shadows",
    "Trial of Nightmare",
    "Dream Clown",
    "Sleeping Lion",
    "Yamatano Dragon Scroll",
    "Faith Bird",
    "Nemuriko",
    "Weather Control",
    "The 13th Grave",
    "Charubin the Fire Knight",
    "Mystical Capture Chain",
    "Fiend's Hand",
    "Witty Phantom",
    "Dragon Statue",
    "Blue-Eyed Silver Zombie",
    "Toad Master",
    "Spiked Snail",
    "Flame Manipulator",
    "Necrolancer the Time-lord",
    "Djinn the Watcher of the Wind",
    "The Bewitching Phantom Thief",
    "Temple of Skulls",
    "Monster Egg",
    "The Shadow Who Controls the Dark",
    "Lord of the Lamp",
    "Rhaimundos of the Red Sword",
    "The Melting Red Shadow",
    "Dokuroizo the Grim Reaper",
    "Fire Reaper",
    "Larvas",
    "Hard Armor",
    "Firegrass",
    "Man Eater",
    "Dig Beak",
    "M-Warrior #1",
    "M-Warrior #2",
    "Lisark",
    "Lord of Zemia",
    "The Judgement Hand",
    "Mysterious Puppeteer",
    "Darkfire Dragon",
    "Dark King of the Abyss",
    "Spirit of the Harp",
    "Armaill",
    "Dark Prisoner",
    "Hurricail",
    "Fire Eye",
    "Monsturtle",
    "Claw Reacher",
    "Phantom Dewan",
    "Arlownay",
    "Dark Shade",
    "Masked Clown",
    "Lucky Trinket",
    "Genin",
    "Eyearmor",
    "Fiend Reflection #2",
    "Gate Deeg",
    "Synchar",
    "Fusionist",
    "Akakieisu",
    "LaLa Li-oon",
    "Turtle Tiger",
    "Terra the Terrible",
    "Doron",
    "Arma Knight",
    "Happy Lover",
    "Penguin Knight",
    "Petit Dragon",
    "Frenzied Panda",
    "Archfiend Marmot of Nefariousness",
    "Phantom Ghost",
    "Dorover",
    "Twin Long Rods #1",
    "Droll Bird",
    "Petit Angel",
    "Winged Cleaver",
    "Hinotama Soul",
    "Thunder Kid",
    "Meotoko",
    "Aqua Madoor",
    "Kagemusha of the Blue Flame",
    "Flame Ghost",
    "Doriado",
    "Black Skull Dragon",
    "Two-Mouth Darkruler",
    "Solitude",
    "Masked Sorcerer",
    "Kumootoko",
    "Midnight Fiend",
    "Trap Master",
    "Fiend Sword",
    "Skull Stalker",
    "Hitodenchak",
    "Wood Remains",
    "Hourglass of Life",
    "Rare Fish",
    "Wood Clown",
    "Madjinn Gunn",
    "Dark Titan of Terror",
    "Beautiful Headhuntress",
    "Guardian of the Labyrinth",
    "Yashinoki",
    "Vishwar Randi",
    "The Drdek",
    "Dark Assailant",
    "Candle of Fate",
    "Water Element",
    "Dissolverock",
    "Meda Bat",
    "One Who Hunts Souls",
    "Root Water",
    "Master & Expert",
    "Water Omotics",
    "Hyo",
    "Enchanting Mermaid",
    "Nekogal #1",
    "Fairywitch",
    "Embryonic Beast",
    "Prevent Rat",
    "D.D. Warrior",
    "Stone Armadiller",
    "Beastking of the Swamps",
    "Ancient Sorcerer",
    "Lunar Queen Elzaim",
    "Archfiend Mirror",
    "The Little Swordsman of Aile",
    "Rock Ogre Grotto #2",
    "Wing Egg Elf",
    "The Furious Sea King",
    "Princess of Tsurugi",
    "Unknown Warrior of Fiend",
    "Sectarian of Secrets",
    "Versago the Destroyer",
    "Wetha",
    "Megirus Light",
    "Mavelus",
    "Ancient Tree of Enlightenment",
    "Green Phantom King",
    "Ground Attacker Bugroth",
    "Ray & Temperature",
    "Gorgon Egg",
    "Petit Moth",
    "King Fog",
    "Protector of the Throne",
    "Mystic Clown",
    "Mystical Sheep #2",
    "Holograh",
    "Tao the Chanter",
    "Serpent Marauder",
    "Ogre of the Black Shadow",
    "Moon Envoy",
    "Fireyarou",
    "Psychic Kappa",
    "Masaki the Legendary Swordsman",
    "Dragoness the Wicked Knight",
    "Bio Plant",
    "One-Eyed Shield Dragon",
    "Cyber Soldier of Darkworld",
    "Wicked Dragon with the Ersatz Head",
    "Sonic Maid",
    "Kurama",
    "Axe of Despair",
    "Insect Armor with Laser Cannon",
    "Black Pendant",
    "Horn of Light",
    "Horn of the Unicorn",
    "Elegant Egotist",
    "Stop Defense",
    "Malevolent Nuzzler",
    "Dragon Capture Jar",
    "Forest",
    "Wasteland",
    "Mountain",
    "Sogen",
    "Umi",
    "Yami",
    "Dark Hole",
    "Raigeki",
    "Mooyan Curry",
    "Red Medicine",
    "Goblin's Secret Remedy",
    "Soul of the Pure",
    "Dian Keto the Cure Master",
    "Sparks",
    "Ookazi",
    "Tremendous Fire",
    "Swords of Revealing Light",
    "Spellbinding Circle",
    "Dark-Piercing Light",
    "Yaranzo",
    "Kanan the Swordmistress",
    "Takriminos",
    "Stuffed Animal",
    "Super War-Lion",
    "Three-Legged Zombies",
    "Zera the Mant",
    "Flying Penguin",
    "Millennium Shield",
    "Fairy's Gift",
    "Black Luster Soldier",
    "Fiend's Mirror",
    "Labyrinth Wall",
    "Jirai Gumo",
    "Shadow Ghoul",
    "Wall Shadow",
    "Labyrinth Tank",
    "Sanga of the Thunder",
    "Kazejin",
    "Suijin",
    "Gate Guardian",
    "Ryu-Kishin Powered",
    "Swordstalker",
    "La Jinn the Mystical Genie of the Lamp",
    "Blue-Eyes Ultimate Dragon",
    "Toon Alligator",
    "Parrot Dragon",
    "Dark Rabbit",
    "Bickuribox",
    "Harpie's Pet Dragon",
    "Pendulum Machine",
    "Giltia the D. Knight",
    "Launcher Spider",
    "Zoa",
    "Metalzoa",
    "Ocubeam",
    "Monster Eye",
    "Yaiba Robo",
    "Machine King",
    "Metal Dragon",
    "Giga-Tech Wolf",
    "Shovel Crusher",
    "Mechanicalchaser",
    "Blocker",
    "Golgoil",
    "Cyber-Stein",
    "Cyber Commander",
    "Jinzo #7",
    "Thunder Dragon",
    "Kaiser Dragon",
    "Magician of Faith",
    "Goddess of Whim",
    "Water Magician",
    "Ice Water",
    "Waterdragon Fairy",
    "Ancient Elf",
    "Water Girl",
    "Deepsea Shark",
    "Bottom Dweller",
    "7 Colored Fish",
    "Sentinel of the Seas",
    "Aqua Snake",
    "Giant Red Seasnake",
    "Kappa Avenger",
    "Kanikabuto",
    "Zarigun",
    "Millennium Golem",
    "Destroyer Golem",
    "Barrel Rock",
    "Minomushi Warrior",
    "Stone Ghost",
    "Kaminari Attack",
    "Tripwire Beast",
    "Bolt Penguin",
    "The Immortal of Thunder",
    "Electric Snake",
    "Punished Eagle",
    "Skull Red Bird",
    "Crimson Sunbird",
    "Armed Ninja",
    "Magical Ghost",
    "Soul Hunter",
    "Vermillion Sparrow",
    "Sea Kamen",
    "Sinister Serpent",
    "Ganigumo",
    "Alinsection",
    "Insect Soldiers of the Sky",
    "Cockroach Knight",
    "Burglar",
    "Pragtical",
    "Ameba",
    "Korogashi",
    "Boo Koo",
    "Flower Wolf",
    "Rainbow Flower",
    "Barrel Lily",
    "Hoshiningen",
    "Maha Vailo",
    "Musician King",
    "Wilmee",
    "Dragon Seeker",
    "Man-Eater Bug",
    "D. Human",
    "Turtle Raccoon",
    "Prisman",
    "Crazy Fish",
    "Bracchio-raidus",
    "Laughing Flower",
    "Bean Soldier",
    "Cannon Soldier",
    "Guardian of the Throne Room",
    "Brave Scizzar",
    "The Statue of Easter Island",
    "Muka Muka",
    "Boulder Tortoise",
    "Fire Kraken",
    "Turtle Bird",
    "Skullbird",
    "Monstrous Bird",
    "The Bistro Butcher",
    "Star Boy",
    "Milus Radiant",
    "Flame Cerebrus",
    "Eldeen",
    "Mystical Sand",
    "Gemini Elf",
    "Minar",
    "Kamakiriman",
    "Mechaleon",
    "Mega Thunderball",
    "Niwatori",
    "Corroding Shark",
    "Skelengel",
    "Hane-Hane",
    "Tongyo",
    "Dharma Cannon",
    "Skelgon",
    "Wow Warrior",
    "Griggle",
    "Slime Toad",
    "Behegon",
    "Dark Elf",
    "Winged Dragon, Guardian of the Fortress #2",
    "The Wandering Doomed",
    "Steel Ogre Grotto #1",
    "Oscillo Hero",
    "Invader from Another Dimension",
    "Lesser Dragon",
    "Needle Worm",
    "Wretched Ghost of the Attic",
    "Great Mammoth of Goldfine",
    "Man-Eating Black Shark",
    "Yormungarde",
    "Darkworld Thorns",
    "Anthrosaurus",
    "Drooling Lizard",
    "Trakodon",
    "B. Dragon Jungle King",
    "Little D",
    "Witch of the Black Forest",
    "Giant Scorpion of the Tundra",
    "Abyss Flower",
    "Takuhee",
    "Binding Chain",
    "Mechanical Snail",
    "Greenkappa",
    "Mon Larvas",
    "Living Vase",
    "Tentacle Plant",
    "Beaked Snake",
    "Morphing Jar",
    "Muse-A",
    "Rose Spectre of Dunn",
    "Fiend Reflection #1",
    "Ghoul with an Appetite",
    "Pale Beast",
    "Little Chimera",
    "Violent Rain",
    "Key Mace #2",
    "Tenderness",
    "Penguin Soldier",
    "Fairy Dragon",
    "Obese Marmot of Nefariousness",
    "Liquid Beast",
    "Twin Long Rods #2",
    "Great Bill",
    "Shining Friendship",
    "Bladefly",
    "Hiro's Shadow Scout",
    "Lady of Faith",
    "Twin-Headed Thunder Dragon",
    "Armored Starfish",
    "Marine Beast",
    "Warrior of Tradition",
    "Snakeyashi",
    "The Thing That Hides in the Mud",
    "High Tide Gyojin",
    "Fairy of the Fountain",
    "Amazon of the Seas",
    "Nekogal #2",
    "Witch's Apprentice",
    "Armored Rat",
    "Ancient Lizard Warrior",
    "Maiden of the Moonlight",
    "Night Lizard",
    "Blue-Winged Crown",
    "Amphibious Bugroth",
    "Acid Crawler",
    "Invader of the Throne",
    "Mystical Sheep #1",
    "Disk Magician",
    "Flame Viper",
    "Royal Guard",
    "Gruesome Goo",
    "Whiptail Crow",
    "Kunai with Chain",
    "Magical Labyrinth",
    "Salamandra",
    "Eternal Rest",
    "Megamorph",
    "Metalmorph",
    "Crush Card Virus",
    "Shine Palace",
    "Shadow Spell",
    "Black Luster Ritual",
    "Zera Ritual",
    "Harpie's Feather Duster",
    "War-Lion Ritual",
    "Beastly Mirror Ritual",
    "Commencement Dance",
    "Hamburger Recipe",
    "Novox's Prayer",
    "House of Adhesive Tape",
    "Acid Trap Hole",
    "Widespread Ruin",
    "Bad Reaction to Simochi",
    "Reverse Trap",
    "Turtle Oath",
    "Resurrection of Chakra",
    "Javelin Beetle Pact",
    "Garma Sword Oath",
    "Revival of Dokurorider",
    "Fortress Whale's Oath",
    "Performance of Sword",
    "Hungry Burger",
    "Sengenjin",
    "Skull Guardian",
    "Tri-Horned Dragon",
    "Serpent Night Dragon",
    "Cosmo Queen",
    "Chakra",
    "Crab Turtle",
    "Mikazukinoyaiba",
    "Meteor Dragon",
    "Meteor Black Dragon",
    "Firewing Pegasus",
    "Garma Sword",
    "Javelin Beetle",
    "Fortress Whale",
    "Dokurorider",
    "Black Magic Ritual",
    "Magician of Black Chaos",
    "Slot Machine",
    "Red Archery Girl",
    "Ryu-Ran",
    "Manga Ryu-Ran",
    "Toon Mermaid",
    "Toon Summoned Skull",
    "Relinquished",
    "Thousand-Eyes Idol",
    "Thousand-Eyes Restrict",
    "Steel Ogre Grotto #2",
    "Blast Sphere",
    "Hyozanryu",
    "Alpha The Magnet Warrior",
    "Lord of D.",
    "Red-Eyes Black Metal Dragon",
    "Barrel Dragon",
    "Hannibal Necromancer",
    "Panther Warrior",
    "Three-Headed Geedo",
    "Gazelle the King of Mythical Beasts",
    "Stone Statue of the Aztecs",
    "Berfomet",
    "Chimera the Flying Mythical Beast",
    "Gear Golem the Moving Fortress",
    "Jinzo",
    "Swordsman of Landstar",
    "Cyber Raider",
    "The Fiend Megacyber",
    "Reflect Bounder",
    "Beta The Magnet Warrior",
    "Big Shield Gardna",
    "Dark Magician Girl",
    "Alligator's Sword",
    "Insect Queen",
    "Parasite Paracide",
    "Skull-Mark Ladybug",
    "Little-Winguard",
    "Pinch Hopper",
    "Blue-Eyes Toon Dragon",
    "Sword Hunter",
    "Drill Bug",
    "Deepsea Warrior",
    "Satellite Cannon",
    "The Last Warrior from Another Planet",
    "Dunames Dark Witch",
    "Garnecia Elefantis",
    "Total Defense Shogun",
    "Beast of Talwar",
    "Cyber-Tech Alligator",
    "Gamma the Magnet Warrior",
    "Time Machine",
    "Copycat",
    "Toon World",
    "Gorgon's Eye",
    "Black Illusion Ritual",
    "Brain Control",
    "Negate Attack",
    "Multiply",
    "Lightforce Sword",
    "The Flute of Summoning Dragon",
    "Shield & Sword",
    "Graceful Charity",
    "Chain Destruction",
    "Mesmeric Control",
    "Graceful Dice",
    "Skull Dice",
    "Mind Control",
    "Scapegoat",
    "Amplifier",
    "Card Destruction",
    "Tragedy",
    "Ectoplasmer",
    "Dark Magic Curtain",
    "Insect Barrier",
    "Magical Arm Shield",
    "Fissure",
    "Trap Hole",
    "Polymerization",
    "Remove Trap",
    "Two-Pronged Attack",
    "Monster Reborn",
    "De-Spell",
    "Pot of Greed",
    "Gravedigger Ghoul",
    "Reinforcements",
    "Castle Walls",
    "Ultimate Offering",
    "Tribute to the Doomed",
    "Soul Release",
    "The Cheerful Coffin",
    "Change of Heart",
    "Solemn Judgment",
    "Magic Jammer",
    "Seven Tools of the Bandit",
    "Horn of Heaven",
    "Just Desserts",
    "Royal Decree",
    "Magical Thorn",
    "Restructer Revolution",
    "Fusion Sage",
    "Sword of Deep-Seated",
    "Block Attack",
    "The Unhappy Maiden",
    "Robbin' Goblin",
    "Germ Infection",
    "Wall of Illusion",
    "Neo the Magic Swordsman",
    "Baron of the Fiend Sword",
    "Man-Eating Treasure Chest",
    "Sorcerer of the Doomed",
    "Last Will",
    "Waboku",
    "Mirror Force",
    "Ring of Magnetism",
    "Share the Pain",
    "Stim-Pack",
    "Heavy Storm",
    "Gravekeeper's Servant",
    "Upstart Goblin",
    "Toll",
    "Final Destiny",
    "Snatch Steal",
    "Chorus of Sanctuary",
    "Confiscation",
    "Delinquent Duo",
    "Fairy's Hand Mirror",
    "Tailor of the Fickle",
    "Rush Recklessly",
    "The Reliable Guardian",
    "The Forceful Sentry",
    "Chain Energy",
    "Mystical Space Typhoon",
    "Giant Trunade",
    "Painful Choice",
    "Snake Fang",
    "Cyber Jar",
    "Banisher of the Light",
    "Giant Rat",
    "Senju of the Thousand Hands",
    "UFO Turtle",
    "Flash Assailant",
    "Karate Man",
    "Giant Germ",
    "Nimble Momonga",
    "Spear Cretin",
    "Shining Angel",
    "Mother Grizzly",
    "Flying Kamakiri #1",
    "Ceremonial Bell",
    "Sonic Bird",
    "Mystic Tomato",
    "Kotodama",
    "Gaia Power",
    "Umiiruka",
    "Molten Destruction",
    "Rising Air Current",
    "Luminous Spark",
    "Mystic Plasma Zone",
    "Messenger of Peace",
    "Michizure",
    "Gust",
    "Driving Snow",
    "Numinous Healer",
    "Appropriate",
    "Forced Requisition",
    "Minor Goblin Official",
    "Gamble",
    "DNA Surgery",
    "The Regulation of Tribe",
    "Backup Soldier",
    "Attack and Receive",
    "Ceasefire",
    "Light of Intervention",
    "Respect Play",
    "Imperial Order",
    "Skull Invitation",
    "Magical Hats",
    "Nobleman of Crossout",
    "Nobleman of Extermination",
    "The Shallow Grave",
    "Premature Burial",
    "Morphing Jar #2",
    "Bubonic Vermin",
    "Twin-Headed Fire Dragon",
    "Darkfire Soldier #1",
    "Mr. Volcano",
    "Darkfire Soldier #2",
    "Kiseitai",
    "Cyber Falcon",
    "Dark Bat",
    "Flying Kamakiri #2",
    "Sky Scout",
    "Oni Tank T-34",
    "Overdrive",
    "Buster Blader",
    "Time Seal",
    "Graverobber",
    "Gift of The Mystical Elf",
    "The Eye of Truth",
    "Dust Tornado",
    "Call of the Haunted",
    "Solomon's Lawbook",
    "Enchanted Javelin",
    "Mirror Wall",
    "Windstorm of Etaqua",
    "Valkyrion the Magna Warrior",
    "Alligator's Sword Dragon",
    "Vorse Raider",
    "Ring of Destruction",
    "Aqua Chorus",
    "Sebek's Blessing",
    "Anti-Spell Fragrance",
    "Riryoku",
    "Sword of Dragon's Soul",
    "Luminous Soldier",
    "King Tiger Wanghu",
    "Command Knight",
    "Wolf Axwielder",
    "The Illusory Gentleman",
    "Patrician of Darkness",
    "Birdface",
    "Kryuel",
    "Airknight Parshath",
    "Fairy King Truesdale",
    "Serpentine Princess",
    "Maiden of the Aqua",
    "Robotic Knight",
    "Thunder Nyan Nyan",
    "Molten Behemoth",
    "Twin-Headed Behemoth",
    "Injection Fairy Lily",
    "Woodland Sprite",
    "Arsenal Bug",
    "Cipher Soldier",
    "Jowls of Dark Demise",
    "Souleater",
    "Slate Warrior",
    "Timeater",
    "Mucus Yolk",
    "Servant of Catabolism",
    "Rigorous Reaver",
    "Moisture Creature",
    "Boneheimer",
    "Flame Dancer",
    "Sonic Jammer",
    "Gearfried the Iron Knight",
    "Humanoid Slime",
    "Worm Drake",
    "Humanoid Worm Drake",
    "Revival Jam",
    "Flying Fish",
    "Amphibian Beast",
    "Rocket Warrior",
    "The Legendary Fisherman",
    "Robolady",
    "Roboyarou",
    "Lightning Conger",
    "Spherous Lady",
    "Shining Abyss",
    "Archfiend of Gilfer",
    "Gadget Soldier",
    "Grand Tiki Elder",
    "The Masked Beast",
    "Melchid the Four-Face Beast",
    "Nuvia the Wicked",
    "Soul Exchange",
    "Mask of Weakness",
    "Curse of the Masked Beast",
    "Mask of Dispel",
    "Mask of Restrict",
    "Mask of the Accursed",
    "Mask of Brutality",
    "Return of the Doomed",
    "Lightning Blade",
    "Tornado Wall",
    "Infinite Dismissal",
    "Fairy Box",
    "Torrential Tribute",
    "Multiplication of Ants",
    "De-Fusion",
    "Jam Breeding Machine",
    "Nightmare's Steelcage",
    "Infinite Cards",
    "Jam Defender",
    "Card of Safe Return",
    "Magic Cylinder",
    "Solemn Wishes",
    "Burning Land",
    "Cold Wave",
    "Fairy Meteor Crush",
    "Limiter Removal",
    "Shift",
    "Insect Imitation",
    "Dimensionhole",
    "Magic Drain",
    "Gravity Bind",
    "Shadow of Eyes",
    "Girochin Kuwagata",
    "Hayabusa Knight",
    "Bombardment Beetle",
    "4-Starred Ladybug of Doom",
    "Gradius",
    "Vampire Baby",
    "Mad Sword Beast",
    "Skull Mariner",
    "The All-Seeing White Tiger",
    "Goblin Attack Force",
    "Island Turtle",
    "Wingweaver",
    "Science Soldier",
    "Souls of the Forgotten",
    "Dokuroyaiba",
    "Rain of Mercy",
    "Monster Recovery",
    "Type Zero Magic Crusher",
    "Yellow Luster Shield",
    "Creature Swap",
    "Thousand Knives",
    "Mystic Box",
    "Ground Collapse",
    "Amazoness Archer",
    "Fire Princess",
    "Spirit of the Breeze",
    "Dancing Fairy",
    "Empress Mantis",
    "Cure Mermaid",
    "Hysteric Fairy",
    "Bio-Mage",
    "The Forgiving Maiden",
    "St. Joan",
    "Darklord Marie",
    "Jar of Greed",
    "Scroll of Bewitchment",
    "United We Stand",
    "Mage Power",
    "Offerings to the Doomed",
    "Meteor of Destruction",
    "Lightning Vortex",
    "Exchange",
    "The Portrait's Secret",
    "The Gross Ghost of Fled Dreams",
    "Headless Knight",
    "Dark Necrofear",
    "Magic Formula",
    "Destiny Board",
    "The Dark Door",
    "Earthbound Spirit",
    "Dark Spirit of the Silent",
    "The Earl of Demise",
    "Dark Sage",
    "Temple of the Kings",
    "Judgment of Anubis",
    "Embodiment of Apophis",
    "Foolish Burial",
    "Makiu, the Magical Mist",
    "Ancient Lamp",
    "Cyber Harpie Lady",
    "Mystical Beast of Serket",
    "Swift Gaia the Fierce Knight",
    "Obnoxious Celtic Guard",
    "Zombyra the Dark",
    "Spiritualism",
    "Jowgen the Spiritualist",
    "Kycoo the Ghost Destroyer",
    "Summoner of Illusions",
    "Bazoo the Soul-Eater",
    "Soul of Purity and Light",
    "Spirit of Flames",
    "Aqua Spirit",
    "The Rock Spirit",
    "Garuda the Wind Spirit",
    "Gilasaurus",
    "Tornado Bird",
    "Dreamsprite",
    "Supply",
    "Maryokutai",
    "Collected Power",
    "Royal Command",
    "Riryoku Field",
    "Skull Lair",
    "Graverobber's Retribution",
    "Deal of Phantom",
    "Destruction Punch",
    "Blind Destruction",
    "The Emperor's Holiday",
    "Cyclon Laser",
    'Spirit Message "I"',
    'Spirit Message "N"',
    'Spirit Message "A"',
    'Spirit Message "L"',
    "Bait Doll",
    "Fusion Gate",
    "Ekibyo Drakmord",
    "Miracle Dig",
    "Vengeful Bog Spirit",
    "Amazoness Swords Woman",
    "Makyura the Destructor",
    "Amazoness Archers",
    "Rope of Life",
    "Spell Shattering Arrow",
    "Amazoness Chain Master",
    "Viser Des",
    "Amazoness Fighter",
    "Nightmare Wheel",
    "Byser Shock",
    "Dark Ruler Ha Des",
    "Dark Balter the Terrible",
    "Lesser Fiend",
    "Possessed Dark Soul",
    "Winged Minion",
    "Ryu-Kishin Clown",
    "Twin-Headed Wolf",
    "Opticlops",
    "Bark of Dark Ruler",
    "Fatal Abacus",
    "Life Absorbing Machine",
    "Double Snare",
    "Freed the Matchless General",
    "Throwstone Unit",
    "Marauding Captain",
    "Ryu Senshi",
    "Warrior Dai Grepher",
    "Frontier Wiseman",
    "Exiled Force",
    "The Hunter with 7 Weapons",
    "Shadow Tamer",
    "Dragon Manipulator",
    "The A. Forces",
    "Reinforcement of the Army",
    "Array of Revealing Light",
    "The Warrior Returning Alive",
    "Ready for Intercepting",
    "A Feint Plan",
    "Tyrant Dragon",
    "Spear Dragon",
    "Spirit Ryu",
    "The Dragon Dwelling in the Cave",
    "Lizard Soldier",
    "Fiend Skull Dragon",
    "Cave Dragon",
    "Gray Wing",
    "Troop Dragon",
    "The Dragon's Bead",
    "A Wingbeat of Giant Dragon",
    "Dragon's Gunfire",
    "Stamping Destruction",
    "Super Rejuvenation",
    "Dragon's Rage",
    "Burst Breath",
    "Luster Dragon #2",
    "Emergency Provisions",
    "Keldo",
    "Dragged Down into the Grave",
    "Kaiser Glider",
    "Spell Reproduction",
    "Shrink",
    "Mudora",
    "Cestus of Dagla",
    "Virus Cannon",
    "Des Feral Imp",
    "Exchange of the Spirit",
    "Kelbek",
    "Zolga",
    "Blast Held by a Tribute",
    "Agido",
    "Silent Doom",
    "Fiber Jar",
    "Gradius' Option",
    "Maharaghi",
    "Inaba White Rabbit",
    "Yata-Garasu",
    "Susa Soldier",
    "Yamata Dragon",
    "Great Long Nose",
    "Otohime",
    "Hino-Kagu-Tsuchi",
    "Asura Priest",
    "Fushi No Tori",
    "Super Robolady",
    "Super Roboyarou",
    "Fengsheng Mirror",
    "Heart of Clear Water",
    "A Legendary Ocean",
    "Fusion Sword Murasame Blade",
    "Smoke Grenade of the Thief",
    "Spiritual Energy Settle Machine",
    "Second Coin Toss",
    "Convulsion of Nature",
    "The Secret of the Bandit",
    "After the Struggle",
    "Blast with Chain",
    "Disappear",
    "Bottomless Trap Hole",
    "Ominous Fortunetelling",
    "Nutrient Z",
    "Drop Off",
    "Fiend Comedian",
    "Last Turn",
    "Des Volstgalph",
    "Kaiser Sea Horse",
    "Vampire Lord",
    "Gora Turtle",
    "Sasuke Samurai",
    "Poison Mummy",
    "Dark Dust Spirit",
    "Royal Keeper",
    "Wandering Mummy",
    "Great Dezard",
    "Swarm of Scarabs",
    "Swarm of Locusts",
    "Giant Axe Mummy",
    "Guardian Sphinx",
    "Pyramid Turtle",
    "Dice Jar",
    "Dark Scorpion Burglars",
    "Don Zaloog",
    "Des Lacooda",
    "Fushioh Richie",
    "Cobraman Sakuzy",
    "Book of Life",
    "Book of Taiyou",
    "Book of Moon",
    "Mirage of Nightmare",
    "Call of the Mummy",
    "Timidity",
    "Pyramid Energy",
    "Tutan Mask",
    "Ordeal of a Traveler",
    "Bottomless Shifting Sand",
    "Curse of Royal",
    "Needle Ceiling",
    "Statue of the Wicked",
    "Dark Coffin",
    "Needle Wall",
    "Trap Dustshoot",
    "Reckless Greed",
    "Toon Dark Magician Girl",
    "Gilford the Lightning",
    "Exarion Universe",
    "Legendary Fiend",
    "Toon Defense",
    "Toon Table of Contents",
    "Toon Masked Sorcerer",
    "Toon Gemini Elf",
    "Toon Cannon Soldier",
    "Toon Goblin Attack Force",
    "Card of Sanctity",
    "Puppet Master",
    "Newdoria",
    "Lord Poison",
    "Blade Knight",
    "Helpoemer",
    "Hidden Soldiers",
    "Gil Garth",
    "Malevolent Catastrophe",
    "Lava Golem",
    "Relieve Monster",
    "Machine Duplication",
    "Dark Jeroid",
    "Dragon Master Knight",
    "Five-Headed Dragon",
    "Queen's Knight",
    "X-Head Cannon",
    "Enemy Controller",
    "Master Kyonshee",
    "Kabazauls",
    "Inpachi",
    "Gravekeeper's Spy",
    "Gravekeeper's Curse",
    "Gravekeeper's Guard",
    "Gravekeeper's Spear Soldier",
    "Gravekeeper's Cannonholder",
    "Gravekeeper's Assailant",
    "A Man with Wdjat",
    "Mystical Knight of Jackal",
    "A Cat of Ill Omen",
    "Yomi Ship",
    "Winged Sage Falcos",
    "An Owl of Luck",
    "Charm of Shabti",
    "Cobra Jar",
    "Spirit Reaper",
    "Nightmare Horse",
    "Reaper on the Nightmare",
    "Card Shuffle",
    "Reasoning",
    "Dark Room of Nightmare",
    "Different Dimension Capsule",
    "Necrovalley",
    "Buster Rancher",
    "Hieroglyph Lithograph",
    "Dark Snake Syndrome",
    "Terraforming",
    "Banner of Courage",
    "Metamorphosis",
    "Royal Tribute",
    "Reversal Quiz",
    "Curse of Aging",
    "Raigeki Break",
    "Disturbance Strategy",
    "Rite of Spirit",
    "Non Aggression Area",
    "D. Tribe",
    "Y-Dragon Head",
    "XY-Dragon Cannon",
    "Z-Metal Tank",
    "XYZ-Dragon Cannon",
    "Soul Rope",
    "King's Knight",
    "Jack's Knight",
    "Interdimensional Matter Transporter",
    "Goblin Zombie",
    "Drillago",
    "Lekunga",
    "Cost Down",
    "People Running About",
    "Oppressed People",
    "United Resistance",
    "Dark Blade",
    "Pitch-Dark Dragon",
    "Kiryu",
    "Decayed Commander",
    "Zombie Tiger",
    "Giant Orc",
    "Second Goblin",
    "Vampiric Orchis",
    "Des Dendle",
    "Burning Beast",
    "Freezing Beast",
    "D.D. Crazy Beast",
    "Spell Canceller",
    "Helping Robo for Combat",
    "Dimension Jar",
    "Roulette Barrel",
    "Paladin of White Dragon",
    "White Dragon Ritual",
    "Frontline Base",
    "Demotion",
    "Combination Attack",
    "Autonomous Action Unit",
    "Poison of the Old Man",
    "Dark Core",
    "Raregold Armor",
    "Kishido Spirit",
    "Tribute Doll",
    "Wave-Motion Cannon",
    "Huge Revolution",
    "Thunder of Ruler",
    "Spell Shield Type-8",
    "Meteorain",
    "Pineapple Blast",
    "Secret Barrel",
    "Formation Union",
    "Adhesion Trap Hole",
    "XZ-Tank Cannon",
    "YZ-Tank Dragon",
    "Final Attack Orders",
    "Dark Paladin",
    "Spell Absorption",
    "Diffusion Wave-Motion",
    "Fiend's Sanctuary",
    "Great Angus",
    "Aitsu",
    "Sonic Duck",
    "Luster Dragon",
    "Amazoness Paladin",
    "Amazoness Blowpiper",
    "Amazoness Tiger",
    "Skilled White Magician",
    "Skilled Dark Magician",
    "Apprentice Magician",
    "Old Vindictive Magician",
    "Chaos Command Magician",
    "Magical Marionette",
    "Breaker the Magical Warrior",
    "Magical Plant Mandragola",
    "Magical Scientist",
    "Royal Magical Library",
    "Armor Exe",
    "Tribe-Infecting Virus",
    "Des Koala",
    "Dark Scorpion - Cliff the Trap Remover",
    "Magical Merchant",
    "Koitsu",
    "Cat's Ear Tribe",
    "Ultimate Obedient Fiend",
    "Pitch-Black Power Stone",
    "Big Bang Shot",
    "Gather Your Mind",
    "Mass Driver",
    "Senri Eye",
    "Emblem of Dragon Destroyer",
    "Jar Robber",
    "Mega Ton Magical Cannon",
    "Continuous Destruction Punch",
    "Exhausting Spell",
    "Hidden Spellbook",
    "Miracle Restoring",
    "Disarmament",
    "Anti-Spell",
    "The Spell Absorbing Life",
    "Metal Reflect Slime",
    "Bowganian",
    "Magical Stone Excavation",
    "Granadora",
    "Shinato, King of a Higher Plane",
    "Dark Flare Knight",
    "Mirage Knight",
    "Berserk Dragon",
    "Exodia Necross",
    "Battle Footballer",
    "Arsenal Summoner",
    "Nin-Ken Dog",
    "Acrobat Monkey",
    "Guardian Elma",
    "Guardian Ceal",
    "Guardian Grarl",
    "Guardian Baou",
    "Guardian Kay'est",
    "Guardian Tryce",
    "Gyaku-Gire Panda",
    "Blindly Loyal Goblin",
    "Despair from the Dark",
    "Maju Garzett",
    "Fear from the Dark",
    "Dark Scorpion - Chick the Yellow",
    "D.D. Warrior Lady",
    "Thousand Needles",
    "Shinato's Ark",
    "A Deal with Dark Ruler",
    "Contract with Exodia",
    "Butterfly Dagger - Elma",
    "Shooting Star Bow - Ceal",
    "Gravity Axe - Grarl",
    "Wicked-Breaking Flamberge - Baou",
    "Rod of Silence - Kay'est",
    "Twin Swords of Flashing Light - Tryce",
    "Precious Cards from Beyond",
    "Rod of the Mind's Eye",
    "Fairy of the Spring",
    "Token Thanksgiving",
    "Non-Spellcasting Area",
    "Staunch Defender",
    "Ojama Trio",
    "Arsenal Robber",
    "Skill Drain",
    "Really Eternal Rest",
    "Soul Taker",
    "Magical Dimension",
    "Judgment of the Pharaoh",
    "Yu-Jo Friendship",
    "Unity",
    "Dark Magician Knight",
    "Knight's Title",
    "Sage's Stone",
    "Gagagigo",
    "D.D. Trainer",
    "Ojama Green",
    "Archfiend Soldier",
    "Pandemonium Watchbear",
    "Sasuke Samurai #2",
    "Dark Scorpion - Gorg the Strong",
    "Dark Scorpion - Meanae the Thorn",
    "Outstanding Dog Marron",
    "Great Maju Garzett",
    "Iron Blacksmith Kotetsu",
    "Mefist the Infernal General",
    "Vilepawn Archfiend",
    "Shadowknight Archfiend",
    "Darkbishop Archfiend",
    "Desrook Archfiend",
    "Infernalqueen Archfiend",
    "Terrorking Archfiend",
    "Skull Archfiend of Lightning",
    "Metallizing Parasite - Lunatite",
    "Tsukuyomi",
    "Legendary Flame Lord",
    "Dark Master - Zorc",
    "Incandescent Ordeal",
    "Contract with the Abyss",
    "Contract with the Dark Master",
    "Falling Down",
    "Checkmate",
    "Final Countdown",
    "Mustering of the Dark Scorpions",
    "Pandemonium",
    "Altar for Tribute",
    "Frozen Soul",
    "Battle-Scarred",
    "Dark Scorpion Combination",
    "Archfiend's Roar",
    "Dice Re-Roll",
    "Spell Vanishing",
    "Sakuretsu Armor",
    "Ray of Hope",
    "Nightmare Penguin",
    "Perfect Machine King",
    "Chiron the Mage",
    "Ojama Yellow",
    "Ojama Black",
    "Soul Tiger",
    "Big Koala",
    "Des Kangaroo",
    "Crimson Ninja",
    "Strike Ninja",
    "Gale Lizard",
    "Chopman the Desperate Outlaw",
    "Sasuke Samurai #3",
    "D.D. Scout Plane",
    "Berserk Gorilla",
    "Freed the Brave Wanderer",
    "Witch Doctor of Chaos",
    "Chaos Necromancer",
    "Chaosrider Gustaph",
    "Inferno",
    "Fenrir",
    "Gigantes",
    "Silpheed",
    "Chaos Sorcerer",
    "Gren Maju Da Eiza",
    "Black Luster Soldier - Envoy of the Beginning",
    "Fuhma Shuriken",
    "Heart of the Underdog",
    "Wild Nature's Release",
    "Ojama Delta Hurricane!!",
    "Stumbling",
    "Chaos End",
    "Chaos Greed",
    "D.D. Borderline",
    "Recycle",
    "Primal Seed",
    "Thunder Crash",
    "Dimension Distortion",
    "Reload",
    "Soul Absorption",
    "Big Burn",
    "Blasting the Ruins",
    "Cursed Seal of the Forbidden Spell",
    "Tower of Babel",
    "Spatial Collapse",
    "Chain Disappearance",
    "Zero Gravity",
    "Dark Mirror Force",
    "Energy Drain",
    "Chaos Emperor Dragon - Envoy of the End",
    "Victory Dragon",
    "Magician's Valkyria",
    "Giga Gagagigo",
    "Mad Dog of Darkness",
    "Neo Bug",
    "Sea Serpent Warrior of Darkness",
    "Terrorking Salmon",
    "Blazing Inpachi",
    "Burning Algae",
    "The Thing in the Crater",
    "Molten Zombie",
    "Dark Magician of Chaos",
    "Manticore of Darkness",
    "Stealth Bird",
    "Sacred Crane",
    "Enraged Battle Ox",
    "Don Turtle",
    "Dark Driceratops",
    "Hyper Hammerhead",
    "Black Tyranno",
    "Anti-Aircraft Flower",
    "Prickle Fairy",
    "Insect Princess",
    "Amphibious Bugroth MK-3",
    "Torpedo Fish",
    "Levia-Dragon - Daedalus",
    "Orca Mega-Fortress of Darkness",
    "Cannonball Spear Shellfish",
    "Mataza the Zapper",
    "Guardian Angel Joan",
    "Manju of the Ten Thousand Hands",
    "Getsu Fuhma",
    "Ryu Kokki",
    "Gryphon's Feather Duster",
    "Stray Lambs",
    "Smashing Ground",
    "Dimension Fusion",
    "Dedication through Light and Darkness",
    "Salvage",
    "Ultra Evolution Pill",
    "Earth Chant",
    "Jade Insect Whistle",
    "Destruction Ring",
    "Fiend's Hand Mirror",
    "Compulsory Evacuation Device",
    "A Hero Emerges",
    "Self-Destruct Button",
    "Curse of Darkness",
    "Begone, Knave!",
    "DNA Transplant",
    "Robbin' Zombie",
    "Trap Jammer",
    "Invader of Darkness",
    "Twinheaded Beast",
    "Abyss Soldier",
    "Inferno Hammer",
    "Emes the Infinity",
    "D.D. Assailant",
    "Teva",
    "Zoma the Spirit",
    "Maximum Six",
    "Dangerous Machine Type-6",
    "Sixth Sense",
    "Gogiga Gagagigo",
    "Warrior of Zera",
    "Sealmaster Meisei",
    "Mystical Shine Ball",
    "Metal Armored Bug",
    "The Agent of Judgment - Saturn",
    "The Agent of Wisdom - Mercury",
    "The Agent of Creation - Venus",
    "The Agent of Force - Mars",
    "The Unhappy Girl",
    "Soul-Absorbing Bone Tower",
    "The Kick Man",
    "Vampire Lady",
    "Rocket Jumper",
    "Avatar of The Pot",
    "Legendary Jujitsu Master",
    "KA-2 Des Scissors",
    "Needle Burrower",
    "Blowback Dragon",
    "Zaborg the Thunder Monarch",
    "Atomic Firefly",
    "Mermaid Knight",
    "Piranha Army",
    "Two Thousand Needles",
    "Disc Fighter",
    "Arcane Archer of the Forest",
    "Lady Ninja Yae",
    "Goblin King",
    "Solar Flare Dragon",
    "White Magician Pikeru",
    "Archlord Zerato",
    "Opti-Camouflage Armor",
    "Mystik Wok",
    "Burst Stream of Destruction",
    "Monster Gate",
    "The Sanctuary in the Sky",
    "Earthquake",
    "Goblin Thief",
    "Backfire",
    "Micro Ray",
    "Light of Judgment",
    "Wall of Revealing Light",
    "Solar Ray",
    "Ninjitsu Art of Transformation",
    "Beckoning Light",
    "Draining Shield",
    "Armor Break",
    "Mazera DeVille",
    "Marshmallon",
    "Doomcaliber Knight",
    "Shield Crush",
    "Return Zombie",
    "Legacy of Yata-Garasu",
    "Marshmallon Glasses",
    "Call of the Earthbound",
    "Mokey Mokey",
    "Gigobyte",
    "Kozaky",
    "Fiend Scorpion",
    "Pharaoh's Servant",
    "Pharaonic Protector",
    "Spirit of the Pharaoh",
    "Theban Nightmare",
    "Aswan Apparition",
    "Protector of the Sanctuary",
    "Nubian Guard",
    "Desertapir",
    "Sand Gambler",
    "Ghost Knight of Jackal",
    "Absorbing Kid from the Sky",
    "Elephant Statue of Blessing",
    "Elephant Statue of Disaster",
    "Spirit Caller",
    "Emissary of the Afterlife",
    "Double Coston",
    "Regenerating Mummy",
    "Night Assailant",
    "Man-Thro' Tro'",
    "King of the Swamp",
    "Emissary of the Oasis",
    "Special Hurricane",
    "Order to Charge",
    "Sword of the Soul-Eater",
    "Dust Barrier",
    "Soul Reversal",
    "Spell Economics",
    "Level Limit - Area B",
    "Enchanting Fitting Room",
    "The Law of the Normal",
    "Dark Magic Attack",
    "Delta Attacker",
    "Thousand Energy",
    "Triangle Power",
    "The Third Sarcophagus",
    "The Second Sarcophagus",
    "The First Sarcophagus",
    "Human-Wave Tactics",
    "Curse of Anubis",
    "Desert Sunlight",
    "Des Counterblow",
    "Labyrinth of Nightmare",
    "Soul Resurrection",
    "Order to Smash",
    "The End of Anubis",
    "Gandora the Dragon of Destruction",
    "Return from the Different Dimension",
    "Pyramid of Light",
    "Blue-Eyes Shining Dragon",
    "Familiar Knight",
    "Rare Metal Dragon",
    "Peten the Dark Clown",
    "Sorcerer of Dark Magic",
    "Andro Sphinx",
    "Sphinx Teleia",
    "Theinen the Great Sphinx",
    "Inferno Tempest",
    "Watapon",
    "Charcoal Inpachi",
    "Neo Aqua Madoor",
    "Skull Dog Marron",
    "Goblin Calligrapher",
    "Ultimate Insect LV1",
    "Horus the Black Flame Dragon LV4",
    "Horus the Black Flame Dragon LV6",
    "Horus the Black Flame Dragon LV8",
    "Dark Mimic LV1",
    "Dark Mimic LV3",
    "Mystic Swordsman LV2",
    "Mystic Swordsman LV4",
    "Armed Dragon LV3",
    "Armed Dragon LV5",
    "Armed Dragon LV7",
    "Horus' Servant",
    "Black Dragon's Chick",
    "Ninja Grandmaster Sasuke",
    "Rafflesia Seduction",
    "Ultimate Baseball Kid",
    "Mobius the Frost Monarch",
    "Element Dragon",
    "Element Soldier",
    "Howling Insect",
    "Masked Dragon",
    "Mind on Air",
    "Unshaven Angler",
    "The Trojan Horse",
    "Nobleman-Eater Bug",
    "Enraged Muka Muka",
    "Hade-Hane",
    "Penumbral Soldier Lady",
    "Ojama King",
    "Master of Oz",
    "Sanwitch",
    "Dark Factory of Mass Production",
    "Hammer Shot",
    "Mind Wipe",
    "Abyssal Designator",
    "Level Up!",
    "Inferno Fire Blast",
    "The Graveyard in the Fourth Dimension",
    "Two-Man Cell Battle",
    "Big Wave Small Wave",
    "Fusion Weapon",
    "Ritual Weapon",
    "Taunt",
    "Absolute End",
    "Spirit Barrier",
    "Ninjitsu Art of Decoy",
    "Enervating Mist",
    "Heavy Slump",
    "Greed",
    "Cemetary Bomb",
    "Hallowed Life Barrier",
    "The Tricky",
    "Green Gadget",
    "Stronghold the Moving Fortress",
    "Red Gadget",
    "Yellow Gadget",
    "Tricky Spell 4",
    "Blockman",
    "Silent Swordsman LV3",
    "Silent Swordsman LV5",
    "Silent Swordsman LV7",
    "Silent Magician LV4",
    "Magician's Circle",
    "Magicians Unite",
    "Silent Magician LV8",
    "Woodborg Inpachi",
    "Mighty Guard",
    "Bokoichi the Freightening Car",
    "Harpie Girl",
    "The Creator",
    "The Creator Incarnate",
    "Ultimate Insect LV3",
    "Mystic Swordsman LV6",
    "Heavy Mech Support Platform",
    "Element Magician",
    "Element Saurus",
    "Roc from the Valley of Haze",
    "Sasuke Samurai #4",
    "Harpie Lady 1",
    "Harpie Lady 2",
    "Harpie Lady 3",
    "Raging Flame Sprite",
    "Thestalos the Firestorm Monarch",
    "Eagle Eye",
    "Tactical Espionage Expert",
    "Invasion of Flames",
    "Creeping Doom Manta",
    "Pitch-Black Warwolf",
    "Mirage Dragon",
    "Gaia Soul the Combustible Collective",
    "Fox Fire",
    "B.E.S. Big Core",
    "Fusilier Dragon, the Dual-Mode Beast",
    "Dekoichi the Battlechanted Locomotive",
    "A-Team: Trap Disposal Unit",
    "Homunculus the Alchemic Being",
    "Dark Blade the Dragon Knight",
    "Mokey Mokey King",
    "Serial Spell",
    "Harpies' Hunting Ground",
    "Triangle Ecstasy Spark",
    "Necklace of Command",
    "Flint",
    "Mokey Mokey Smackdown",
    "Back to Square One",
    "Monster Reincarnation",
    "Ballista of Rampart Smashing",
    "Lighten the Load",
    "Malice Dispersion",
    "Divine Wrath",
    "Xing Zhen Hu",
    "Rare Metalmorph",
    "Mind Haxorz",
    "Fuh-Rin-Ka-Zan",
    "Chain Burst",
    "Pikeru's Circle of Enchantment",
    "Spell Purification",
    "Astral Barrier",
    "Covering Fire",
    "Castle Gate",
    "Owner's Seal",
    "Space Mambo",
    "Divine Dragon Ragnarok",
    "Chu-Ske the Mouse Fighter",
    "Insect Knight",
    "Sacred Phoenix of Nephthys",
    "Hand of Nephthys",
    "Ultimate Insect LV5",
    "Granmarg the Rock Monarch",
    "Element Valkyrie",
    "Element Doom",
    "Maji-Gire Panda",
    "Catnipped Kitty",
    "Behemoth the King of All Animals",
    "Big-Tusked Mammoth",
    "Kangaroo Champ",
    "Hyena",
    "Blade Rabbit",
    "Mecha-Dog Marron",
    "Blast Magician",
    "Gearfried the Swordmaster",
    "Armed Samurai - Ben Kei",
    "Shadowslayer",
    "Golem Sentry",
    "Abare Ushioni",
    "The Light - Hex-Sealed Fusion",
    "The Dark - Hex-Sealed Fusion",
    "The Earth - Hex-Sealed Fusion",
    "Whirlwind Prodigy",
    "Flame Ruler",
    "Firebird",
    "Rescue Cat",
    "Brain Jacker",
    "Gatling Dragon",
    "King Dragun",
    "A Feather of the Phoenix",
    "Poison Fangs",
    "Swords of Concealing Light",
    "Spiral Spear Strike",
    "Release Restraint",
    "Centrifugal Field",
    "Fulfillment of the Contract",
    "Re-Fusion",
    "The Big March of Animals",
    "Cross Counter",
    "Threatening Roar",
    "Phoenix Wing Wind Blast",
    "Good Goblin Housekeeping",
    "Beast Soul Swap",
    "Assault on GHQ",
    "D.D. Dynamite",
    "Deck Devastation Virus",
    "Elemental Burst",
    "Forced Ceasefire",
    "Vampire's Curse",
    "Union Attack",
    "Blood Sucker",
    "Overpowering Eye",
    "Red-Eyes Darkness Dragon",
    "Vampire Genesis",
    "Kaibaman",
    "Elemental HERO Avian",
    "Elemental HERO Burstinatrix",
    "Elemental HERO Clayman",
    "Elemental HERO Sparkman",
    "Winged Kuriboh",
    "Ancient Gear Golem",
    "Ancient Gear Beast",
    "Ancient Gear Soldier",
    "Millennium Scorpion",
    "Ultimate Insect LV7",
    "Lost Guardian",
    "Hieracosphinx",
    "Criosphinx",
    "Moai Interceptor Cannons",
    "Megarock Dragon",
    "Dummy Golem",
    "Grave Ohja",
    "Mine Golem",
    "Monk Fighter",
    "Master Monk",
    "Guardian Statue",
    "Medusa Worm",
    "D.D. Survivor",
    "Mid Shield Gardna",
    "White Ninja",
    "Aussa the Earth Charmer",
    "Eria the Water Charmer",
    "Hiita the Fire Charmer",
    "Wynn the Wind Charmer",
    "Batteryman AA",
    "Des Wombat",
    "King of the Skull Servants",
    "Reshef the Dark Being",
    "Elemental Mistress Doriado",
    "Elemental HERO Flame Wingman",
    "Elemental HERO Thunder Giant",
    "Gift of the Martyr",
    "Double Attack",
    "Battery Charger",
    "Kaminote Blow",
    "Doriado's Blessing",
    "Final Ritual of the Ancients",
    "Legendary Black Belt",
    "Nitro Unit",
    "Shifting Shadows",
    "Impenetrable Formation",
    "Hero Signal",
    "Pikeru's Second Sight",
    "Minefield Eruption",
    "Kozaky's Self-Destruct Button",
    "Mispolymerization",
    "Level Conversion Lab",
    "Rock Bombardment",
    "Token Feastevil",
    "Spell-Stopping Statute",
    "Royal Surrender",
    "Infernal Flame Emperor",
    "Divine Knight Ishzark",
    "Ocean Dragon Lord - Neo-Daedalus",
    "Cycroid",
    "Patroid",
    "Gyroid",
    "Steamroid",
    "Drillroid",
    "UFOroid",
    "Jetroid",
    "Cyber Dragon",
    "Wroughtweiler",
    "Elemental HERO Bubbleman",
    "Steam Gyroid",
    "UFOroid Fighter",
    "Cyber Twin Dragon",
    "Cyber End Dragon",
    "Power Bond",
    "Skyscraper",
    "Summoner Monk",
    "The Wicked Dreadroot",
    "Winged Kuriboh LV10",
    "Transcendent Wings",
    "Bubble Shuffle",
    "Spark Blaster",
    "Van'Dalgyon the Dark Dragon Lord",
    "Soitsu",
    "Mad Lobster",
    "Jerry Beans Man",
    "Cybernetic Magician",
    "Cybernetic Cyclopean",
    "Mechanical Hound",
    "Cyber Archfiend",
    "Goblin Elite Attack Force",
    "B.E.S. Crystal Core",
    "Giant Kozaky",
    "Indomitable Fighter Lei Lei",
    "Protective Soul Ailin",
    "Doitsu",
    "Des Frog",
    "T.A.D.P.O.L.E.",
    "Poison Draw Frog",
    "Tyranno Infinity",
    "Batteryman C",
    "Ebon Magician Curran",
    "D.D.M. - Different Dimension Master",
    "Fusion Recovery",
    "Miracle Fusion",
    "Dragon's Mirror",
    "System Down",
    "Des Croaking",
    "Pot of Generosity",
    "Shien's Spy",
    "Fire Darts",
    "Spiritual Earth Art - Kurogane",
    "Spiritual Water Art - Aoi",
    "Spiritual Fire Art - Kurenai",
    "Spiritual Wind Art - Miyabi",
    "A Rival Appears!",
    "Magical Explosion",
    "Rising Energy",
    "D.D. Trap Hole",
    "Conscription",
    "Dimension Wall",
    "Prepare to Strike Back",
    "The Selection",
    "Arcana Knight Joker",
    "Gilford the Legend",
    "Warrior Lady of the Wasteland",
    "Divine Sword - Phoenix Blade",
    "Elemental HERO Shining Flare Wingman",
    "Level Modulation",
    "Ojamuscle",
    "Ojamagic",
    "V-Tiger Jet",
    "Blade Skater",
    "Reborn Zombie",
    "W-Wing Catapult",
    "Elemental HERO Bladedge",
    "Elemental HERO Wildheart",
    "Hydrogeddon",
    "Oxygeddon",
    "Water Dragon",
    "Etoile Cyber",
    "VW-Tiger Catapult",
    "VWXYZ-Dragon Catapult Cannon",
    "Cyber Blader",
    "Elemental HERO Rampart Blaster",
    "Elemental HERO Tempest",
    "Elemental HERO Wildedge",
    "Chthonian Alliance",
    "Feather Shot",
    "Bonding - H2O",
    "Chthonian Polymer",
    "Chthonian Blast",
    "Hero Barrier",
    "Feather Wind",
    "Zure, Knight of Dark World",
    "B.E.S. Tetran",
    "Nanobreaker",
    "Rapid-Fire Magician",
    "Beiige, Vanguard of Dark World",
    "Broww, Huntsman of Dark World",
    "Brron, Mad King of Dark World",
    "Sillva, Warlord of Dark World",
    "Goldd, Wu-Lord of Dark World",
    "Scarr, Scout of Dark World",
    "Familiar-Possessed - Aussa",
    "Familiar-Possessed - Eria",
    "Familiar-Possessed - Hiita",
    "Familiar-Possessed - Wynn",
    "Pot of Avarice",
    "Dark World Lightning",
    "Boss Rush",
    "Gateway to Dark World",
    "The Forces of Darkness",
    "Dark Deal",
    "Simultaneous Loss",
    "Weed Out",
    "The League of Uniform Nomenclature",
    "Roll Out!",
    "Non-Fusion Area",
    "Level Limit - Area A",
    "Armed Changer",
    "Elemental HERO Necroshade",
    "Hero Ring",
    "Elemental HERO Mudballman",
    "Dark Eradicator Warlock",
    "Mythical Beast Cerberus",
    "Magical Blast",
    "Elemental HERO Steam Healer",
    "Burst Return",
    "Bubble Blaster",
    "Bubble Illusion",
    "Clay Charge",
    "Armed Dragon LV10",
    "Magical Mallet",
    "Inferno Reckless Summon",
    "Lancer Dragonute",
    "Mist Body",
    "Axe Dragonute",
    "White-Horned Dragon",
    "Uria, Lord of Searing Flames",
    "Hamon, Lord of Striking Thunder",
    "Raviel, Lord of Phantasms",
    "Elemental HERO Neo Bubbleman",
    "Hero Kid",
    "Cyber Barrier Dragon",
    "Cyber Laser Dragon",
    "Ancient Gear",
    "Hero Heart",
    "Magnet Circle LV2",
    "Ancient Gear Drill",
    "Phantasmal Martyrs",
    "Cyclone Boomerang",
    "Photon Generator Unit",
    "Ancient Gear Castle",
    "Miracle Kids",
    "Attack Reflector Unit",
    "Damage Condenser",
    "Ancient Gear Cannon",
    "Proto-Cyber Dragon",
    "Adhesive Explosive",
    "Machine King Prototype",
    "B.E.S. Covered Core",
    "D.D. Guide",
    "Chain Thrasher",
    "Disciple of the Forbidden Spell",
    "Tenkabito Shien",
    "Parasitic Ticky",
    "Gokipon",
    "Silent Insect",
    "Chainsaw Insect",
    "Anteatereatingant",
    "Saber Beetle",
    "Doom Dozer",
    "Treeborn Frog",
    "Beelze Frog",
    "Princess Pikeru",
    "Princess Curran",
    "Memory Crusher",
    "Malice Ascendant",
    "Grass Phantom",
    "Sand Moth",
    "Divine Dragon - Excelion",
    "Ruin, Queen of Oblivion",
    "Demise, King of Armageddon",
    "D.3.S. Frog",
    "Symbol of Heritage",
    "Trial of the Princesses",
    "End of the World",
    "Samsara",
    "Karma Cut",
    "Next to be Lost",
    "Generation Shift",
    "Full Salvo",
    "Success Probability 0%",
    "Option Hunter",
    "Goblin Out of the Frying Pan",
    "Malfunction",
    "The Flute of Summoning Kuriboh",
    "Elemental HERO Electrum",
    "Exxod, Master of The Guard",
    "Great Spirit",
    "Canyon",
    "Golden Homunculus",
    "Helios - The Primordial Sun",
    "Helios Duo Megistus",
    "Helios Trice Megistus",
    "Elemental HERO Neos",
    "Dandylion",
    "Insect Monster Token",
    "Kuriboh Token",
    "Sheep Token",
    "Army Ant Token",
    "Slime Token",
    "Wicked Token",
    "Poisonous Snake Token",
    "Lekunga Token",
    "Wicked Plant Token",
    "Metal Fiend Token",
    "Ojama Token",
    "Lamb Token",
    "Tricky Token",
    "Block Token",
    "Phantasm Token",
    "Phantasmal Martyr Token",
    "Fluff Token"
]

output = open('output.txt', 'w', encoding='utf8')

for card in mod:
    count = 0
    for set in data2[card]:
        try:
            date_ = parser.parse(data2[card][set]['set_chronology_tcg'][1]).date()
            if date_ <= critter:
                attribute = 'None'
                level = 0
                atk = 0
                defn = 0
                try:
                    attribute = card_info[card]['attribute']
                    level = card_info[card]['level']
                    atk = card_info[card]['atk']
                    defn = card_info[card]['def']
                    if count == 0:
                        output.write(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\tY\n')
                except:
                    if count == 0:
                        output.write(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\tY\n')
                count = count + 1
        except:
            pass
    attribute = 'None'
    level = 0
    atk = 0
    defn = 0
    try:
        attribute = card_info[card]['attribute']
        level = card_info[card]['level']
        atk = card_info[card]['atk']
        defn = card_info[card]['def']
        if count == 0:
            output.write(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\tN\n')
    except:
        if count == 0:
            output.write(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\tN\n')

# for card in eds_cards:
    # # printed = False
    # # if card not in eds_cards:
    # try:
        # attribute = 'None'
        # level = 0
        # atk = 0
        # defn = 0
        # for set in data2[card]:
            # try:
                # date_tcg = parser.parse(data2[card][set]['set_chronology_tcg'][1]).date()
                # if date_tcg <= eds:
                    # try:
                        # attribute = card_info[card]['attribute']
                        # level = card_info[card]['level']
                        # atk = card_info[card]['atk']
                        # defn = card_info[card]['def']
                        # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set + '\t' + data2[card][set]['set_chronology_tcg'][1])
                    # except:
                        # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set + '\t' + data2[card][set]['set_chronology_tcg'][1])
                    # # printed = True
            # except Exception as e:
                # # print(e)
                # pass
        # try:
            # # if printed == False:
            # for set in data2[card]['set_chronology_ocg']:
                # try:
                    # attribute = card_info[card]['attribute']
                    # level = card_info[card]['level']
                    # atk = card_info[card]['atk']
                    # defn = card_info[card]['def']
                    # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set[0] + ' (OCG)\t' + set[1].split('/')[3], months[int(set[1].split('/')[2])], set[1].split('/')[1])
                # except:
                    # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set[0] + ' (OCG)\t' + set[1].split('/')[3], months[int(set[1].split('/')[2])], set[1].split('/')[1])
        # except Exception as e:
            # # print(e)
            # pass
    # except:
        # pass

f.close()
f2.close()