import json
from dateutil import parser
from datetime import *
import traceback
import logging

f = open('YGOProDeck_Card_Info.json')
f2 = open('Set_Chronology.json')
data = json.load(f)
data2 = json.load(f2)
card_info = {}
for card_info_data in data['data']:
    card_info[card_info_data['name']] = card_info_data
yugikaiba = date(2002, 3, 29)
critter = date(2002, 6, 26)
treasure = date(2002, 9, 16)
eds = date(2002, 10, 15)
imperial = date(2002, 10, 20)
android = date(2003, 3, 1)
reaper = date(2006, 2, 18)

months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]

eds_cards = [
    "7 Colored Fish",
    "7 Completed",
    "Acid Crawler",
    "Acid Trap Hole",
    "Air Eater",
    "Archfiend Marmot of Nefariousness", # "Air Marmot of Nefariousness",
    "Akakieisu",
    "Akihiron",
    "Alligator's Sword",
    "Alligator's Sword Dragon",
    "Alpha The Magnet Warrior",
    "Amazon of the Seas",
    "Ameba",
    "Amphibious Bugroth",
    "Ancient Brain",
    "Ancient Elf",
    "Ancient Jar",
    "Ancient Lizard Warrior",
    "Ancient One of the Deep Forest",
    "Ancient Telescope",
    "Ancient Tool",
    "Ansatsu",
    "Anthrosaurus",
    "Anti Raigeki",
    "Anti-Spell Fragrance", # "Anti-Magic Fragrance",
    "Appropriate",
    "Aqua Chorus",
    "Aqua Dragon",
    "Aqua Madoor",
    "Arlownay",
    "Arma Knight",
    "Armaill",
    "Armed Ninja",
    "Armored Glass",
    "Armored Lizard",
    "Armored Rat",
    "Armored Starfish",
    "Armored Zombie",
    "Axe of Despair",
    "Axe Raider",
    "B. Dragon Jungle King",
    "Black Skull Dragon", # "B. Skull Dragon",
    "Baby Dragon",
    "Backup Soldier",
    "Banisher of the Light",
    "Barox",
    "Barrel Dragon",
    "Barrel Lily",
    "Barrel Rock",
    "Basic Insect",
    "Battle Ox",
    "Battle Steer",
    "Battle Warrior",
    "Bean Soldier",
    "Beast Fangs",
    "Beastking of the Swamps",
    "Beastly Mirror Ritual",
    "Beautiful Headhuntress",
    "Beaver Warrior",
    "Behegon",
    "Ring of Destruction", # "Bell of Destruction",
    "Beta The Magnet Warrior",
    "Bickuribox",
    "Big Eye",
    "Big Insect",
    "Big Shield Gardna",
    "Binding Chain",
    "Bio Plant",
    "Black Illusion Ritual",
    "Black Luster Ritual",
    "Black Luster Soldier",
    "Black Pendant",
    "Blackland Fire Dragon",
    "Bladefly",
    "Blast Juggler",
    "Blast Sphere",
    "Block Attack",
    "Blue Medicine",
    "Blue-Eyed Silver Zombie",
    "Blue-Eyes Toon Dragon",
    "Blue-Eyes Ultimate Dragon",
    "Blue-Eyes White Dragon",
    "Blue-Eyes White Dragon",
    "Blue-Winged Crown",
    "Boar Soldier",
    "Bolt Escargot",
    "Book of Secret Arts",
    "Bottom Dweller",
    "Bracchio-raidus",
    "Breath of Light",
    "Shine Palace", # "Bright Castle",
    "Burglar",
    "Burning Spear",
    "Buster Blader",
    "Call of Darkness", # "Call of the Dark",
    "Call of the Grave",
    "Call of the Haunted", # "Call Of The Haunted",
    "Candle of Fate",
    "Cannon Soldier",
    "Castle of Dark Illusions",
    "Castle Walls",
    "Catapult Turtle",
    "Ceasefire",
    "Celtic Guardian",
    "Celtic Guardian",
    "Ceremonial Bell",
    "Chain Destruction",
    "Chain Energy",
    "Chakra",
    "Change of Heart",
    "Charubin the Fire Knight",
    "Chorus of Sanctuary",
    "Claw Reacher",
    "Clown Zombie",
    "Cockroach Knight",
    "Cocoon of Evolution",
    "Commencement Dance",
    "Confiscation",
    "Cosmo Queen",
    "Crab Turtle",
    "Crass Clown",
    "Crawling Dragon",
    "Crawling Dragon #2",
    "Crazy Fish",
    "Crimson Sunbird",
    "Crow Goblin",
    "Crush Card Virus", # "Crush Card",
    "Curse of Dragon",
    "Curse of Fiend",
    "Curtain of the Dark Ones",
    "Cyber Commander",
    "Cyber Falcon",
    "Cyber Jar",
    "Cyber Saurus",
    "Cyber Shield",
    "Cyber Soldier",
    "Cyber-Stein",
    "Cyber-Tech Alligator",
    "D. Human",
    "Dancing Elf",
    "Dark Artist",
    "Dark Assailant",
    "Dark Chimera",
    "Dark Elf",
    "Dark Energy",
    "Dark Gray",
    "Dark Hole",
    "Dark King of the Abyss",
    "Black Magic Ritual", # "Dark Magic Ritual",
    "Dark Magician",
    "Dark Magician",
    "Dark Magician Girl",
    "Dark Rabbit",
    "Dark Sage",
    "Dark Shade",
    "Dark Witch",
    "Dark Zebra",
    "Dark-Eyes Illusionist",
    "Darkfire Dragon",
    "Darkfire Soldier #1",
    "Darkfire Soldier #2",
    "Darkness Approaches",
    "Dark-Piercing Light",
    "Darkworld Thorns",
    "Deepsea Shark",
    "Delinquent Duo",
    "De-Spell",
    "Destroyer Golem",
    "Dian Keto the Cure Master",
    "Dice Armadillo",
    "D.D. Warrior", # "Dimensional Warrior",
    "Disk Magician",
    "Dissolverock",
    "DNA Surgery",
    "Dokuroizo the Grim Reaper",
    "Dokurorider",
    "Doma The Angel of Silence",
    "Doron",
    "Dorover",
    "Dragon Capture Jar",
    "Dragon Piper",
    "Dragon Seeker",
    "Dragon Treasure",
    "Dragon Zombie",
    "Dragoness the Wicked Knight",
    "Dream Clown",
    "Driving Snow",
    "Drooling Lizard",
    "Doriado", # "Dryad",
    "Dunames Dark Witch",
    "Dungeon Worm",
    "Dust Tornado",
    "Earthshaker",
    "Eatgaboon",
    "Eldeen",
    "Electric Lizard",
    "Electric Snake",
    "Electro-Whip",
    "Elegant Egotist",
    "Elf's Light",
    "Empress Judge",
    "Enchanted Javelin",
    "Enchanting Mermaid",
    "Eradicating Aerosol",
    "Eternal Drought", # "Eternal Draught",
    "Eternal Rest",
    "Exchange",
    "Exile of the Wicked",
    "Exodia the Forbidden One",
    "Eyearmor",
    "Fairy Dragon",
    "Fairy's Hand Mirror",
    "Fairywitch",
    "Faith Bird",
    "Fake Trap",
    "Feral Imp",
    "Fiend Kraken",
    "Fiend Reflection #1",
    "Fiend Reflection #2",
    "Fiend Sword",
    "Fiend's Hand",
    "Fiend's Mirror",
    "Final Destiny",
    "Final Flame",
    "Fire Kraken",
    "Fire Reaper",
    "Firegrass",
    "Firewing Pegasus",
    "Fireyarou",
    "Fissure",
    "Flame Cerebrus",
    "Flame Champion",
    "Flame Ghost",
    "Flame Manipulator",
    "Flame Swordsman",
    "Flame Swordsman",
    "Flame Viper",
    "Flash Assailant",
    "Flower Wolf",
    "Flying Kamakiri #1",
    "Flying Kamakiri #2",
    "Follow Wind",
    "Forced Requisition",
    "Forest",
    "Fortress Whale",
    "Fortress Whale's Oath",
    "Frenzied Panda",
    "Fusion Sage",
    "Fusionist",
    "Gaia Power",
    "Gaia the Dragon Champion",
    "Gaia The Fierce Knight",
    "Gaia The Fierce Knight",
    "Gale Dogra",
    "Gamma the Magnet Warrior", # "Gamma The Magnet Warrior",
    "Ganigumo",
    "Garma Sword",
    "Garma Sword Oath",
    "Garnecia Elefantis",
    "Garoozis",
    "Garvas",
    "Gate Guardian",
    "Gatekeeper",
    "Gazelle the King of Mythical Beasts",
    "Gemini Elf",
    "Genin",
    "Germ Infection",
    "Ghoul with an Appetite",
    "Giant Flea",
    "Giant Germ",
    "Giant Mech-Soldier",
    "Giant Rat",
    "Giant Red Seasnake",
    "Giant Scorpion of the Tundra",
    "Giant Soldier of Stone",
    "Giant Trunade",
    "Giant Turtle Who Feeds on Flames",
    "Gift of The Mystical Elf",
    "Giganto",
    "Giga-Tech Wolf", # "Giga-tech Wolf",
    "Giltia the D. Knight",
    "Goblin Fan",
    "Goblin's Secret Remedy",
    "Goddess of Whim",
    "Goddess with the Third Eye",
    "Gokibore",
    "Graceful Charity",
    "Graceful Dice",
    "Grappler",
    "Gravedigger Ghoul",
    "Gravekeeper's Servant",
    "Graverobber",
    "Graveyard and the Hand of Invitation",
    "Great Bill",
    "Great Mammoth of Goldfine",
    "Great Moth",
    "Great White",
    "Green Phantom King",
    "Greenkappa",
    "Griffore",
    "Griggle",
    "Ground Attacker Bugroth",
    "Gruesome Goo",
    "Gryphon Wing",
    "Guardian of the Labyrinth",
    "Sentinel of the Seas", # "Guardian of the Sea",
    "Guardian of the Throne Room",
    "Gust",
    "Gust Fan",
    "Gyakutenno Megami",
    "Hamburger Recipe",
    "Hane-Hane",
    "Haniwa",
    "Happy Lover",
    "Hard Armor",
    "Harpie Lady",
    "Harpie Lady Sisters",
    "Sky Scout", # "Harpie's Brother",
    "Harpie's Feather Duster",
    "Harpie's Pet Dragon",
    "Heavy Storm",
    "Hercules Beetle",
    "Hero of the East",
    "Hibikime",
    "High Tide Gyojin",
    "Hinotama",
    "Hinotama Soul",
    "Hiro's Shadow Scout",
    "Hitodenchak",
    "Hitotsu-Me Giant",
    "Holograh",
    "Horn Imp",
    "Horn of Heaven",
    "Horn of Light",
    "Horn of the Unicorn",
    "Hoshiningen",
    "Hourglass of Courage",
    "Hourglass of Life",
    "House of Adhesive Tape",
    "Hungry Burger",
    "Hunter Spider",
    "Hyo",
    "Hyosube",
    "Hyozanryu",
    "Ice Water",
    "Ill Witch",
    "Illusionist Faceless Mage",
    "Imperial Order",
    "Insect Armor with Laser Cannon",
    "Insect Queen",
    "Insect Soldiers of the Sky",
    "Inspection",
    "Invader from Another Dimension",
    "Invader of the Throne",
    "Invigoration",
    "Javelin Beetle",
    "Javelin Beetle Pact",
    "Jellyfish",
    "Jigen Bakudan",
    "Jinzo",
    "Jinzo #7",
    "Jirai Gumo",
    "Judge Man",
    "Just Desserts",
    "Kagemusha of the Blue Flame",
    "Kageningen",
    "Kairyu-Shin",
    "Kaiser Dragon",
    "Kamakiriman",
    "Kaminari Attack",
    "Thunder Kid", # "Kaminarikozou",
    "Kamionwizard",
    "Kanan the Swordmistress",
    "Kanikabuto",
    "Karate Man",
    "Karbonala Warrior",
    "Kattapillar",
    "Kazejin",
    "Key Mace #2",
    "Killer Needle",
    "King Fog",
    "King of Yamimakai",
    "Kiseitai",
    "Kojikocy",
    "Kotodama",
    "Koumori Dragon",
    "Krokodilus",
    "Kumootoko",
    "Kunai with Chain",
    "Kurama",
    "Kuriboh",
    "Kuwagata α", # "Kuwagata a",
    "Kwagar Hercules",
    "La Jinn the Mystical Genie of the Lamp",
    "Labyrinth Tank",
    "Labyrinth Wall",
    "Lady of Faith",
    "LaLa Li-oon",
    "Larvae Moth",
    "Larvas",
    "Laser Cannon Armor",
    "Last Day of Witch",
    "Last Will",
    "Laughing Flower",
    "Launcher Spider",
    "Launcher Spider",
    "Lava Battleguard",
    "Left Arm of the Forbidden One",
    "Left Leg of the Forbidden One",
    "Legendary Sword",
    "Leghul",
    "Leogun",
    "Lesser Dragon",
    "Light of Intervention",
    "Lightforce Sword",
    "Liquid Beast",
    "Little Chimera",
    "Little D",
    "Lord of D.",
    "Lord of the Lamp",
    "Lord of Zemia",
    "Luminous Spark",
    "Lunar Queen Elzaim",
    "Mabarrel",
    "Machine Conversion Factory",
    "Machine King",
    "Magic Jammer",
    "Magical Thorn", # "Magic Thorn",
    "Magical Ghost",
    "Magical Hats",
    "Magical Labyrinth",
    "Magical Arm Shield", # "Magic-Arm Shield",
    "Magician of Black Chaos",
    "Magician of Faith",
    "Maha Vailo",
    "Maiden of the Moonlight",
    "Major Riot",
    "Malevolent Nuzzler",
    "Mammoth Graveyard",
    "Man Eater",
    "Man-Eater Bug",
    "Man-Eating Black Shark", # "Man-eating Black Shark",
    "Man-Eating Plant",
    "Man-Eating Treasure Chest",
    "Manga Ryu-Ran",
    "Marine Beast",
    "Masaki the Legendary Swordsman",
    "Mask of Darkness",
    "Masked Sorcerer",
    "Master & Expert",
    "Mavelus",
    "Mechanical Snail",
    "Karakuri Spider", # "Mechanical Spider",
    "Mechanicalchaser",
    "Meda Bat",
    "Mega Thunderball",
    "Megamorph",
    "Megazowler",
    "Meotoko",
    "Mesmeric Control",
    "Messenger of Peace",
    "Metal Detector",
    "Metal Dragon",
    "Metal Fish",
    "Metal Guardian",
    "Metalmorph",
    "Metalzoa",
    "Meteor Black Dragon", # "Meteor B. Dragon",
    "Meteor Dragon",
    "Mikazukinoyaiba",
    "Millennium Golem",
    "Millennium Shield",
    "Milus Radiant",
    "Minar",
    "Minomushi Warrior",
    "Mirror Force",
    "Mirror Wall",
    "Misairuzame",
    "Molten Destruction",
    "Monster Egg",
    "Monster Eye",
    "Monster Reborn",
    "Monster Tamer",
    "Monstrous Bird",
    "Moon Envoy",
    "Mooyan Curry",
    "Morinphen",
    "Morphing Jar",
    "Morphing Jar #2",
    "Mother Grizzly",
    "Mountain",
    "Mountain Warrior",
    "Mr. Volcano",
    "Muka Muka",
    "Mushroom Man",
    "Mushroom Man #2",
    "Musician King",
    "M-Warrior #1",
    "M-Warrior #2",
    "Mysterious Puppeteer",
    "Mystic Horseman",
    "Mystic Lamp",
    "Mystic Plasma Zone",
    "Mystic Probe",
    "Mystic Tomato",
    "Mystical Capture Chain",
    "Mystical Elf",
    "Mystical Moon",
    "Mystical Sand",
    "Mystical Sheep #1",
    "Mystical Sheep #2",
    "Mystical Space Typhoon",
    "Needle Ball",
    "Needle Worm",
    "Negate Attack",
    "Nekogal #1",
    "Nekogal #2",
    "Nemuriko",
    "Neo the Magic Swordsman",
    "Nimble Momonga",
    "Niwatori",
    "Nobleman of Crossout",
    "Nobleman of Extermination",
    "Novox's Prayer",
    "Numinous Healer",
    "Octoberser",
    "Ocubeam",
    "Ogre of the Black Shadow",
    "One-Eyed Shield Dragon",
    "Ooguchi",
    "Ookazi",
    "Orion the Battle King",
    "Oscillo Hero",
    "Wattkid", # "Oscillo Hero #2",
    "Painful Choice",
    "Pale Beast",
    "Panther Warrior",
    "Paralyzing Potion",
    "Parasite Paracide",
    "Parrot Dragon",
    "Patrol Robo",
    "Peacock",
    "Pendulum Machine",
    "Pendulum Machine",
    "Penguin Knight",
    "Penguin Soldier",
    "Perfectly Ultimate Great Moth",
    "Performance of Sword",
    "Petit Angel",
    "Petit Dragon",
    "Petit Moth",
    "Polymerization",
    "Polymerization",
    "Pot of Greed",
    "Power of Kaishin",
    "Pragtical",
    "Premature Burial",
    "Prevent Rat",
    "Princess of Tsurugi",
    "Prisman",
    "Prohibition",
    "Protector of the Throne",
    "Psychic Kappa",
    "Pumpking the King of Ghosts",
    "Punished Eagle",
    "Queen Bird",
    "Queen of Autumn Leaves",
    "Queen's Double",
    "Rabid Horseman",
    "Raigeki",
    "Raimei",
    "Rainbow Flower",
    "Raise Body Heat",
    "Rare Fish",
    "Ray & Temperature",
    "Reaper of the Cards",
    "Red Archery Girl",
    "Red Medicine",
    "Red-Eyes Black Dragon", # "Red-Eyes B. Dragon",
    "Red-Eyes Black Metal Dragon",
    "Reinforcements",
    "Relinquished",
    "Remove Trap",
    "Respect Play",
    "Restructer Revolution",
    "Resurrection of Chakra",
    "Reverse Trap",
    "Revival of Dokurorider",
    "Rhaimundos of the Red Sword",
    "Right Arm of the Forbidden One",
    "Right Leg of the Forbidden One",
    "Ring of Magnetism",
    "Riryoku",
    "Rising Air Current",
    "Roaring Ocean Snake",
    "Robbin' Goblin",
    "Rock Ogre Grotto #1",
    "Rogue Doll",
    "Root Water",
    "Rose Spectre of Dunn",
    "Royal Decree",
    "Royal Guard",
    "Rude Kaiser",
    "Rush Recklessly",
    "Ryu-Kishin",
    "Ryu-Kishin Powered",
    "Ryu-Ran",
    "Sword Slasher", # "Saber Slasher",
    "Saggi the Dark Clown",
    "Salamandra",
    "Sand Stone",
    "Sanga of the Thunder",
    "Sangan",
    "Sea Kamen",
    "Sea King Dragon",
    "Seal of the Ancients",
    "Sebek's Blessing",
    "Sectarian of Secrets",
    "Seiyaryu",
    "Sengenjin",
    "Senju of the Thousand Hands",
    "Serpent Night Dragon",
    "Seven Tools of the Bandit",
    "Shadow Ghoul",
    "Shadow Specter",
    "Share the Pain",
    "Shield & Sword",
    "Shining Angel", # "Shining Fairy",
    "Shovel Crusher",
    "Silver Bow and Arrow",
    "Silver Fang",
    "Sinister Serpent",
    "Skelengel",
    "Skelgon",
    "Skull Dice",
    "Skull Guardian",
    "Skull Knight",
    "Skull Red Bird",
    "Skull Servant",
    "Skull Stalker",
    "Skullbird",
    "Sleeping Lion",
    "Slot Machine",
    "Snake Fang",
    "Snakeyashi",
    "Snatch Steal",
    "Sogen",
    "Solemn Judgment",
    "Solitude",
    "Solomon's Lawbook",
    "Sonic Bird",
    "Sonic Maid",
    "Soul Hunter",
    "Soul of the Pure",
    "Soul Release",
    "Sparks",
    "Spear Cretin",
    "Spellbinding Circle",
    "Spike Seadra",
    "Spirit of the Books",
    "Spirit of the Harp",
    "Acid Rain", # "Stain Storm",
    "Star Boy",
    "Steel Ogre Grotto #1",
    "Steel Ogre Grotto #2",
    "Steel Scorpion",
    "Steel Shell",
    "Stim-Pack",
    "Stone Armadiller",
    "Stone Ogre Grotto",
    "Stop Defense",
    "Stuffed Animal",
    "Succubus Knight",
    "Suijin",
    "Summoned Skull",
    "Super War-Lion",
    "Supporter in the Shadows",
    "Swamp Battleguard",
    "Sword Arm of Dragon",
    "Sword of Dark Destruction",
    "Sword of Deep-Seated",
    "Sword of Dragon's Soul",
    "Swords of Revealing Light",
    "Swordsman from a Distant Land", # "Swordsman from a Foreign Land",
    "Swordstalker",
    "Tailor of the Fickle",
    "Tainted Wisdom",
    "Takriminos",
    "Takuhee",
    "Tao the Chanter",
    "Temple of Skulls",
    "Tenderness",
    "Terra the Terrible",
    "The 13th Grave",
    "The Bewitching Phantom Thief",
    "The Bistro Butcher",
    "The Cheerful Coffin",
    "The Drdek",
    "The Eye of Truth",
    "The Flute of Summoning Dragon",
    "The Forceful Sentry",
    "The Furious Sea King",
    "The Immortal of Thunder",
    "The Inexperienced Spy",
    "The Little Swordsman of Aile",
    "The Regulation of Tribe",
    "The Reliable Guardian",
    "The Shallow Grave",
    "The Snake Hair",
    "The Stern Mystic",
    "The Thing That Hides in the Mud",
    "The Unhappy Maiden",
    "The Wandering Doomed",
    "The Wicked Worm Beast",
    "Thousand Dragon",
    "Thousand Dragon",
    "Three-Headed Geedo",
    "Three-Legged Zombies",
    "Thunder Dragon",
    "Tiger Axe",
    "Tiger Axe",
    "Time Machine",
    "Time Seal",
    "Time Wizard",
    "Toad Master",
    "Togex",
    "Toll",
    "Tomozaurus",
    "Tongyo",
    "Toon Alligator",
    "Toon Mermaid",
    "Toon Summoned Skull",
    "Toon World",
    "Torike",
    "Total Defense Shogun",
    "Trakodon", # "Trakadon",
    "Trap Hole",
    "Trap Master",
    "Tremendous Fire",
    "Trent",
    "Trial of Nightmare",
    "Tribute to the Doomed", # "Tribute to The Doomed",
    "Tri-Horned Dragon",
    "Tripwire Beast",
    "Turtle Oath",
    "Turtle Tiger",
    "Twin Long Rods #2",
    "Twin-Headed Fire Dragon",
    "Twin-Headed Thunder Dragon",
    "Two-Headed King Rex",
    "Two-Mouth Darkruler",
    "Two-Pronged Attack",
    "Tyhone",
    "Tyhone #2",
    "UFO Turtle",
    "Ultimate Offering",
    "Umi",
    "Umiiruka",
    "Unknown Warrior of Fiend",
    "Upstart Goblin",
    "Uraby",
    "Ushi Oni",
    "Valkyrion the Magna Warrior",
    "Vermillion Sparrow",
    "Versago the Destroyer",
    "Vile Germs",
    "Violent Rain",
    "Violet Crystal",
    "Vishwar Randi",
    "Vorse Raider",
    "Waboku",
    "Wall of Illusion",
    "Wall Shadow",
    "War-Lion Ritual",
    "Warrior Elimination",
    "Warrior of Tradition",
    "Wasteland",
    "Water Element",
    "Water Girl",
    "Water Magician",
    "Water Omotics",
    "Waterdragon Fairy",
    "Weather Control",
    "Weather Report",
    "Whiptail Crow",
    "White Hole",
    "White Magical Hat",
    "Archfiend Mirror", # "Wicked Mirror",
    "Widespread Ruin",
    "Windstorm of Etaqua",
    "Wing Egg Elf",
    "Winged Cleaver",
    "Winged Dragon, Guardian of the Fortress #1", # "Winged Dragon,Guardian of the Fortress #1",
    "Wings of Wicked Flame",
    "Witch of the Black Forest",
    "Witch's Apprentice",
    "Witty Phantom",
    "Wodan the Resident of the Forest",
    "Wood Remains",
    "World Suppression",
    "Wow Warrior",
    "Wretched Ghost of the Attic",
    "Yado Karu",
    "Yaiba Robo",
    "Yamatano Dragon Scroll",
    "Yami",
    "Yaranzo",
    "Zanki",
    "Zera Ritual",
    "Zera the Mant", # "Zera The Mant",
    "Zoa",
    "Zombie Warrior",
    "Zone Eater",
    # "The Monarchy",
    # "Set Sail for the Kingdom",
    # "Glory of the King's Hand",
    "Obelisk the Tormentor",
    "Slifer the Sky Dragon",
    "The Winged Dragon of Ra",
    "Insect Monster Token"
]

um06_cards = [
    "30,000-Year White Turtle",
    "Akihiron",
    "Ally Mind",
    "Ancient Tool",
    "Ansatsu",
    "Battle Steer",
    "Beautiful Beast Trainer",
    "Bolt Escargot",
    "Crawling Dragon",
    "Crow Goblin",
    "Cyber Soldier",
    "Dark Chimera",
    "Dark Witch",
    "Dice Armadillo",
    "Doma The Angel of Silence",
    "Dungeon Worm",
    "Emperor of the Land and Sea",
    "Flame Champion",
    "Garoozis",
    "Gatekeeper",
    "Giant Turtle Who Feeds on Flames",
    "Giganto",
    "Hercules Beetle",
    "Hunter Spider",
    "Ill Witch",
    "Kairyu-Shin",
    "Kuwagata α",
    "LaMoon",
    "Leo Wizard",
    "Leogun",
    "Mabarrel",
    "Machine Attacker",
    "Mech Bass",
    "Megasonic Eye",
    "Metal Fish",
    "Metal Guardian",
    "Misairuzame",
    "Monster Tamer",
    "Morinphen",
    "Octoberser",
    "Orion the Battle King",
    "Parrot Dragon",
    "Peacock",
    "Queen Bird",
    "Queen of Autumn Leaves",
    "Rainbow Marine Mermaid",
    "Rock Spirit",
    "Rude Kaiser",
    "Sand Stone",
    "Seiyaryu",
    "Shapesnatch",
    "Spike Seadra",
    "Spikebot",
    "Spirit of the Mountain",
    "Spirit of the Winds",
    "Stone Ogre Grotto",
    "Succubus Knight",
    "Sword Slasher",
    "Tatsunootoshigo",
    "Togex",
    "Trent",
    "Wing Eagle",
    "Winged Egg of New Life",
    "Yamadron",
    "Zanki",
    "8-Claws Scorpion",
    "Dragon Piper",
    "Grave Protector",
    "Gravekeeper's Chief",
    "Great Phantom Thief",
    "Legacy Hunter",
    "Malice Doll of Demise",
    "Skull Knight #2",
    "Ante",
    "Archfiend's Oath",
    "Beast Fangs",
    "Book of Secret Arts",
    "Burning Spear",
    "D.D. Designator",
    "Dark Designator",
    "Dark Energy",
    "Darkness Approaches",
    "Double Spell",
    "Dragon Treasure",
    "Electro-Whip",
    "Elf's Light",
    "Follow Wind",
    "Gust Fan",
    "Invigoration",
    "Kaiser Colosseum",
    "Laser Cannon Armor",
    "Legendary Sword",
    "Machine Conversion Factory",
    "My Body as a Shield",
    "Mystical Moon",
    "Power of Kaishin",
    "Prohibition",
    "Question",
    "Raise Body Heat",
    "Secret Pass to the Treasures",
    "Silver Bow and Arrow",
    "Spirit Elimination",
    "Spring of Rebirth",
    "Steel Shell",
    "Sword of Dark Destruction",
    "The Puppet Magic of Dark Ruler",
    "Vile Germs",
    "Violet Crystal",
    "Barrel Behind the Door",
    "Grave Lure",
    "Mind Crush",
    "Null and Void",
    "Penalty Game!",
    "Pharaoh's Treasure",
    "Pole Position",
    "Trap of Board Eraser",
    "Kwagar Hercules"
]

imperial_cards = [
    "4-Starred Ladybug of Doom",
    "7 Colored Fish",
    "7 Completed",
    "Acid Trap Hole",
    "Ameba",
    "Ancient Brain",
    "Ancient Elf",
    "Ancient Lizard Warrior",
    "Ancient One of the Deep Forest",
    "Ancient Telescope",
    "Ansatsu",
    "Appropriate",
    "Aqua Madoor",
    "Armaill",
    "Armed Ninja",
    "Armored Glass",
    "Armored Lizard",
    "Armored Starfish",
    "Armored Zombie",
    "Attack and Receive",
    "Axe of Despair",
    "Axe Raider",
    "Baby Dragon",
    "Backup Soldier",
    "Banisher of the Light",
    "Baron of the Fiend Sword",
    "Barrel Dragon",
    "Basic Insect",
    "Battle Ox",
    "Battle Steer",
    "Bean Soldier",
    "Beast Fangs",
    "Beast of Talwar",
    "Beastking of the Swamps",
    "Beautiful Headhuntress",
    "Beaver Warrior",
    "Bickuribox",
    "Big Eye",
    "Bite Shoes",
    "Black Illusion Ritual",
    "Black Pendant",
    "Black Skull Dragon",
    "Blackland Fire Dragon",
    "Bladefly",
    "Blast Juggler",
    "Block Attack",
    "Blue Medicine",
    "Blue-Eyes Toon Dragon",
    "Blue-Eyes White Dragon",
    "Blue-Winged Crown",
    "Boar Soldier",
    "Bombardment Beetle",
    "Book of Secret Arts",
    "Bottom Dweller",
    "Bubonic Vermin",
    "Burning Land",
    "Burning Spear",
    "Buster Blader",
    "Call of the Grave",
    "Call of the Haunted",
    "Cannon Soldier",
    "Card Destruction",
    "Castle of Dark Illusions",
    "Castle Walls",
    "Catapult Turtle",
    "Ceasefire",
    "Celtic Guardian",
    "Ceremonial Bell",
    "Chain Destruction",
    "Chain Energy",
    "Change of Heart",
    "Charubin the Fire Knight",
    "Chorus of Sanctuary",
    "Claw Reacher",
    "Cockroach Knight",
    "Cocoon of Evolution",
    "Cold Wave",
    "Commencement Dance",
    "Confiscation",
    "Corroding Shark",
    "Crab Turtle",
    "Crass Clown",
    "Crawling Dragon",
    "Crawling Dragon #2",
    "Curse of Dragon",
    "Curse of Fiend",
    "Cyber Falcon",
    "Cyber Jar",
    "Cyber Saurus",
    "Cyber Soldier of Darkworld",
    "D. Human",
    "Dancing Elf",
    "Dark Assailant",
    "Dark Bat",
    "Dark Elf",
    "Dark Energy",
    "Dark Gray",
    "Dark Hole",
    "Dark King of the Abyss",
    "Dark Magician",
    "Dark Titan of Terror",
    "Dark Witch",
    "Dark Zebra",
    "Darkfire Dragon",
    "Darkfire Soldier #1",
    "Darkfire Soldier #2",
    "Darkness Approaches",
    "Darkworld Thorns",
    "De-Spell",
    "Deepsea Shark",
    "Deepsea Warrior",
    "Delinquent Duo",
    "Destroyer Golem",
    "Dharma Cannon",
    "Dian Keto the Cure Master",
    "Dimensionhole",
    "Disk Magician",
    "Dissolverock",
    "DNA Surgery",
    "Dokurorider",
    "Dokuroyaiba",
    "Doma The Angel of Silence",
    "Dragon Capture Jar",
    "Dragon Piper",
    "Dragon Seeker",
    "Dragon Treasure",
    "Dragon Zombie",
    "Dragoness the Wicked Knight",
    "Dream Clown",
    "Drill Bug",
    "Driving Snow",
    "Drooling Lizard",
    "Dust Tornado",
    "Earthshaker",
    "Eatgaboon",
    "Electric Lizard",
    "Electric Snake",
    "Electro-Whip",
    "Elegant Egotist",
    "Elf's Light",
    "Empress Judge",
    "Enchanted Javelin",
    "Enchanting Mermaid",
    "Eternal Rest",
    "Exchange",
    "Exile of the Wicked",
    "Exodia the Forbidden One",
    "Fairy Meteor Crush",
    "Fairy's Hand Mirror",
    "Faith Bird",
    "Fake Trap",
    "Feral Imp",
    "Fiend Reflection #2",
    "Final Destiny",
    "Final Flame",
    "Fire Kraken",
    "Firegrass",
    "Fireyarou",
    "Fissure",
    "Flame Cerebrus",
    "Flame Champion",
    "Flame Ghost",
    "Flame Manipulator",
    "Flame Swordsman",
    "Flash Assailant",
    "Flower Wolf",
    "Flying Kamakiri #1",
    "Flying Kamakiri #2",
    "Follow Wind",
    "Forced Requisition",
    "Forest",
    "Frenzied Panda",
    "Fusionist",
    "Gaia Power",
    "Gaia the Dragon Champion",
    "Gaia The Fierce Knight",
    "Gamble",
    "Garnecia Elefantis",
    "Garoozis",
    "Gate Guardian",
    "Gazelle the King of Mythical Beasts",
    "Gearfried the Iron Knight",
    "Germ Infection",
    "Giant Flea",
    "Giant Germ",
    "Giant Rat",
    "Giant Red Seasnake",
    "Giant Soldier of Stone",
    "Giant Trunade",
    "Giant Turtle Who Feeds on Flames",
    "Gift of The Mystical Elf",
    "Giga-Tech Wolf",
    "Giltia the D. Knight",
    "Girochin Kuwagata",
    "Goblin Attack Force",
    "Goblin's Secret Remedy",
    "Goddess with the Third Eye",
    "Graceful Dice",
    "Gradius",
    "Gravedigger Ghoul",
    "Gravekeeper's Servant",
    "Graverobber",
    "Gravity Bind",
    "Great Moth",
    "Great White",
    "Green Phantom King",
    "Griggle",
    "Ground Attacker Bugroth",
    "Ground Collapse",
    "Guardian of the Labyrinth",
    "Guardian of the Throne Room",
    "Gust",
    "Gust Fan",
    "Gyakutenno Megami",
    "Hamburger Recipe",
    "Hane-Hane",
    "Hard Armor",
    "Harpie Lady",
    "Harpie Lady Sisters",
    "Hayabusa Knight",
    "Heavy Storm",
    "Hercules Beetle",
    "Hibikime",
    "High Tide Gyojin",
    "Hinotama",
    "Hinotama Soul",
    "Hiro's Shadow Scout",
    "Hitotsu-Me Giant",
    "Horn of Heaven",
    "Horn of Light",
    "Horn of the Unicorn",
    "Hoshiningen",
    "House of Adhesive Tape",
    "Hungry Burger",
    "Hunter Spider",
    "Hyosube",
    "Hyozanryu",
    "Illusionist Faceless Mage",
    "Imperial Order",
    "Infinite Dismissal",
    "Insect Barrier",
    "Insect Imitation",
    "Insect Soldiers of the Sky",
    "Inspection",
    "Invader of the Throne",
    "Invigoration",
    "Invitation to a Dark Sleep",
    "Island Turtle",
    "Jellyfish",
    "Jigen Bakudan",
    "Jinzo",
    "Jinzo #7",
    "Jirai Gumo",
    "Judge Man",
    "Just Desserts",
    "Kagemusha of the Blue Flame",
    "Kaminari Attack",
    "Karate Man",
    "Karbonala Warrior",
    "Kazejin",
    "Killer Needle",
    "King Fog",
    "King of Yamimakai",
    "Kiseitai",
    "Kojikocy",
    "Kotodama",
    "Koumori Dragon",
    "Kumootoko",
    "Kurama",
    "Kuriboh",
    "Kwagar Hercules",
    "La Jinn the Mystical Genie of the Lamp",
    "Labyrinth Tank",
    "Labyrinth Wall",
    "Lady of Faith",
    "Larvae Moth",
    "Larvas",
    "Laser Cannon Armor",
    "Last Will",
    "Launcher Spider",
    "Lava Battleguard",
    "Left Arm of the Forbidden One",
    "Left Leg of the Forbidden One",
    "Legendary Sword",
    "Leghul",
    "Leogun",
    "Lesser Dragon",
    "Light of Intervention",
    "Lightforce Sword",
    "Limiter Removal",
    "Liquid Beast",
    "Little Chimera",
    "Lord of D.",
    "Luminous Spark",
    "M-Warrior #1",
    "M-Warrior #2",
    "Machine Conversion Factory",
    "Mad Sword Beast",
    "Magic Drain",
    "Magic Jammer",
    "Magical Ghost",
    "Magical Hats",
    "Magical Labyrinth",
    "Magician of Faith",
    "Maha Vailo",
    "Maiden of the Moonlight",
    "Major Riot",
    "Malevolent Nuzzler",
    "Mammoth Graveyard",
    "Man Eater",
    "Man-Eater Bug",
    "Man-Eating Treasure Chest",
    "Manga Ryu-Ran",
    "Masaki the Legendary Swordsman",
    "Mask of Darkness",
    "Masked Sorcerer",
    "Master & Expert",
    "Mechanical Snail",
    "Mechanicalchaser",
    "Meda Bat",
    "Mega Thunderball",
    "Megamorph",
    "Messenger of Peace",
    "Metal Detector",
    "Metal Dragon",
    "Metal Fish",
    "Michizure",
    "Mikazukinoyaiba",
    "Milus Radiant",
    "Minar",
    "Minor Goblin Official",
    "Mirror Force",
    "Mirror Wall",
    "Misairuzame",
    "Molten Destruction",
    "Monster Egg",
    "Monster Reborn",
    "Monster Recovery",
    "Morinphen",
    "Morphing Jar",
    "Morphing Jar #2",
    "Mother Grizzly",
    "Mountain",
    "Mr. Volcano",
    "Muka Muka",
    "Mushroom Man #2",
    "Musician King",
    "Mysterious Puppeteer",
    "Mystic Clown",
    "Mystic Horseman",
    "Mystic Lamp",
    "Mystic Plasma Zone",
    "Mystic Probe",
    "Mystic Tomato",
    "Mystical Elf",
    "Mystical Moon",
    "Mystical Sheep #1",
    "Mystical Sheep #2",
    "Mystical Space Typhoon",
    "Nemuriko",
    "Neo the Magic Swordsman",
    "Nimble Momonga",
    "Niwatori",
    "Nobleman of Crossout",
    "Nobleman of Extermination",
    "Novox's Prayer",
    "Numinous Healer",
    "Octoberser",
    "Ocubeam",
    "Ogre of the Black Shadow",
    "One-Eyed Shield Dragon",
    "Oni Tank T-34",
    "Ooguchi",
    "Ookazi",
    "Oscillo Hero",
    "Overdrive",
    "Painful Choice",
    "Pale Beast",
    "Paralyzing Potion",
    "Parasite Paracide",
    "Parrot Dragon",
    "Patrol Robo",
    "Peacock",
    "Penguin Knight",
    "Performance of Sword",
    "Petit Angel",
    "Petit Dragon",
    "Petit Moth",
    "Polymerization",
    "Pot of Greed",
    "Power of Kaishin",
    "Premature Burial",
    "Prevent Rat",
    "Princess of Tsurugi",
    "Prohibition",
    "Protector of the Throne",
    "Psychic Kappa",
    "Pumpking the King of Ghosts",
    "Punished Eagle",
    "Queen Bird",
    "Queen of Autumn Leaves",
    "Queen's Double",
    "Rabid Horseman",
    "Raigeki",
    "Raimei",
    "Rain of Mercy",
    "Rainbow Flower",
    "Raise Body Heat",
    "Ray & Temperature",
    "Reaper of the Cards",
    "Red Archery Girl",
    "Red Medicine",
    "Red-Eyes Black Dragon",
    "Reinforcements",
    "Relinquished",
    "Remove Trap",
    "Respect Play",
    "Reverse Trap",
    "Revival of Dokurorider",
    "Right Arm of the Forbidden One",
    "Right Leg of the Forbidden One",
    "Ring of Magnetism",
    "Rising Air Current",
    "Roaring Ocean Snake",
    "Robbin' Goblin",
    "Rock Ogre Grotto #1",
    "Rogue Doll",
    "Root Water",
    "Rude Kaiser",
    "Rush Recklessly",
    "Ryu-Kishin",
    "Ryu-Kishin Powered",
    "Ryu-Ran",
    "Saggi the Dark Clown",
    "Salamandra",
    "Sand Stone",
    "Sanga of the Thunder",
    "Sangan",
    "Science Soldier",
    "Seiyaryu",
    "Senju of the Thousand Hands",
    "Serpent Night Dragon",
    "Seven Tools of the Bandit",
    "Shadow Ghoul",
    "Shadow of Eyes",
    "Share the Pain",
    "Shield & Sword",
    "Shift",
    "Shining Angel",
    "Shining Friendship",
    "Silver Bow and Arrow",
    "Silver Fang",
    "Skull Dice",
    "Skull Guardian",
    "Skull Invitation",
    "Skull Knight",
    "Skull Mariner",
    "Skull Red Bird",
    "Skull Servant",
    "Sky Dragon",
    "Sky Scout",
    "Slot Machine",
    "Snake Fang",
    "Snatch Steal",
    "Sogen",
    "Solemn Judgment",
    "Solemn Wishes",
    "Solomon's Lawbook",
    "Sonic Bird",
    "Sonic Maid",
    "Sorcerer of the Doomed",
    "Soul Exchange",
    "Soul of the Pure",
    "Soul Release",
    "Souls of the Forgotten",
    "Sparks",
    "Spear Cretin",
    "Spellbinding Circle",
    "Spike Seadra",
    "Spikebot",
    "Spirit of the Books",
    "Spirit of the Harp",
    "Star Boy",
    "Steel Ogre Grotto #1",
    "Steel Ogre Grotto #2",
    "Steel Scorpion",
    "Steel Shell",
    "Stim-Pack",
    "Stone Ogre Grotto",
    "Stop Defense",
    "Stuffed Animal",
    "Succubus Knight",
    "Suijin",
    "Summoned Skull",
    "Swamp Battleguard",
    "Sword Hunter",
    "Sword of Dark Destruction",
    "Sword of Deep-Seated",
    "Swords of Revealing Light",
    "Swordstalker",
    "Tailor of the Fickle",
    "Tainted Wisdom",
    "Takuhee",
    "Terra the Terrible",
    "The 13th Grave",
    "The All-Seeing White Tiger",
    "The Bistro Butcher",
    "The Cheerful Coffin",
    "The Eye of Truth",
    "The Fiend Megacyber",
    "The Flute of Summoning Dragon",
    "The Forceful Sentry",
    "The Furious Sea King",
    "The Immortal of Thunder",
    "The Inexperienced Spy",
    "The Judgement Hand",
    "The Legendary Fisherman",
    "The Little Swordsman of Aile",
    "The Regulation of Tribe",
    "The Reliable Guardian",
    "The Shallow Grave",
    "The Statue of Easter Island",
    "The Stern Mystic",
    "The Unhappy Maiden",
    "The Wicked Worm Beast",
    "Thousand Dragon",
    "Thousand-Eyes Idol",
    "Thousand-Eyes Restrict",
    "Three-Headed Geedo",
    "Thunder Dragon",
    "Tiger Axe",
    "Time Seal",
    "Time Wizard",
    "Toll",
    "Tongyo",
    "Toon Mermaid",
    "Toon Summoned Skull",
    "Toon World",
    "Trap Hole",
    "Trap Master",
    "Tremendous Fire",
    "Trent",
    "Tri-Horned Dragon",
    "Trial of Nightmare",
    "Tribute to the Doomed",
    "Tripwire Beast",
    "Turtle Oath",
    "Turtle Tiger",
    "Turu-Purun",
    "Twin Long Rods #2",
    "Twin-Headed Fire Dragon",
    "Twin-Headed Thunder Dragon",
    "Two-Headed King Rex",
    "Two-Mouth Darkruler",
    "Two-Pronged Attack",
    "Tyhone",
    "Tyhone #2",
    "Type Zero Magic Crusher",
    "UFO Turtle",
    "Ultimate Offering",
    "Umi",
    "Umiiruka",
    "Unknown Warrior of Fiend",
    "Upstart Goblin",
    "Uraby",
    "Vampire Baby",
    "Versago the Destroyer",
    "Vile Germs",
    "Violet Crystal",
    "Waboku",
    "Wall of Illusion",
    "Wall Shadow",
    "Warrior of Tradition",
    "Wasteland",
    "Water Magician",
    "Water Omotics",
    "Wattkid",
    "Weather Report",
    "Whiptail Crow",
    "White Hole",
    "White Magical Hat",
    "Winged Dragon, Guardian of the Fortress #1",
    "Winged Dragon, Guardian of the Fortress #2",
    "Wingweaver",
    "Witch of the Black Forest",
    "Witch's Apprentice",
    "Witty Phantom",
    "Wodan the Resident of the Forest",
    "World Suppression",
    "Wow Warrior",
    "Yado Karu",
    "Yami"
]

# for card in eds_cards:
    # if card not in imperial_cards:
        # attribute = 'None'
        # level = 0
        # atk = 0
        # defn = 0
        # try:
            # for set in data2[card]['set_chronology_ocg']:
                # try:
                    # attribute = card_info[card]['attribute']
                    # level = card_info[card]['level']
                    # atk = card_info[card]['atk']
                    # defn = card_info[card]['def']
                    # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set[0] + ' (OCG)\t' + set[1].split('/')[3], months[int(set[1].split('/')[2])], set[1].split('/')[1])
                # except:
                    # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set[0] + ' (OCG)\t' + set[1].split('/')[3], months[int(set[1].split('/')[2])], set[1].split('/')[1])
        # except:
            # try:
                # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']))
            # except Exception as e:
                # pass

for card in data2:
    for set in data2[card]:
        try:
            date_ = parser.parse(data2[card][set]['set_chronology_tcg'][1]).date()
            if date_ <= yugikaiba:
                attribute = 'None'
                level = 0
                atk = 0
                defn = 0
                try:
                    attribute = card_info[card]['attribute']
                    level = card_info[card]['level']
                    atk = card_info[card]['atk']
                    defn = card_info[card]['def']
                    print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set + '\t' + data2[card][set]['set_chronology_tcg'][1])
                except:
                    print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set + '\t' + data2[card][set]['set_chronology_tcg'][1])
        except:
            pass

# for card in eds_cards:
    # # printed = False
    # # if card not in eds_cards:
    # try:
        # attribute = 'None'
        # level = 0
        # atk = 0
        # defn = 0
        # for set in data2[card]:
            # try:
                # date_tcg = parser.parse(data2[card][set]['set_chronology_tcg'][1]).date()
                # if date_tcg <= eds:
                    # try:
                        # attribute = card_info[card]['attribute']
                        # level = card_info[card]['level']
                        # atk = card_info[card]['atk']
                        # defn = card_info[card]['def']
                        # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set + '\t' + data2[card][set]['set_chronology_tcg'][1])
                    # except:
                        # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set + '\t' + data2[card][set]['set_chronology_tcg'][1])
                    # # printed = True
            # except Exception as e:
                # # print(e)
                # pass
        # try:
            # # if printed == False:
            # for set in data2[card]['set_chronology_ocg']:
                # try:
                    # attribute = card_info[card]['attribute']
                    # level = card_info[card]['level']
                    # atk = card_info[card]['atk']
                    # defn = card_info[card]['def']
                    # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set[0] + ' (OCG)\t' + set[1].split('/')[3], months[int(set[1].split('/')[2])], set[1].split('/')[1])
                # except:
                    # print(card + '\t' + card_info[card]['type'] + '\t' + attribute + '\t' + card_info[card]['race'] + '\t' + str(level) + '\t' + str(atk) + '\t' + str(defn) + '\t' + str(card_info[card]['id']) + '\t' + set[0] + ' (OCG)\t' + set[1].split('/')[3], months[int(set[1].split('/')[2])], set[1].split('/')[1])
        # except Exception as e:
            # # print(e)
            # pass
    # except:
        # pass

f.close()
f2.close()